### ISSUE TITLE
silent failure querying large github repo

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#1008]
This finds no results:

select * from github_commit where repository_full_name = 'microsoft/vscode' and author_login = 'octref'

There should be many: https://github.com/microsoft/vscode/commits?author=octref 

Actually, there should be 657, I know this because I was able to use Steampipe to cache all of that repo's commits.

(Just FYI, I've been doing a ton of analysis against that repo and in general it's absolutely amazing how robustly the GitHub plugin can pull in data from that API. I have a query pipeline that takes an hour to run, I have run it multiple times, and only twice was there any complaint from the API requiring a backoff.)

**Comment by kaidaguerre** [comment]
@judell are you still seeing this?

**Comment by judell** [comment]
Nope, all good now.
