### ISSUE TITLE
`progress` flag for `check` requires an `=`

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#1010]
does not work:
```
steampipe check control.cis_v140_1_1 --progress false
```

works:
```
steampipe check control.cis_v140_1_1 --progress=false
```

**Comment by kaidaguerre** [comment]
update the docs to describe usage

**Comment by binaek** [comment]
This is a known issue with [cobra](https://github.com/spf13/cobra) which we use internally for handling command line input

It's outlined at https://github.com/spf13/cobra/issues/613

Let me look at alternative approaches

**Comment by kaidaguerre** [comment]
@binaek can we just make sure that the documentation/help is clear about usage
