### ISSUE TITLE
`markdown` output format for `check` `export`

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#1011]
Output we are working towards (not matching up the numbers):

# Steampipe Report

## Benchmark Title
| Alarm    | Ok       | Info     | Error    | Skip     |
|---------:|---------:|---------:|---------:|---------:|
| 3        | 4        | 1        | 0        | 10       |

### Control Title
| Alarm    | Ok       | Info     | Error    | Skip     |
|---------:|---------:|---------:|---------:|---------:|
| 3        | 4        | 1        | 0        | 10       |
---
> Error: *There was an error in this control*
---

### Control Title 2
| Alarm    | Ok       | Info     | Error    | Skip     |
|---------:|---------:|---------:|---------:|---------:|
| 3        | 4        | 1        | 0        | 10       |
---
|        |   |   |   |
| ------ | - | - | - |
| ALARM  | Resource Reason | Dimension 1-1 | Dimension 1-2 |
| OK     | Resource Reason | Dimension 2-1 | Dimension 2-2 |
| ERROR  | Resource Reason | Dimension 3-1 | Dimension 3-2 |
| SKIP   | Resource Reason | Dimension 4-1 | Dimension 4-2 |
| INFO   | Resource Reason | Dimension 5-1 | Dimension 5-2 |
---

**Comment by e-gineer** [comment]
# HIPAA

| | TOTAL | 135 |
|-|-|-|
| ✅ | OK | 64 |
| ⇨ | Skip | 0 |
| ℹ | Info | 0 |
| ❌ | Alarm | 71 |
| ❗ | Error | 0 |

## 1.1 S3 bucket has mandatory tags

| OK | Skip | Info | Alarm | Error | Total |
|-|-|-|-|-|-|
| 0 | 0 | 0 | 49 | 0 | 49 |

| | Reason | Dimensions |
|-------|---------|--------|
| ❌ | codepipeline-us-east-2 is missing tags ["owner", "env"] | `us-east-2` `111122223333` |
| ❌ | graphql-api-dev-serverlessdeploymentbucket is missing tags ["owner", "env"] | `us-east-1` `111122223333` |
| ✅ | serverless-graphql-appsy-serverlessdeploymentbuck is missing tags ["owner", "env"] | `us-east-2` `111122223333` |

| | Reason | Dimensions |
|-------|---------|--------|
| ❌ | codepipeline-us-east-2 is missing tags ["owner", "env"] | `us-east-2` `111122223333` |
| ❌ | graphql-api-dev-serverlessdeploymentbucket is missing tags ["owner", "env"] | `us-east-1` `111122223333` |
| ✅ | serverless-graphql-appsy-serverlessdeploymentbuck is missing tags ["owner", "env"] | `us-east-2` `111122223333` |

## 1.2 H3 is the lowest heading level, even if the check is nested lower

| OK | Skip | Info | Alarm | Error | Total |
|-|-|-|-|-|-|
| 3 | 0 | 0 | 2 | 0 | 5 |

| | Reason | Dimensions |
|-------|---------|--------|
| ✅ | serverless-graphql-appsy-serverlessdeploymentbuck is missing tags ["owner", "env"] | `us-east-2` `111122223333` |

### 1.2 Description is only shown if set

*I am the description, when set I'm shown in italics without a prefix or header.*

| OK | Skip | Info | Alarm | Error | Total |
|-|-|-|-|-|-|
| 3 | 0 | 0 | 2 | 0 | 5 |

| | Reason | Dimensions |
|-------|---------|--------|
| ✅ | serverless-graphql-appsy-serverlessdeploymentbuck is missing tags ["owner", "env"] | `us-east-2` `111122223333` |

_Report run at `2021-10-20 22:19:49` using [`Steampipe v0.9.0`](https://steampipe.io) in dir `/users/nathan/src/steampipe-checks`._

**Comment by e-gineer** [comment]
The above comment is a proposed markdown format. Here is the raw markdown code:
```
# HIPAA

| | TOTAL | 135 |
|-|-|-|
| ✅ | OK | 64 |
| ⇨ | Skip | 0 |
| ℹ | Info | 0 |
| ❌ | Alarm | 71 |
| ❗ | Error | 0 |

## 1.1 S3 bucket has mandatory tags

| OK | Skip | Info | Alarm | Error | Total |
|-|-|-|-|-|-|
| 0 | 0 | 0 | 49 | 0 | 49 |

| | Reason | Dimensions |
|-------|---------|--------|
| ❌ | codepipeline-us-east-2 is missing tags ["owner", "env"] | `us-east-2` `111122223333` |
| ❌ | graphql-api-dev-serverlessdeploymentbucket is missing tags ["owner", "env"] | `us-east-1` `111122223333` |
| ✅ | serverless-graphql-appsy-serverlessdeploymentbuck is missing tags ["owner", "env"] | `us-east-2` `111122223333` |

| | Reason | Dimensions |
|-------|---------|--------|
| ❌ | codepipeline-us-east-2 is missing tags ["owner", "env"] | `us-east-2` `111122223333` |
| ❌ | graphql-api-dev-serverlessdeploymentbucket is missing tags ["owner", "env"] | `us-east-1` `111122223333` |
| ✅ | serverless-graphql-appsy-serverlessdeploymentbuck is missing tags ["owner", "env"] | `us-east-2` `111122223333` |

## 1.2 H3 is the lowest heading level, even if the check is nested lower

| OK | Skip | Info | Alarm | Error | Total |
|-|-|-|-|-|-|
| 3 | 0 | 0 | 2 | 0 | 5 |

| | Reason | Dimensions |
|-------|---------|--------|
| ✅ | serverless-graphql-appsy-serverlessdeploymentbuck is missing tags ["owner", "env"] | `us-east-2` `111122223333` |

### 1.2 Description is only shown if set

*I am the description, when set I'm shown in italics without a prefix or header.*

| OK | Skip | Info | Alarm | Error | Total |
|-|-|-|-|-|-|
| 3 | 0 | 0 | 2 | 0 | 5 |

| | Reason | Dimensions |
|-------|---------|--------|
| ✅ | serverless-graphql-appsy-serverlessdeploymentbuck is missing tags ["owner", "env"] | `us-east-2` `111122223333` |

_Report run at `2021-10-20 22:19:49` using [`Steampipe v0.9.0`](https://steampipe.io) in dir `/users/nathan/src/steampipe-checks`._
```
