### ISSUE TITLE
steampipe should not create connection config file when a specific version of a plugin is installed

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#1052]
**NOTE**
This issue should resolve https://github.com/turbot/steampipe/issues/1043 and https://github.com/turbot/steampipe-plugin-aws/issues/697

**Describe the bug**
steampipe should not create a connection config file when a specific version of a plugin is installed. If I install aws@0.36.0, steampipe should not create a connection config file aws.spc, it should only create one when aws@latest is being installed.

**Steampipe version (`steampipe -v`)**
Example: v0.9.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by cbruno10** [comment]
@kaidaguerre From our conversation outside GitHub, it seems we need input from @johnsmyth on how we deal with default connection config for versions of plugins other than `latest`.

@johnsmyth Any thoughts on this?

**Comment by cbruno10** [comment]
@kaidaguerre @johnsmyth We had discussed earlier today about possibly getting this fixed in an upcoming releasing, so bumping here for visibility/tracking

**Comment by kaidaguerre** [comment]
replaced with https://github.com/turbot/steampipe/issues/1675
