### ISSUE TITLE
Introduce --output-brief or --brief flag

### ISSUE THREAD

**Issue by ecktom** [turbot/steampipe#1058]
**Is your feature request related to a problem? Please describe.**
We're running steampipe in CI where we mostly use `json` and `md` output formats. The only thing I’m missing in that CI context is gaining a fast glance on the failed controls only. Is there a way to limit the output to “failed only”? I know this has been implemented for the `brief` output format but wouldn’t it make sense to make this an independent flag like `--output-biref` which can be combined with any output? Haven’t looked into the sources yet but from my perspective it should be a simple filter before processing the output.
I'm not entirely sure how this could look like in conjunction with `--export`. So basically what we try to achieve is getting the full results as `json` via `--export` (get's uploaded to s3 to keep track of the progress) and highlight the failed controls using `md` output in the build annotations of our CI system.
From my perspective I would expect --export to always export the full set. If I want I, could get a brief JSON also by doing `--output=json --output-brief > brief.json`

**Comment by kaidaguerre** [comment]
@ecktom sorry for not responding sooner. Thanks for raising this - this sounds like a sensible requirement. I will look into it

**Comment by ecktom** [comment]
@kaidaguerre Is there anything I can help with to speed this up? ;)
