### ISSUE TITLE
ColumnType_IPADDR is not working for CIDR range 

### ISSUE THREAD

**Issue by Subhajit97** [turbot/steampipe#108]
Steampipe version
```
0.1.1
```

```
{
	Name:        "dest_range",
	Description: "The destination range of outgoing packets that this route applies to.",
	Type:        proto.ColumnType_IPADDR,
}
```
When the field value is `10.0.0.0/16`, it is throwing error 
`Error: pq: rpc error: code = Unknown desc = dest_range: invalid ip address 10.0.0.0/16`

If the value is single IP address (i.e. `0.0.0.0`), it is working properly

**Comment by e-gineer** [comment]
If this field is for a CIDR range then please try using ColumnType_CIDR.

ColumnType_IPADDR Is for IPs, not for CIDRs.

**Comment by Subhajit97** [comment]
The value of this field can be an IP address or CIDR range. I had tried with both but it failed.

**Comment by johnsmyth** [comment]
I believe that it is a bug in the sdk here: https://github.com/turbot/steampipe-plugin-sdk/blob/main/plugin/table_column.go#L170.  according to the postgres docs, the inet type can be a single ip or a cidr:  'The input format for this type is address/y where address is an IPv4 or IPv6 address and y is the number of bits in the netmask. If the /y portion is missing, the netmask is 32 for IPv4 and 128 for IPv6, so the value represents just a single host. On display, the /y portion is suppressed if the netmask specifies a single host.'  (https://www.postgresql.org/docs/current/datatype-net-types.html#DATATYPE-INET)

**Comment by kaidaguerre** [comment]
this is expected behaviour - ip address columns are validated to be an ip address and cidr range columns are validated to be a cidr range

A new column type `ColumnType_INET` will be added which may be either cidr range or ip address 
https://github.com/turbot/steampipe-plugin-sdk/issues/22
