### ISSUE TITLE
database `username` is not escaped when setting service `search_path`

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#1082]
steampipe crashes with usernames having special characters in them:
`alter user vha-dianto set search_path to "public","all_digitalocean","acmedo1","internal";`

**Comment by e-gineer** [comment]
@binaek I believe this is an identifier / quoting problem, not an escaping problem.

All user managed identifiers (user names, schema names, etc) must be quoted identifiers when we do our SQL queries.

So, we want the query to become:
```
alter user "vha-dianto" set search_path to "public","all_digitalocean","acmedo1","internal";
```

Reference - https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
