### ISSUE TITLE
Add ability to show info/warning messages when running queries

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#1090]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to show users messages when plugin tables are loaded, or when a query is run, that lets them know information I'd normally have to put into logs. For instance, if I have a plugin that loads CSV files, I'd like to be able to display a message after a user runs `steampipe query` interactively letting them know if some CSV files could not be created as tables, but still allowing them to run queries against other valid tables.

**Describe the solution you'd like**
I'd like to be able to define messages that will be shown to users when they run queries (non-interactively and interactively) that do not terminate the process.

**Describe alternatives you've considered**
Putting messages into logs, but this requires users to know where to check/sift through the logs.

**Additional context**

**Comment by judell** [comment]
👍
