### ISSUE TITLE
`Error: Plugin Listing failed - syntax error at or near "-"` when db users contain a dash 

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe#1094]
**Describe the bug**
When any database user that is in `steamipe_users` contains a dash, steampipe  fails with an error.

**Steampipe version (`steampipe -v`)**
steampipe version 0.9.0

**To reproduce**
1. connect to the steampipe db as `root`
2. create a user that has a dash in it: `create user "user-with-dash"`
3. add the user to `steampipe_users`:   `grant steampipe_users to "user-with-dash"`
4. Run `steampipe plugin list`:
```bash
$ steampipe plugin list
Error: Plugin Listing failed - syntax error at or near "user"
```
**Expected behavior**
should not fail

**Additional context**

**Comment by binaek** [comment]
@johnsmyth  this may be related to #1082 

We will take a look
