### ISSUE TITLE
Trying to re-execute prepared statements on query init masks real error

### ISSUE THREAD

**Issue by robinp-tw** [turbot/steampipe#1144]
**Describe the bug**
If you have multiple `fooN.sql` files in local folder, steampipe seems to create a prepared statement for each on `steampipe query` startup.
If there's say a syntax error in one of the SQLs, the code (https://github.com/turbot/steampipe/blob/main/db/db_common/prepared_statements.go#L34) tries to re-execute the sqls separately to see what the problem was. But this will result in an error like
> Error: failed to create prepared statement for query.paramy: pq: prepared statement "local_paramy_q94be" already exists
for the prepared statements that succeeded.

**Steampipe version (`steampipe -v`)**
Example: v0.9.1, also it seems head

**To reproduce**
Have multiple sql files in the dir, have some error (like a mistyped field name) in one of the queries, start `steampipe query`, wait for lazy pg statements to happen (few secs), observe unhelpful (and deceiving) error.

**Expected behavior**
The original error should be printed, not the masking one.

**Additional context**
See code location. Maybe don't bundle the queries together? Or handle this prepared statement case already exists case in the details loop and skip over it? Etc.

Thanks btw, really nice tool!

**Comment by robinp-tw** [comment]
See https://github.com/robinp-tw/steampipe/commit/022eb365a2753bb06168b5e0337e6215569992de for an ugly workaround.

**Comment by judell** [comment]
Thanks @robinp-tw, and welcome to Steampipe!

**Comment by robinp-tw** [comment]
Thanks! Actually this part of the logic needs a deeper inspection / testing for various usecases.

For example, if I manage to ruin the syntax of an sql query while `steampipe query` is running, then:
- all existing prepared statements are deallocated (ok so far)
- the batch sql will try to create statements for the new queries (will fail on the syntax-ruined one)
- the one-by-one sql will retry one-by-one, but bail out on the first non-skipped error (so this leaves some otherwise fine queries unprepared, depending on the order)

Then, when I fix the syntax, then under the hood:
- all the previously known named queries try to get deallocated - this will fail since some of the good queries didn't even get allocated in the first place (see end of previous block)
- UpdatePreparedStatements bails out, never tries to prepare all the (now good) queries.

But I assume this is not the final logic you wanted to do anyway, but something more granular. I wonder if executing the prepares/deallocs in a batch is worth it - probably not much win, compared to the complexity it causes?

**Comment by kaidaguerre** [comment]
@robinp-tw thanks for taking the time to raise this. 

As it happens I am working on an update right now that will fix this issue.
```
Maybe don't bundle the queries together
``` 
Yes, this is approach I am taking. I'll be sure to test this scenario in the updated code

**Comment by kaidaguerre** [comment]
closed by 3bb4bf97d3a857ad985ba3a4f01d4f2324ea32c4
