### ISSUE TITLE
should all plugins use ConnectionManager.Cache?

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#1150]
Examples that don't include older ones like Slack, GitHub.

I only just learned yesterday from @kaidaguerre that there was a plugin-managed cache. Should all plugins use it, including ones made before ConnectionManager.Cache was invented. If so, why?

**Comment by kaidaguerre** [comment]
@judell I don't quite understand the question?

**Comment by judell** [comment]
In newer plugins, like Splunk, it seems we use the plugin-managed cache for the connection to the Go SDK's client. 

Is that a recommended best practice? If so, why? And, should older plugins be updated accordingly?

**Comment by e-gineer** [comment]
Plugins should cache credential information etc where possible, and the SDK provided cache is definitely the most efficient and well managed way to do it.

Suggest opening issues on any plugins that could use updates in this regard as appropriate. Closing here.
