### ISSUE TITLE
Stabilize `service stop` 

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#1180]
`service stop` sometimes does not stop the service and leaves it in a bad state.

This is evident from the message:

`Error: service is running in an unknown state [PID: xxxxx] - try killing it with steampipe service stop --force`

which comes up from time-to-time

**Comment by kaidaguerre** [comment]
when leaving services running (e.,g. shutting down debugging), a `service stop --force` does not always closes everything - sometimes it must be run several time
