### ISSUE TITLE
slightly confusing message when uninstalling CSV plugin

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#1194]
```
$ steampipe plugin uninstall csv

The following files have steampipe connections using the 'csv' plugin:

        * 'csv' in /home/jon/.steampipe/config/csv.spc, line 1

Please remove them to continue using steampipe

Uninstalled plugin csv
```

To me this implied commenting out the `paths` argument in `csv.spc` but that results in:

`Error: failed to load connection 'csv': no plugin installed matching csv`

I think it's the `* 'csv'` that's misleading because it resembles what's in the `paths` argument. Perhaps replace it with the word `connection`?

```
The following files have steampipe connections using the 'csv' plugin:

        connection 'csv' in /home/jon/.steampipe/config/csv.spc, line 1
```

**Comment by cbruno10** [comment]
@judell I've transferred this issue to the Steampipe repo, as the messages you're seeing are built within the CLI, so this would probably be the best place to discuss general wording with the CSV plugin as a good example

**Comment by kaidaguerre** [comment]
covered by https://github.com/turbot/steampipe/issues/1158

**Comment by judell** [comment]
Thanks again, @kaidaguerre!
