### ISSUE TITLE
Add support for test unit outputs - junit

### ISSUE THREAD

**Issue by jonesy1234** [turbot/steampipe#1196]
**Is your feature request related to a problem? Please describe.**

The current output formats are really great for user feedback however it would be great be able to track the history through other CI/CD tools that pull in test format like junit to track the compliance across multiple runs. We can currently diff between runs from the output but native support would be great.

**Describe the solution you'd like**
Additional output format for junit or something similar that is supported by common tool as follows:-

- https://docs.aws.amazon.com/codebuild/latest/userguide/test-reporting.html
- https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml

**Describe alternatives you've considered**

Only alternative I see at the moment is to perform a diff on the current outputs formats such as `diff out1.csv out2.csv`

**Additional context**

Discussed in https://steampipe.slack.com/archives/C01UECB59A7/p1638186813353000

**Comment by e-gineer** [comment]
@jonesy1234 Thanks for raising this issue - agree that support for test formats would be awesome and that JUnit is a good starting point. I particularly appreciated the references you shared there!

Note for potential contributors ... The CLI has a number of formatters already, that produce results using templates. The code for those is available in this directory - https://github.com/turbot/steampipe/tree/main/control/controldisplay. Adding new formatters should be fairly straight forward, and any suggestions to make it even more extensible would be great too!
