### ISSUE TITLE
Need a feature for inspect in CLI mode

### ISSUE THREAD

**Issue by RahulLah19** [turbot/steampipe#1197]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Need a feature similar to .inspect in interactive mode into CLI mode. Currently, we are able to view the
schema using .inspect in interactive mode, can we have a query/any alternate to view the schema via CLI mode. 

**Describe alternatives you've considered**

**Additional context**
### Result via Interactive mode
![image](https://user-images.githubusercontent.com/47312740/144194068-8f103fa4-1d9e-4884-8062-bb077645bee9.png)
### Result via CLI mode
![image](https://user-images.githubusercontent.com/47312740/144194385-3307f3a2-9e0e-4ba0-84b9-eb2e9b24df5c.png)

**Comment by michaelkubi** [comment]
any update about that?

**Comment by binaek** [comment]
@michaelkubi `.inspect` was designed to be a convenient way to extract information about the loaded connections in the interactive prompt.

Have you considered listing out the information from the `postgres` supplied `information_schema` tables?

**Comment by binaek** [comment]
@michaelkubi This is the SQL query that powers the `.inspect` functionality under-the-hood:
```
WITH distinct_schema AS (
	SELECT DISTINCT(foreign_table_schema) 
	FROM 
		information_schema.foreign_tables 
	WHERE 
		foreign_table_schema <> 'steampipe_command'
)
SELECT
    table_name,
    column_name,
    column_default,
    is_nullable,
    data_type,
    udt_name,
    table_schema,
    (COALESCE(pg_catalog.col_description(c.oid, cols.ordinal_position :: int),'')) as column_comment,
    (COALESCE(pg_catalog.obj_description(c.oid),'')) as table_comment
FROM
    information_schema.columns cols
LEFT JOIN
    pg_catalog.pg_namespace nsp ON nsp.nspname = cols.table_schema
LEFT JOIN
    pg_catalog.pg_class c ON c.relname = cols.table_name AND c.relnamespace = nsp.oid
WHERE
	cols.table_schema in (select * from distinct_schema)
	OR
    LEFT(cols.table_schema,8) = 'pg_temp_'
```
