### ISSUE TITLE
Trying to run a named query from a SQL file gives an error if you have an empty mod.sp file

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/steampipe#1198]
**Describe the bug**
If you run a named query from a sql file e.g. `foo.sql` -> `steampipe query query.foo` and also have an empty mod.sp file in there with no mod definition, you get an error:

`Error: failed to load workspace: no mod definition found in...`

**Steampipe version (`steampipe -v`)**
v0.10.0

**To reproduce**
Create a .sql file with a query in. Also create an empty mod.sp file and then run `steampipe query query.<name>` and you will see the error.

**Expected behavior**
As I haven't actually created a mod, I'd expect an implicit mod to be created that enables me to run the query.

**Comment by pskrbasu** [comment]
Also running `steampipe mod init` when there's an empty mod.sp file in a directory:
```
Working folder already contains a mod definition file
Created mod definition file '/Users/pskrbasu/pskr/test/mod.sp'
```
It says created mod definition file - but no file gets created
