### ISSUE TITLE
Add support for query cancellation

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#120]
ctrl+C while query is running will cancel query (after confirmation?)

need to look at full cancellation journey

**Comment by binaek89** [comment]
depends on #272

**Comment by vielmetti** [comment]
This would be helpful especially for long-running or runaway queries.

**Comment by kaidaguerre** [comment]
(from https://github.com/turbot/steampipe/issues/288)

Is your feature request related to a problem? Please describe.

Queries can take a long time (e.g. event lists) and there is no way to abort in interactive mode. Ctrl-C does not register.

Describe the solution you'd like

Ctrl-C should abort the query and return any (partial) results collected so far.

Describe alternatives you've considered

None.

Additional context

See turbot/steampipe-plugin-equinix#2

**Comment by kaidaguerre** [comment]
fixed by ba217d00bcdd80657f81ec0ff4a6e087f866db41
