### ISSUE TITLE
Investigate `signal.NotifyContext` instead of having custom `context` cancel on `signal`

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#1218]
`steampipe` uses the following construct for intercepting `os interrupts`:
```
c, cancel := context.WithCancel(ctx)
startCancelHandler(cancel)
```
where `startCancelHandler` is defined as:
```
func startCancelHandler(cancel context.CancelFunc) {
	sigIntChannel := make(chan os.Signal, 1)
	signal.Notify(sigIntChannel, os.Interrupt)
	go func() {
		<-sigIntChannel
		log.Println("[TRACE] got SIGINT")
		// call context cancellation function
		cancel()
		// leave the channel open - any subsequent interrupts hits will be ignored
	}()
}
```

**Comment by binaek** [comment]
`golang` already implements a `signal.NotifyContext` which cancels a child of the passed in `context` when any of the passed in signals arrive to the program.

if possible, we should replace the `startCancelHandler` with `signal.NotifyContext`

**Comment by pskrbasu** [comment]
Not planned. Tracked in https://github.com/turbot/steampipe/issues/3764
