### ISSUE TITLE
some plugins fail to update when steampipe is running as a service

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#1248]
This happened (in v10):

```
Skipped the following plugins:

Plugin:   googlesheets@latest
Reason:   plugin installation failed: could not unzip /home/ec2-user/.steampipe/plugins/tmp-d25f-4da6-b698/steampipe-plugin-googlesheets_linux_amd64.gz to /home/ec2-user/.steampipe/plugins/hub.steampipe.io/plugins/turbot/googlesheets@latest

Plugin:   csv@latest
Reason:   plugin installation failed: could not unzip /home/ec2-user/.steampipe/plugins/tmp-9537-481e-9d56/steampipe-plugin-csv_linux_amd64.gz to /home/ec2-user/.steampipe/plugins/hub.steampipe.io/plugins/turbot/csv@latest
```

After `steampipe service stop --force` I was able to update them.

Just a coincidence that both are dynamic-schema plugins?

**Comment by judell** [comment]
> Just a coincidence that both are dynamic-schema plugins?
 
 Yeah. It's just the case that you need to force-quit everything before updating.

**Comment by kaidaguerre** [comment]
@judell what is the full reproduction for this please

**Comment by pskrbasu** [comment]
Reported again in https://steampipe.slack.com/archives/C01UECB59A7/p1686145108011689

**Comment by KTamas** [comment]
This just happened to me last week.
