### ISSUE TITLE
Leaving an interactive session open across dates logs to the previous date's DB log file

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/steampipe#125]
**Issue**

If you open an interactive session (`steampipe query`) on say `2020-01-31` and then come back to query in that same session on `2020-02-01`, DB logs are written out into the log file for `2020-01-31` until you exit and restart your session.

**Expected Outcome**

Logs written to `2020-02-01` log file

**Actual Outcome**

Logs written to `2020-01-31` log file

**Env**

CLI: `0.1.0`
OS: `macOS Big Sur 11.1`
Terminal: `iTerm 3.4.3` / `zsh`

**Comment by binaek** [comment]
This is fixed in `main`
