### ISSUE TITLE
Support introspection queries to enable codegen. 

### ISSUE THREAD

**Issue by trevordilley** [turbot/steampipe#1251]
**Is your feature request related to a problem? Please describe.**
I would like to use powerful tools like [PrismaJS](https://www.prisma.io/) to build administrative client applications in my organization. 

I believe these tools rely on queries like 

```
SELECT * FROM information_schema.tables
WHERE table_schema = 'public';
```

To generate useful static type information and do their codegen in general. 

**Describe the solution you'd like**
I would like to execute a command like `npx prisma db pull` to generate the prisma client. This exposes a really great API to execute queries against an SQL database. 

Currently I receive this error:
```
Introspecting based on datasource defined in prisma/schema.prisma …
Error:
P4001 The introspected database was empty:
```

I believe it's because when I run the `information_schema` query above, I see zero tables. 

**Describe alternatives you've considered**
Currently I believe I could manually define this schema, however that is error prone, especially when I the schema changes (such as adding a new AWS account). 

Would be wonderful to simply pull the new types down whenever a change occurs! 
**Additional context**
Another powerful tool that I think could benefit from this feature would be [Hasura](https://hasura.io/). I believe I receive a permission error with that tool however, probably related to the underlying architecture of how `steampipe` works, but it's in a similar vein. Being able to run `steampipe` in service mode in a docker container really opens up some amazing possibilities for robust and _business specific_ solutions! 

Thanks!

**Comment by binaek** [comment]
@trevordilley this is probably because the tables that you see in `steampipe` are actually tables in `foreign schema` which effectively makes them `foreign tables`. 

The tables are not part of the `public` schema at all - rather each connection becomes it's own schema where the tables are registered.

**Comment by e-gineer** [comment]
@trevordilley I love the idea of PrismaJS / Hasura working with Steampipe!

To build on @binaek's comment, Postgres has slightly different information schema for regular tables vs tables from a foreign schema. Most tools (e.g. DB editors) pull from both for their schema discovery, but some do not. It seems from your issue that PrismaJS does not (yet). Full introspection should be possible once they have foreign schema support.

You can learn more about schemas in Steampipe at https://steampipe.io/docs/using-steampipe/managing-connections. Basically each Steampipe connection is setup as a separate Postgres schema. We leave the `public` schema empty and open for your scratch work / tables / views / etc.

Hope that helps. Please let us know anything we can do to help you build on Steampipe!

**Comment by trevordilley** [comment]
Thanks! I'll see about getting them to support such introspection on their end!
