### ISSUE TITLE
Better Docker support

### ISSUE THREAD

**Issue by trevordilley** [turbot/steampipe#1252]
**Is your feature request related to a problem? Please describe.**
Service mode in `steampipe` is great. However the first thing I want to do is dockerize `steampipe` so I can treat just like another Postgres database and build awesome BI tools with it! 

Currently I have a Dockerfile like follows:

```
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install --yes curl
RUN /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)"

RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
USER docker

RUN steampipe -v
RUN steampipe plugin install steampipe
RUN steampipe plugin install jira
ENTRYPOINT steampipe service start && tail -f /dev/null
```

While this is fine, it does feel kinda _hacky_ (the `tail -f /dev/null` in the `ENTRYPOINT` is how I keep the service running in `docker-compose`

**Describe the solution you'd like**
It would be wonderful to have an official Docker container, perhaps one where I can either specify my plugins or just pass in environment variables specific to a plugin and it would figure out the rest. (Might just be a container that contains all the plugins? Unsure there.) 

**Describe alternatives you've considered**
No real alternatives I can think of, other than just having `steampipe` running as a process on the EC2 (perhaps installed in a `user_data` script?) But that seems far from ideal! 

**Additional context**
Mostly I'd love to treat `steampipe` as a legit, long lived db that I can use as a datasource for API's, Crons, and even direct browser and mobile client interaction depending on the use-case. A solid docker story would enable a great deal of that! 

Thanks!

**Comment by rajlearner17** [comment]
@trevordilley **Appreciate** checking out Steampipe and your feedback on it. Our respective team will analyze this and respond.

**Comment by binaek** [comment]
@trevordilley there is an officially supported `steampipe` image in https://hub.docker.com/r/turbot/steampipe

Can you take a look and see that it works for you?

Additional documentation is available at https://steampipe.io/docs/develop/containers

**Comment by trevordilley** [comment]
Oh neat I'll have a look! Thanks!
