### ISSUE TITLE
Can/should steampipe cooperate with other fdws?

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#1272]
As a Steampipe user, I'd like to mix plugin-accessible data sources with data sources provided by other fdws, such as `sqlite_fdw`.

It's possible, though inconvenient, to do this now.

In a vanilla instance of Postgres 12 I built and installed https://github.com/pgspider/sqlite_fdw, which produces these files.

```
/usr/lib/postgresql/12/lib
  sqlite_fdw.so

/usr/share/postgresql/12/extension
  sqlite_fdw.control
  sqlite_fdw--1.0.sql
  sqlite_fdw--1.0--1.1.sql  
```

I "installed" by copying to the corresponding Steampipe directories: `/.steampipe/db/12.1.0/postgres/lib/postgresql` and `/.steampipe/db/12.1.0/postgres/share/postgresql/extension`.

Then created a sqlite db.

```
$ sqlite3 /tmp/test.db
> create table t1_sqlite(a int, b text);
> insert into t1_sqlite(a, b) values (1, "one");
```

Then, as root in steampipe, created an fdw server for it, and imported its schema.

```
steampipe# CREATE SERVER sqlite_server FOREIGN DATA WRAPPER sqlite_fdw OPTIONS (database '/tmp/test.db');
CREATE SERVER

steampipe# IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server INTO public;	
```

Switching to user steampipe.

```
steampipe=> \dew
                       List of foreign-data wrappers
          Name          | Owner |      Handler       |      Validator       
------------------------+-------+--------------------+----------------------
 sqlite_fdw             | root  | sqlite_fdw_handler | sqlite_fdw_validator
 steampipe_postgres_fdw | root  | fdw_handler        | fdw_validator


steampipe=> \d t1_sqlite 
                Foreign table "public.t1_sqlite"
 Column |  Type  | Collation | Nullable | Default | FDW options 
--------+--------+-----------+----------+---------+-------------
 a      | bigint |           |          |         | 
 b      | text   |           |          |         | 
Server: sqlite_server
FDW options: ("table" 't1_sqlite')


steampipe=> select * from t1_sqlite ;
 a |  b  
---+-----
 1 | one
```

So it's doable, but clumsy. A smoother approach might look like:

- Steampipe ships with `sqlite_fdw`

- Users interact with `sqlite.spc` to activate it, point it at sqlite dbs, and import their schemas

Questions:

- Can this be made practical for sqlite?

- If so, could the method generalize to other fdws? Multicorn, in particular, would be a gateway to many data sources.

- What are the pros and cons vis a vis conventional Steampipe plugins for such sources?

**Comment by binaek** [comment]
@judell `steampipe` already ships with multiple extensions which are just waiting there to be enabled.

Reference: `~/.steampipe/db/12.1.0/postgres/lib/postgresql/`

We could look into auto activation of extensions based on the `default.spc` file in `~/.steampipe/config` and add an extra config option which enables/disables extensions.

**Comment by judell** [comment]
@binaek 

> already ships with multiple extensions which are just waiting there to be enabled.

Yep, including `tablefunc` which (thanks!) is now on by default.

Things to consider:

- Which pre-installed extensions, beyond `tablefunc`, can usefully be pre-activated (or made user-activatable)?

- Which that aren't pre-installed? These fall into two categories:

  - non-fdw: for example, plpython, which is incredibly useful

  - fdw: sqlite, multicorn, etc.

In the fdw category, what I'm noticing is that if we just preinstalled- and -activated sqlite or multicorn) there would still be db-root-level admin to take full advantage of them. That's what prompts the thougth that these could be fully .spc-managed a la csv, airtable, googlesheets.

The broader question is about what the relationship could/should be between other fdws (which are, tbh, a very mixed bag) and ours. Do we want other fdws to be first-class citizens in steampipe? I'm not sure, just posing the question.

**Comment by mingfang** [comment]
Please allow standard fdw, e.g. postgres_fdw.
Since Steampipe is "just Postgres", there's not reason to not allow fdw.
