### ISSUE TITLE
steampipe.io Linux installation documentation

### ISSUE THREAD

**Issue by omerosaienni** [turbot/steampipe#128]
https://steampipe.io/downloads page for |Linux, I noticed step 1 is using sudo to install the app which installs it `/usr/local/bin` 

For step 3, it tells me how to install a plug in as
`steampipe plugin install steampipe` which will fail as not `sudo` 

![image](https://user-images.githubusercontent.com/39497847/106582686-2cdc2480-653c-11eb-97e6-325bd7f814b0.png)

But if I sudo it:
![image](https://user-images.githubusercontent.com/39497847/106582726-36658c80-653c-11eb-85eb-5b0dc319fc5e.png)

![image](https://user-images.githubusercontent.com/39497847/106582769-42e9e500-653c-11eb-8e4a-8ac13ba20691.png)

**Comment by dboeke** [comment]
@omerosaienni can you provide the operating system and other details of your installation?  I have tested on some different linux versions, and none require `sudo` for plugin installation.  For reference plugins are installed in `~/.steampipe/plugins` that directory should be owned by your user and minimum permissions 755
