### ISSUE TITLE
Trigger `less` usage for .inspect on large (wide) tables.

### ISSUE THREAD

**Issue by dboeke** [turbot/steampipe#130]
When using the inspect feature, it will can return a large data set for very wide columns.  It would be great to have the output pipe through `less` if too big for current console window.

**Comment by e-gineer** [comment]
Agreed .. here is a screenshot:
![image](https://user-images.githubusercontent.com/1328145/114640312-d6a70280-9c9d-11eb-8e2c-60f0dcab9159.png)

**Comment by binaek** [comment]
Not required anymore...

![Screenshot 2023-09-11 at 4 00 53 PM](https://github.com/turbot/steampipe/assets/1114038/b61aea81-4988-4b49-a4d1-1fa1683c36c5)

**Comment by binaek** [comment]
Not required anymore. Columns are wrapped to the available window width.

![Screenshot 2023-09-11 at 4 00 53 PM](https://github.com/turbot/steampipe/assets/1114038/cf91d562-b0bd-40b1-ab8f-12a823d54799)
