### ISSUE TITLE
HTML Output Report Filtering by Status 

### ISSUE THREAD

**Issue by fgomesz** [turbot/steampipe#1304]
It would be useful to have a filtering by status of the HTML report much like prowler.

steampipe azure --output html

**Comment by fgomesz** [comment]
Hi @e-gineer,

yes, it would be helpful to modify the HTML results to filter by controls in alarm

**Comment by ecktom** [comment]
We had some similar issues with eg. markdown https://github.com/turbot/steampipe/issues/1058

**Comment by fgomesz** [comment]
running the scan with just the "--output brief" flag is enough
