### ISSUE TITLE
Line-mode layout for report 'table' elements

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe#1408]
**Is your feature request related to a problem? Please describe.**
I would like an option to layout a report `table` resource similar to `line` mode in steampipe query, where each row is a label (the column name) and value.   This is useful for reports that provide details about a single resource

|  |   |
|-|-
| title         | my-instance
| instance_id   | i-0123456789abcdef
| instance_type | t2.small
| account_id    | 123456789012
| region        | us-east-1

**Comment by johnsmyth** [comment]
@MichaelBurgess @e-gineer maybe its a `transform`, like on a `chart` ?
```hcl
table {
  transform = "transpose"
  sql  = query.my_resource.sql
}
```

**Comment by johnsmyth** [comment]
I believe possible values of `none` and `transpose`, with a default of `none` is a good starting point.  I like the idea of showing multiple transposed items vertically as well!

**Comment by e-gineer** [comment]
How does the `transpose` behave if there are multiple rows of data in the table?

So we can more easily handle multiple rows I think that `type = "line"` or similar is a better approach? It could then display a list of detail tables.

**Comment by MichaelBurgess** [comment]
It's a fair point - `transpose` suggests that the data will be transposed into another table format. `type = "item"` suggests it works with an item at a time.

Regardless of the approach taken in HCL, it's worth noting that the resultant HTML will no longer be a table (don't think an issue, just worth mentioning given the name `table`).

**Comment by johnsmyth** [comment]
@e-gineer im not sure what you mean 'display a list of tables' ?  you would select an item from a list box or something?

I was thinking:


| title | instance_id | instance_type | account_id | region
|-|-|-|-|-
| my-instance      | i-0123456789abcdef| t2.small | 123456789012 | us-east-1
| another-instance | i-abcdef0123456789| m5.large | 123456789012 | us-east-2

transposes to 

|  |   | |
|-|-|-
| title         | my-instance         |  another-instance 
| instance_id   | i-0123456789abcdef  | i-abcdef0123456789
| instance_type | t2.small | m5.large 
| account_id    | 123456789012 | 123456789012
| region        | us-east-1 | us-east-2

**Comment by MichaelBurgess** [comment]
@johnsmyth I was not expecting the transposed item to be a table like you've specified, but actually more like a KVP for each item (where the key will be more subtly styled to give prominence to the value:

```
instance_id
i-0123456789abcdef

instance_type
t2.small

account_id
123456789012

region
us-east-1
```

@e-gineer / @johnsmyth sounds like we're not all aligned here, so we should discuss?

**Comment by MichaelBurgess** [comment]
@johnsmyth spoke with @e-gineer on this one - I think we've conflated 2 diff requirements - 1 is the ability to transform table data as per your example and the other is to present a `line` (naming consistent with CLI) view of a table row, which would be as per my description above. I have a path forward for now.

**Comment by MichaelBurgess** [comment]
@johnsmyth as discussed we'll deprioritize the `transform = "transpose"` stuff for now - suggest we add this later and raise a separate issue when we need it.
