### ISSUE TITLE
Steampipe service should stop after exiting a `steampipe report` session

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#1416]
**Describe the bug**
After exiting a `steampipe report` session with cmd+c, the service continues to run in the background, even after closing out any tabs/windows in my browser.

**Steampipe version (`steampipe -v`)**
v0.13.0-alpha.5

**To reproduce**
- Run `steampipe report` in a directory with at least 1 report
- Cancel that command with cmd+c (or your OS equivalent)
- Run `steampipe service status`

**Expected behavior**
The Steampipe service should stop automatically

**Additional context**

**Comment by binaek** [comment]
Solved by #1390 and #1393 

@kaidaguerre should we close this?
