### ISSUE TITLE
Counter chart titles are sometimes cut off and I can't view the full title by hovering

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#1420]
**Describe the bug**
When I shrink the window that contains a report, sometimes counter charts have their titles truncated, but I have no way of viewing the full title without copying the value and pasting it somewhere. Please see an example on the far right counter below.

<img width="1493" alt="Screen Shot 2022-02-08 at 5 26 35 PM" src="https://user-images.githubusercontent.com/12363488/153086243-faa9a363-3c8a-49bd-838c-2b28a0b20e7f.png">

**Steampipe version (`steampipe -v`)**
v0.13.0-alpha.5

**To reproduce**
Pull down branch in https://github.com/turbot/steampipe-mod-aws-insights/tree/release/v0.1 and run steampipe report (need an EBS volume in the AWS account)

**Expected behavior**
Hovering would make the full title visible, or another way would be available to view all of the info

**Additional context**

**Comment by MichaelBurgess** [comment]
@cbruno10 for now I have added html titles to the label and value. Longer-term I think we could consider a richer tooltip for this.
