### ISSUE TITLE
Improve positioning of chart axis titles

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/steampipe#1451]
They appear at the end of the axis, rather than underneath / to the side.

**Comment by judell** [comment]
@MichaelBurgess I think you already know this but fwiw, in this example both axis titles overlap the tick values.

```
      axes {
        x { 
          title {
            value = "word count buckets" 
            align = "center"
          } 
        }
        y {
          title {
            value = "notes in bucket"
            align = "center"
          } 
        }
      }
```

![image](https://user-images.githubusercontent.com/46509/155049486-3cf5b7a0-167d-4863-9dff-52a3adb6d077.png)
