### ISSUE TITLE
Package steampipe for conda-forge

### ISSUE THREAD

**Issue by manics** [turbot/steampipe#1458]
**Is your feature request related to a problem? Please describe.**

I'd like to create a [Conda-forge](https://conda-forge.org/) package for Steampipe. I'll do all the work which should be on the Conda packaging side, no changes should be required in the Steampipe repo. This is a courtesy message to check whether you have any objections?

Optionally you can be added as maintainers if you wish, but there's no obligation on you to do so.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by e-gineer** [comment]
Thank you - we really appreciate your support for Steampipe! Sounds like a great service for the community. Appreciate the heads up and please let us know if there is anything we can do to help!

**Comment by manics** [comment]
Now available: https://anaconda.org/conda-forge/steampipe
Package repo: https://github.com/conda-forge/steampipe-feedstock/

Thanks for creating and opensourcing steampipe!
