### ISSUE TITLE
autocomplete does not show suggestions when entering a new multiline query

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#150]
![image](https://user-images.githubusercontent.com/2838960/107363648-5532c880-6ad2-11eb-8012-85e80970e376.png)
![image](https://user-images.githubusercontent.com/2838960/107363479-1e5cb280-6ad2-11eb-82c4-68b29c15ba3c.png)

**Comment by pskrbasu** [comment]
Tracked in https://github.com/turbot/steampipe/issues/3855
