### ISSUE TITLE
Cosmetic Issue: The description column is too wide.

### ISSUE THREAD

**Issue by dboeke** [turbot/steampipe#155]
When doing a `.inspect` against a table, the `Description` field expands to the full width of the open terminal. This works well if the text in the `Description` column is large, but for tables where all the descriptions are short, the result looks a bit strange. 

<img width="2361" alt="image" src="https://user-images.githubusercontent.com/54130/107374036-278b5680-6ab5-11eb-9f80-be7117eb1270.png">

Suggest that the width of the `DESCRIPTION` column is the `lesser` of [longest description column text, available terminal width]

**Comment by kaidaguerre** [comment]
yup sounds sensible
