### ISSUE TITLE
Dashboard command should try to re-use existing browser tab where possible.

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/steampipe#1552]
As per https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/openBrowser.js

We don’t need as much functionality e.g. we don't need the ability to run a script, but just need a CLI option to not open the browser (if we don't already have that)…and if we do open the browser (the default behaviour), try to re-use an existing tab for it rather than create a new one.

Hopefully that code will port to Golang / give us good inspiration.

**Comment by binaek** [comment]
Closed with https://github.com/turbot/steampipe/pull/1627
