### ISSUE TITLE
Providing custom color option for stack chart

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe#1594]
**Is your feature request related to a problem? Please describe.**
We have a query to show the storage usage (Storage by Compartment) based on compartments catering multi-tenancy in a stack, however, this does not allow us to change the color (e.g. to tan) to map the same row.  Can we have any choice to select colors? 

![image](https://user-images.githubusercontent.com/26873346/157207919-96d0225c-8dfa-44c4-825b-556632b1109f.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by binaek** [comment]
@rajlearner17 is this still pending? If not, can you please close the issue?

**Comment by rajlearner17** [comment]
We are good. Thanks
