### ISSUE TITLE
Doubt - Delete Resources with Steampipe

### ISSUE THREAD

**Issue by filipponova** [turbot/steampipe#1609]
Can I delete resources using steampipe?

I searched but didn't find any information.

When trying to delete snapshots in aws I get a permission error :/

```sql
DELETE
FROM xpto_staging.aws_ebs_snapshot
WHERE
  tags->> 'Name' = 'old_snapshot';


[42501] ERROR: permission denied for foreign table aws_ebs_snapshot
```

**Comment by e-gineer** [comment]
Steampipe is currently focused on read operations only for reporting etc - we feel that's the most valuable area.

Postgres FDWs are capable of read / write / update operations, so it's something that we could extend to in the future - but it's complicated and not currently our focus or priority.
