### ISSUE TITLE
double dashboards for installed mod

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#1654]
To reproduce:

```
mkdir my-aws-insights
cd my-aws-insights
steampipe dashboard
```

![image](https://user-images.githubusercontent.com/46509/158279347-b97bdd5f-0a73-4ad0-aaab-77d945199c72.png)

**Comment by MichaelBurgess** [comment]
This seems to be an issue if you have an existing local mod and install a mod into it - which ends up with the dashboards appearing under both `mod.local` and `mod.<imported_mod_name>`.
