### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by take-five** [turbot/steampipe#1729]
Hello,

I want to deploy Steampipe to Kubernetes using `turbot/steampipe` Docker image (perhaps derive from it later to add some plugins for faster startup). I would then set up a data source in [Redash](https://redash.io/) deployed in the same cluster so that our team would be able to query our AWS infrastructure and share queries and dashboards.

Is it allowed by AGPL license? Will I have to share any of our code if I deploy it "as is"? I am not intending to modify Steampipe code in any way.

Thanks!

**Comment by m8e** [comment]
https://fossa.com/blog/oss-license-compliance-expert-heather-meeker-agpl/
