### ISSUE TITLE
Dashboard inputs should support defaults

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/steampipe#1744]
Sometimes it's desirable to provide a default value for a dashboard input so that the dashboard executes immediately.

We need to consider the case where a default is provided for a select input and that value is not in the static or dynamic options that the input has. In this case we should allow the item(s) and artificially add to the list, but show them as erroneous through some icons / appropriate colouring.

**Comment by judell** [comment]
For me the most-wanted version of this is a default for `type="text"`. Ideally the default could be the empty string. That's because it's common to bind a search term to a Postgres regexp match, and matching the empty string is a convenient way to say "match all".
