### ISSUE TITLE
Multiple Account Group Query Support

### ISSUE THREAD

**Issue by mthbrown** [turbot/steampipe#1746]
**Is your feature request related to a problem? Please describe.**
When using the [Multi-Region / Multi-Account](https://steampipe.io/blog/release-0-2-0) feature, you have to basically specify each account individually when querying. As mentioned in the above link, you basically have to:

```sql
  select account_id, count(*) as buckets
  from dmi_scranton.aws_s3_bucket
  group by account_id
  
  union
  
  select account_id, count(*) as buckets
  from dmi_albany.aws_s3_bucket
  group by account_id
```

While this is doable if you have a handful of accounts, this can be cumbersome if you are dealing with AWS Organizations and have dozens of accounts you want to query in one shot

**Describe the solution you'd like**
It would be great if you could either a group of connections and have them handled in one shot when querying. For example:

```sql
  select account_id, count(*) as buckets
  from dmi_group.aws_s3_bucket
  group by account_id
```

**Describe alternatives you've considered**

**Additional context**

**Comment by binaek** [comment]
@mthbrown What you are looking for may be solved by `aggregator connections` in `steampipe`

Reference: https://steampipe.io/docs/managing/connections#using-aggregators

You will have to add one more connection which aggregates your other connections:
```
connection "dmi_scranton" {
  plugin      = "aws" 
  ...
}

connection "dmi_albany" {
  plugin      = "aws" 
  ...
}

connection "dmi_group" {
  plugin      = "aws" 
  type        = "aggregator"
  connections = ["dmi_scranton", "dmi_albany"]
}

```

Then you should be able to run:
```
  select account_id, count(*) as buckets
  from dmi_group.aws_s3_bucket
  group by account_id
```
