### ISSUE TITLE
Ability to exclude non applicable checks from a report

### ISSUE THREAD

**Issue by pdecat** [turbot/steampipe#1759]
**Is your feature request related to a problem? Please describe.**

When generating a compliance report with `steampipe check all`,
the report can contain many empty sections about resources that are not used at all in the current context.

**Describe the solution you'd like**

I'd like to be able to pass a command-line parameter to `steampipe check` to omit empty sections from the generated report. Maybe `--omit-empty-sections` or `--omit-empty-checks`.

**Describe alternatives you've considered**

Identify which resources are used in the context, and use `steampipe check check1 check2 ...` instead of `steampipe check all` but that can be tedious and error-prone.

**Additional context**

Example of a report generated against the terraform  https://github.com/terraform-aws-modules/terraform-aws-lambda/ community module using the https://hub.steampipe.io/mods/turbot/terraform_aws_compliance mod: 
[all-20220330-145142.pdf](https://github.com/turbot/steampipe/files/8380752/all-20220330-145142.pdf)

**Comment by binaek** [comment]
This can be achieved with custom check output templates.

https://steampipe.io/docs/develop/writing-control-output-templates
