### ISSUE TITLE
dashboard: show how to update plugin when required

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#1794]
When this happens:

![image](https://user-images.githubusercontent.com/46509/161646290-ddc6f791-02e5-423f-99dc-e2d3687fd4b2.png)

we could also say something like:

Please run: steampipe plugin update aws

**Comment by pskrbasu** [comment]
This message has changed.

Now:
`[ Message ] could not find plugin which satisfies requirement 'net@0.12.0' - required by 'net_insights'`

**Comment by pskrbasu** [comment]
New updated issue: https://github.com/turbot/steampipe/issues/3846
