### ISSUE TITLE
Update .mod.cache.json - rename ShortName to Alias and remove the 'steampipe-mod-' prefix

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#1810]
* The value should be the name of the hcl `mod` resource in the `mod.sp` (or the alias listed in the mod require `section` when that functionality is implemented)
* The name of the field should be `Alias` instead of `ShortName`

```
$ cat .mod.cache.json 
{
  "local": {
    "github.com/turbot/steampipe-mod-aws-insights": {
      "Name": "github.com/turbot/steampipe-mod-aws-insights",
      "ShortName": "steampipe-mod-aws-insights",
      "Version": "0.3.0",
      "Constraint": "*"
    }
  }
```

It should be:
```
{
  "local": {
    "github.com/turbot/steampipe-mod-aws-insights": {
      "Name": "github.com/turbot/steampipe-mod-aws-insights",
      "Alias": "aws_insights",
      "Version": "0.3.0",
      "Constraint": "*"
    }
  }
```

**Comment by vhadianto** [comment]
This should also be in `snake_case`:

{
  "local": {
    "github.com/turbot/steampipe-mod-aws-insights": {
      "name": "github.com/turbot/steampipe-mod-aws-insights",
      "alias": "aws_insights",
      "version": "0.3.0",
      "constraint": "*"
    }
  }
