### ISSUE TITLE
dashboard: html export of tables

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#1824]
It'd be nice to be able to get a clean HTML export of dashboard tables, for use in other contexts.

Current method:

- Try File -> Save As HTML, yields empty page

- Inspect DOM, copy Outer HTML

- Run that through https://htmltidy.net/

**Comment by tnelson-doghouse** [comment]
Might be nice if we changed the current "Download" button to "Download CSV", and added this as "Download HTML" next to it.

**Comment by tnelson-doghouse** [comment]
Have a fresh cookie.

**Comment by tnelson-doghouse** [comment]
Should be reopened.

**Comment by tnelson-doghouse** [comment]
Thanks!  Hopefully this comment will also remove the "stale" tag.
