### ISSUE TITLE
options "terminal" { search_path_prefix = "aws_all" } in default.spc should work everywhere

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#1825]
I have 4 AWS accounts grouped into my `aws_all`. 

This query finds all of them using either `steampipe query` or in a dashboard table:

```
select * from aws_account
```

But it does not apply to `steampipe check` -- there,  I always have to do `steampipe check --search-path-prefix aws_all`. Since the outputs don't report which accounts are checked (maybe they should?) it's easy to assume that `aws_all` is in effect and not realize you're getting partial results.

**Comment by judell** [comment]
[John Smyth]
> IMO the 'terminal' options only apply to the terminal, and should only apply to the termnial


> if you want them to work everywhere, you should set them in the database options

> I believe the fix should be to add search_path_prefix to database  options instead (it only supports `search_path` i think)

**Comment by johnsmyth** [comment]
`terminal` options only apply to the terminal, and **should** only apply to the terminal. If you want to set the search path for EVERYTHING, you can set `search_path` in the database options. I believe we should also add `search_path_prefix` to database  options though to be more flexible.
