### ISSUE TITLE
Allow dashboard columns to set content/text alignment

### ISSUE THREAD

**Issue by tnelson-doghouse** [turbot/steampipe#1876]
**Is your feature request related to a problem? Please describe.**
The problem is that I have strings like '$USD           5.50' which I would like to right-align

**Describe the solution you'd like**
I would like dashboard columns to allow the setting of the content/text alignment.  

**Describe alternatives you've considered**
- Converting the string to a numeric and a currency column.  That seems annoying
- Upgrading the automatic detector to allow for this.  While a good idea, it seems like allowing the setting of alignment would also solve future problems like these.  There's no reason both can't be done.  My use-case currently requires me to support USD and AUD.

**Comment by tnelson-doghouse** [comment]
Someone liked this -- I'm not the only one.

**Comment by MichaelBurgess** [comment]
We agree this would be a good feature to add, however we're not able to look at this currently due to other priorities, so will close this issue for now.

**Comment by tnelson-doghouse** [comment]
Thanks for the update; would it be useful to have something that tracks possible future features and lets the community vote on them like Atlassian has for its products?
