### ISSUE TITLE
Extra output string in help message when command fails due to no plugin installed

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#1909]
**Describe the bug**
When I attempted to list my plugins after uninstalling a plugin I still had a config file for, I received the message:
```
cbruno@M1P ~ % steampipe plugin list
Error: Plugin Listing failed - failed to load connection 'aws': no plugin installed matching aws
{/Users/cbruno/.steampipe/config/aws.spc {2 1 20} {2 11 30}}
```

What does the `{2 1 20} {2 11 30}` string at the end of the filename? Is it useful for debugging at all?

**Steampipe version (`steampipe -v`)**
v0.14.0-alpha.11

**To reproduce**
Run `steampipe plugin list` or `steampipe query` when there is a config file without a matching plugin

**Expected behavior**
The help message should contain useful and readable information to the end user

**Additional context**

**Comment by pskrbasu** [comment]
This issue does not exist anymore. If an uninstalled plugin has leftover connections they are listed in the `Failed` list.
```

+---------------------------------------------------+-------------+---------------+
| Failed                                            | Connections | Reason        |
+---------------------------------------------------+-------------+---------------+
| hub.steampipe.io/plugins/turbot/oci@latest        | oci         | Not installed |
| hub.steampipe.io/plugins/turbot/hackernews@latest | hackernews  | Not installed |
+---------------------------------------------------+-------------+---------------+
```
