### ISSUE TITLE
Attempting to update a specific mod results in all mods being updated

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#1971]
**Describe the bug**
If I run `steampipe mod update github.com/turbot/steampipe-mod-aws-thrifty`, it appears to update all of my mods:
```
cbruno@M1P installed % steampipe mod update github.com/turbot/steampipe-mod-aws-thrifty

Upgraded 3 mods:

local
├── github.com/turbot/steampipe-mod-aws-compliance@v0.29
├── github.com/turbot/steampipe-mod-aws-tags@v0.4
└── github.com/turbot/steampipe-mod-aws-thrifty@v0.13
```

**Steampipe version (`steampipe -v`)**
v0.14.0-alpha.15

**To reproduce**
Install multiple mods, all of them on a version before latest, and then attempt to update a specific one.

**Expected behavior**
Only the provided mod should be updated.

**Additional context**

**Comment by binaek** [comment]
Fixed in `main`

![Screenshot 2023-09-14 at 10 09 28 PM](https://github.com/turbot/steampipe/assets/1114038/71b22a5f-2e89-47bf-bc42-2233c0c9882d)
