### ISSUE TITLE
Pasting a query during CLI initialization causes it to be duplicated on the screen

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#1980]
**Describe the bug**

1. Start the CLI
2. Immediately paste a SQL query into the console
3. The query will be duplicated once initialization is finished

**Steampipe version (`steampipe -v`)**
Example: v0.14.x-alpha

**Comment by binaek** [comment]
Closed by [d15ac33](https://github.com/turbot/steampipe/commit/d15ac33b2648b40bf7ba9b989033a44e1b0abc3a)
