### ISSUE TITLE
dashboard does not render in Safari

### ISSUE THREAD

**Issue by mheiges** [turbot/steampipe#1984]
**Describe the bug**

Dashboards do not render in macOS Safari

**Steampipe version (`steampipe -v`)**

v0.13.6

**To reproduce**

Following the dashboard tutorial, https://steampipe.io/docs/mods/writing-dashboards , load in macOS Safari Version 15.4 (16613.1.17.1.13, 16613)

**Expected behavior**

expect to see a rendered dashboard but get a blank page.

The js console in the dev tools reports,
```
SyntaxError: Invalid regular expression: invalid group specifier name
(anonymous function) - main.a0ad54a7.js:2
```

**Additional context**

The dashboard loads fine in Firefox and Chrome.

**Comment by e-gineer** [comment]
I've reproduced. So many standards, and yet still edges in the browser level that we should have tested for ... thanks so much for letting us know @mheiges!

**Comment by MichaelBurgess** [comment]
@mheiges apologies for this one - we've got it sorted now and will look to release this soon. Will ping you on here when we do. Thanks for reporting!

**Comment by MichaelBurgess** [comment]
@mheiges sorry for the delay in the update. The latest version (0.14.x) contains this fix whenever you'd like to update.
