### ISSUE TITLE
Plugin log file entries may end up in prior day log?

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#2016]
I left steampipe running overnight, and then ran a query. I was surprised there was no plugin log file for the new day, instead the log entries seemed to be added to the prior day's log file.

In addition, I can see log entries from the night before also seem to have a different date to the log file date.

I assume two things, but am not sure:
* The log filename date is the local time, but log entries are in UTC
* The log file destination is set at startup and not changed if steampipe is long running

I'm not sure these are bugs exactly - but they are noteworthy and should perhaps be fixed.

Here is a screenshot taken at 7:20am in US Eastern timezone on 7-May:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/1328145/167252077-7550d12e-c7a2-4c33-a1e6-875c966b3dd8.png">

**Comment by kaidaguerre** [comment]
covered by #3825
