### ISSUE TITLE
Disable Password Logging on service start

### ISSUE THREAD

**Issue by kaiba42** [turbot/steampipe#2033]
**Is your feature request related to a problem? Please describe.**

When running `steampipe` in service mode, the password for connecting is printed to stdout. This can lead to a security issue, especially when using log collectors like fluentd or datadog.

**Describe the solution you'd like**

I'd like to pass in a flag or set an environment variable to disable printing the password. For example, something like `steampipe service start --hide-password`.

I would even consider hiding the password to be the default, and explicitly enable password logging, e.g. `steampipe service start --show-password`.

**Describe alternatives you've considered**

I have considered piping the output to a file with tight access permissions. 

**Additional context**

**Comment by e-gineer** [comment]
Hi @kaiba42 - thanks for the detailed suggestion! Makes sense to have the opportunity to hide the password for repeated use.

I think a good approach would be to hide the password when it has been set by the user through https://steampipe.io/docs/reference/env-vars/steampipe_database_password

The password is printed at service start by this code https://github.com/turbot/steampipe/blob/c3b78c72b9750512dc87d00b834eed39b46ea397/cmd/service.go#L615

And is the code we use to check the password config setting https://github.com/turbot/steampipe/blob/c3b78c72b9750512dc87d00b834eed39b46ea397/db/db_local/start_services.go#L275

**Comment by kaiba42** [comment]
Gotcha -- so you're suggesting to hide the password automatically if it is explicitly set by the user?
Perhaps something like this then:

At [this line](https://github.com/turbot/steampipe/blob/c3b78c72b9750512dc87d00b834eed39b46ea397/cmd/service.go#L626) 
```go
password := dbState.Password
// if a password was set through the `STEAMPIPE_DATABASE_PASSWORD` environment variable
// or through the `--database-password` cmdline flag, then redact it from the printed status
if viper.IsSet(constants.ArgServicePassword) {
    password = "***"
}
postgresMsg := fmt.Sprintf(
		postgresFmt,
		strings.Join(dbState.Listen, ", "),
		dbState.Port,
		dbState.Database,
		dbState.User,
		dbState.Password,
		dbState.User,
		password,
		dbState.Listen[0],
		dbState.Port,
		dbState.Database,
	)
```

**Comment by kaiba42** [comment]
happy to open a little PR for this if you guys agree with that approach. It'll change existing behavior as opposed to being additive but I think it's a good change. Lmk!

**Comment by e-gineer** [comment]
Thanks @kaiba42!

@kaidaguerre @johnsmyth What do you think?

Hiding the password when set explicitly seemed to make sense, but perhaps there is a case I'm missing (e.g. Docker) that means we should have a separate option / capability to hide the password on service start?

**Comment by johnsmyth** [comment]
Either solution would be ok if it only hides the password when showing the status on startup.  It seems non-obvious if you do `steampipe service status` later though - whether the password is displayed depends on how you started the service?  Maybe it would be better as a config file option / environment variable that is evaluated whenever the status is printed?

**Comment by e-gineer** [comment]
So, closer to the original proposal by @kaiba42 then ... with a `--hide-password` style option.

Best precedent seems to be on `steampipe query --watch`:
```
      --watch                        Watch SQL files in the current workspace (works only in interactive mode) (default true)
```

We generally avoid both negative options (confusing) and booleans (limit future expansion), but perhaps a negative option is actually best / simplest in this case?
```
# start shows password by default (convenient, current behavior)
steampipe service start
steampipe service status

# use option to hide password
steampipe service start --hide-password
steampipe service status --hide-password

# show password explicitly (silly & redundant, but possible)
steampipe service start --hide-password=false
steampipe service status --hide-password=false
```

**Comment by kaidaguerre** [comment]
I agree, `--hide-password` seems a simple and non-confusing way to solve this.

**Comment by yuha0** [comment]
The password is also included in the connection string

```
Steampipe service is running:

Database:

  Host(s):            localhost, 127.0.0.1, 172.17.0.2
  Port:               9193
  Database:           steampipe
  User:               steampipe
  Password:           password
  Connection string:  postgres://steampipe:password@localhost:9193/steampipe
```

Personally, I would prefer to have an option to just hide the whole database section.

**Comment by e-gineer** [comment]
I like the idea of moving beyond hide password, which fits better with avoiding negated options etc.

Perhaps:
```
--output developer   # the default as per current
--output brief       # simple status message with port only
```

We can expand options over time as required.

**Comment by johnsmyth** [comment]
We already have an `--output` flag for `steampipe check` and `steampipe query`, and I don't think its intuitive in this case.  I still prefer using an env var of a config file options instead of a command flag myself.

**Comment by kaiba42** [comment]
Nice thoughts and ideas from everyone! Thanks for chiming in. I propose the following design so we can all agree on a path forward.

#### Criteria
1. Support env var configuration of startup output
2. Hide the password from startup output (including the connection string)
3. Support CLI flag configuration of startup output, avoiding negated options (i.e. avoid `--hide-password`)

The design of this solution should enable more configurations of startup output in the future.

#### Design
Create an optional env var `STEAMPIPE_STARTUP_OUTPUT` that can be set to one of the following values:
1. `disabled`: hides startup output completely
2. **`developer`**: displays the existing startup output today, and would be the **default**
3. _...more to come!_ 

`STEAMPIPE_STARTUP_OUTPUT` can also be configured via the CLI flag `--startup-output`, which accepts the same set of values when set via env var.

More configuration options like those mentioned by @e-gineer could be added (e.g. `port-only`) in the future.

#### Usage
To hide password output, you have two options:
- `steampipe service start --startup-output=disabled`
- `STEAMPIPE_STARTUP_OUTPUT=disabled steampipe service start`

👍  **Give me some thumbs UP if you'd like to move forward with this design!**
👎  **Give me some thumbs DOWN if you'd like to change this design, and please COMMENT with the changes you'd like**

@e-gineer 
@johnsmyth 
@yuha0 
@kaidaguerre

**Comment by yuha0** [comment]
Hi @johnsmyth , the information is just not very useful to me.

Steampipe does not necessarily know the actual hostname a user can connect to. e.g. if I run the process in a container with bridged virtual interface, neither the interface's IP nor `localhost` will work from outside the container.

And the same argument for port -- I can bind a different host port to 9193 and steampipe container will have no idea.

For password: if I set a password explicitly, then I already know it and don't need steampipe process to tell me what it is.

I understand that the information is useful for users who want to quickly spin up a local process and run some adhoc queries. But I run steampipe in a controlled remote environment and set all the configuration options to make software behavior as deterministic as possible. I don't have some AWS credentials laying around on my laptop that can read everything in my AWS account.

**Comment by kaiba42** [comment]
> Im not a fan of `--startup-output` with named ouput types becuase they are not self explanatory - what does `developer` output mean? While it gives _us_ flexibilty, it doesnt help the user know when to use it. I would actually be ok changing the default to **not show** the password, and add `--show-password` argument to allow the user to show it. The pg_hba file has `hostssl steampipe steampipe samehost trust` so you dont need the password to connect from the same host anyway. The default output could inform the user to run `steampipe service status --show-password` if they wish to see the password, something like this:
> 
> ```
> 
> Steampipe service is running:
> 
> Database:
> 
>   Host(s):            localhost, 127.0.0.1, 192.168.1.183
>   Port:               9193
>   Database:           steampipe
>   User:               steampipe
>   Password:           ******** [redacted - use `steampipe service status --show-password` to reveal]
>   Connection string:  postgres://steampipe@localhost:9193/steampipe
> 
> Managing the Steampipe service:
> 
>   # Get status of the service
>   steampipe service status
>   
>   # Restart the service
>   steampipe service restart
>   
>   # Stop the service
>   steampipe service stop
> ```
> 
> Obviously whatever mechansim we choose to hide the password would remove it from the connection string as well. @yuha0 Im interested in why you would want to hide the whole database section (other than not showing the password)?

sounds like your preference would be closer to this [initial concept](https://github.com/turbot/steampipe/issues/2033#issuecomment-1124081815):

At [this line](https://github.com/turbot/steampipe/blob/c3b78c72b9750512dc87d00b834eed39b46ea397/cmd/service.go#L626)
```go
password = "*** [use `steampipe service status --show-password` to reveal]"
// if the `STEAMPIPE_SHOW_PASSWORD` environment variable is set to true
// or through the `--show-password` cmdline flag, then reveal it in the printed status
if viper.IsSet(constants.ArgShowPassword) {
    password := dbState.Password
}
postgresMsg := fmt.Sprintf(
		postgresFmt,
		strings.Join(dbState.Listen, ", "),
		dbState.Port,
		dbState.Database,
		dbState.User,
		password,
		dbState.User,
		password,
		dbState.Listen[0],
		dbState.Port,
		dbState.Database,
	)
```

I'm happy with this approach. It's likely easiest implementation.

**Comment by kaidaguerre** [comment]
@kaiba42 it seems we have consensus on this issue - are you happy to go ahead and raise a PR with the changes?

**Comment by kaiba42** [comment]
PR is up @kaidaguerre
Are tests needed?

**Comment by e-gineer** [comment]
Thanks @kaiba42  for your great work discussing and implementing this feature!
