### ISSUE TITLE
Move restorebackup out of RefreshConnectionAndSearchPaths and into a more obvious location

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#2037]
if a database backup was taken after a db upgrade, it is restored by `restoreBackup` which is called from `RefreshConnectionAndSearchPaths`

This is a slightly unexpected place to call it from - move somewhere more expected, like EnsureDbInstalled

**Comment by pskrbasu** [comment]
Not planned. Tracked in https://github.com/turbot/steampipe/issues/3764
