### ISSUE TITLE
Intermittent panic error on plugin install

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#2086]
We should never panic, even if something goes wrong during the install

Details in issue https://github.com/theapsgroup/steampipe-plugin-gitlab/issues/12 raised by @dbmorin

**Comment by graza-io** [comment]
https://github.com/turbot/steampipe/blob/v0.14.4/cmd/plugin.go#L270 (if `b.Current()` returns zero, this is when you get the panic)
