### ISSUE TITLE
Steampipe - Github Audit Logs

### ISSUE THREAD

**Issue by ngowraj** [turbot/steampipe#2087]
We should be able to create a table for [Github Audit logs](https://github.com/organizations/loomhq/settings/audit-log) with Steampipe. 

I use this query in our internal tooling to find policy overrides like ["Branch Protection Overrides"](https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/reviewing-the-audit-log-for-your-organization#protected_branch-category-actions) to trigger a notification. Would be nice to have this data within Steampipe for us to start using it.

```
curl \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token ghp_...(redacted)" \
  --request GET \
  "https://api.github.com/orgs/loomhq/audit-log?phrase=created:2022-05-10&page=1&per_page=100"
```

**Comment by cbruno10** [comment]
Hi @ngowraj , I had transferred your original issue over to the GitHub plugin repo at https://github.com/turbot/steampipe-plugin-github/issues/164. Sorry if it wasn't clear that I did so, I'm not sure what notifications GitHub provides.

I'll close this issue so we can move discussion over to the linked issue.
