### ISSUE TITLE
`pluralize` sql function

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#2097]
Is it possible to have a `pluralize` function available in SQL statements for steampipe?

Use case:
I have a `jsonb_array` which contains `0-n` elements.
A `reason` is getting generated like `... jsonb_array_length(arr) || ' endpoint(s) '...`
It will be great if we could do something like `... jsonb_array_length(arr) || pluralize('endpoint',jsonb_array_length(arr))...`

**Comment by judell** [comment]
It's easy to write such a function. One way to do it:

```
create or replace function pluralize(label text, arr jsonb) returns text as $$
  select
    label || 
      case 
        when jsonb_array_length(arr) = 0 then 's'
        when jsonb_array_length(arr) = 1 then ''
        else 's'
      end;
$$ language sql;
```

And there are about a million ways in which providing a library of such functions would be helpful. The list of non-core functions available to Steampipe users has grown as we've added the `tablefunc` and then `ltree` extensions, but we've yet to add any of our own. Would we consider doing so?

**Comment by judell** [comment]
Hey @binaek, I was just reviewing stale issues and found this one. Has there been any discussion about putting some utility functions into the public schema?

**Comment by binaek** [comment]
Not planned
