### ISSUE TITLE
plugin requirements for dependent mods are not respected

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#2107]
To reproduce
```
mkdir test_mod
cd test_mod
steampipe mod install github.com/turbot/steampipe-mod-aws-compliance
steampipe plugin uninstall aws
steampipe query
```
this _should_ fail with the error 
```
Error: 1 mod plugin requirement not satisfied. 

  turbot/aws  none  →  0.59.0
```

but does not

**Comment by binaek** [comment]
fixed by https://github.com/turbot/steampipe/pull/3334

**Comment by binaek** [comment]
As pre new design, `steampipe` raises a warning if there are unmet plugin dependencies in the dependency tree

![Screenshot 2023-09-14 at 10 23 05 PM](https://github.com/turbot/steampipe/assets/1114038/3bedad66-3afd-4ca5-a075-48e936178659)
