### ISSUE TITLE
Bad value in config (aws.spc) file caused steampipe query & dashboard to load with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe#2111]
**Is your feature request related to a problem? Please describe.**

Just added the new feature to ignore errors in `aws.spc` file i.e. I had **`ignored_error_codes`**  instead of right value **`ignore_error_codes`**. It failed to load the steampipe query & dashboard with the following error

```
 $ steampipe query
Welcome to Steampipe v0.14.5
For more information, type .help
> 
Error: runtime error: invalid memory address or nil pointer dereference
```

```
➜ steampipe dashboard
[ Wait    ] Loading Workspace
Error: runtime error: invalid memory address or nil pointer dereference

```
**Describe the solution you'd like**

**Describe alternatives you've considered**

run `STEAMPIPE_LOG=trace steampipe query`, this will provide an indication of the error e.g.
```
Unsupported argument: An argument named "ignored_error_codes" is not expected here. Did you mean "ignore_error_codes"?
(/:1,1-20)
```

**Additional context**

**Comment by pskrbasu** [comment]
Tried in v0.21.0-beta.0
Having an unsupported config argument does not cause `invalid memory address or nil pointer dereference` anymore, instead, the connection goes into error.
TRACE logs reveal the error:
```
Unsupported argument: An argument named "ignored_error_codes" is not expected here. Did you mean "ignore_error_codes"?
```

![Screenshot 2023-09-15 at 6 09 20 PM](https://github.com/turbot/steampipe/assets/45908484/00f6920c-ef7a-4760-868e-bd1f5c6f7595)
