### ISSUE TITLE
Configuring database... FAILED during installation

### ISSUE THREAD

**Issue by vbolneni** [turbot/steampipe#2215]
it is hanging at configuring database and nothing happening. it was sitting there for entire night and i have to cancel it. I tried delete whole ~/.steampipe directory and install again and same thing happening. I am on windows 2019 server WSL and ubuntu.
![trace-file](https://user-images.githubusercontent.com/97460246/176540776-2cc49dfa-e48b-4abb-9e10-197e8301e36d.png)

**Comment by judell** [comment]
Hey @vbolneni, sorry it wasn't smooth. First question: Is WSL2 available for that version of Windows Server? Based on [this](https://www.bleepingcomputer.com/news/microsoft/microsoft-adds-support-for-wsl2-distros-on-windows-server-2022/) I'm guessing likely not, but let's establish that first.

**Comment by vbolneni** [comment]
No WSL2 not available. I am using Amazon windows 2019 instance.

**Comment by e-gineer** [comment]
At a minimum we should offer a better error message and / or warning that WSL 1 is not supported. Awful experience for users like @vbolneni when we just timeout / fail.

Looking at [this ask ubuntu thread](https://askubuntu.com/a/1377913), I wonder if we can use `uname -r` to detect WSL and hopefully the WSL version during startup?

Then we could provide a message like `Steampipe requires WSL 2, please upgrade and try again.`

**Comment by e-gineer** [comment]
Actually, perhaps we should put this check into the `install.sh`?

https://github.com/turbot/steampipe/blob/657cbaab4f064cc3f487febd79d2750a4f070fe1/install.sh#L35-L46
