### ISSUE TITLE
Retain historical data in the dashboard

### ISSUE THREAD

**Issue by massyn** [turbot/steampipe#2253]
**Is your feature request related to a problem? Please describe.**
Steampipe dashboards are great for real-time visibility.  But what happened a week ago, or last month?  It would be great if there was a way for Steampipe to record the data extractions, and keep them (perhaps in a local file?) that would allow me to see what changed in the query from a month ago until now.

**Describe the solution you'd like**
Allow steampipe to create a local state file, that records the results from a query with a timestamp of when it was executed.
Create a feature in the dashboard go allow me to view older dashboards.
Add an additional graph to allow trending (ie number of alerts and how they changed over time)

**Describe alternatives you've considered**

**Additional context**

**Comment by massyn** [comment]
Hi Nathan,

Thanks for the feedback.  Let me give you my take..

**Which specific dashboards would you be most interested in snapshotting? (e.g. AWS CIS v1.4.0, AWS Insights, a custom one)?**

> I don't see it as a _dashboard_ issue, but rather a _functionality_ enhancement, meaning this is something the `steampipe dashboard` command should handle, not the dashboard.sp files themselves.

**When comparing past results, do you imagine that of summary data only (e.g. cards) or of full table data?**

> More data means slower performance, and bigger management issues of that data.  I would be quite happy with just the summarised data.  Capturing the full table data for historical purposes do not add much value as the data is aging.

**Would you be looking to share dashboards with other users, or is it just for personal review?**

> The dashboard definition itself might potentially be shared, but I don't see the historical tracking being shared.  That being said, when I do an export (ie `steampipe check all --output myfile.html`) I would expect the HTML report to also include the trend data.

**How do you imagine capturing the snapshot?**

> Keeping things simple, I would opt for a `json` file that can be passed as a parameter where the historical data is stored.

**Any other tools / best practice examples that are good inspiration for this feature?**

> Unfortunately none that I can share here.  I do have some examples from internal systems we've developed that does something similar.  In my example, the tool would record a snapshot at least once per month, so even if you ran the script every day, it would only ever record a snapshot for that one month.  For trending analysis, a monthly snapshot was good enough, though I would image some users may want to opt for weekly, or even daily recording.

**Comment by e-gineer** [comment]
Our current design is that dashboards can be captured as snapshots and include the data only from that moment. To build a trend, we expect users will start to query collections of snapshots (from the cloud, or using file-level plugins like config).

At a high level, the CLI is focused on a single developer doing one thing at one time ... while we are building cloud to focus on many users doing many things over time. So, our priority right now would be to add features like trending etc at the cloud level rather than in the CLI specifically.

Closing the ticket for now.
