### ISSUE TITLE
Add auto-refresh to dashboards

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#2258]
**Is your feature request related to a problem? Please describe.**
For dashboards with data that changes over time, I have to restart the Steampipe service to get new data.

**Describe the solution you'd like**
Auto-refresh capabilities on a schedule.

**Describe alternatives you've considered**
Restarting the service manually.

**Additional context**

**Comment by e-gineer** [comment]
Should this be a setting in the HCL code (an attribute set by the dashboard designer) or an option in the UI (an attribute set by the dashboard viewer)?

**Comment by MichaelBurgess** [comment]
Both would be nice - set something up to auto-refresh if that's your use case, or opt-in/out in the UI for ad-hoc control of it.
