### ISSUE TITLE
Error: runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)

### ISSUE THREAD

**Issue by createchange** [turbot/steampipe#2259]
**Describe the bug**
```
select az.user_principal_name as upn, slack.email as email, az.account_enabled as az_enabled, slack.deleted as slack_deleted from slack_user slack, azuread_user az where slack.email = az.user_principal_name;
Error: runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
~ ➜  steampipe -v
steampipe version 0.15.3

**To reproduce**
Run the above command

**Expected behavior**
Command successfully completes.

**Comment by e-gineer** [comment]
Thanks for reporting this issue @createchange, sorry you've run into it - crashes are particularly nasty / unexpected, so keen to get it resolved.

Questions to help us troubleshoot:
* Can you query the `slack_user` table on it's own?
* Can you query the `azuread_user` table on it's own?

Also, can you please try again and share the log you get after running with:
```
STEAMPIPE_LOG=trace steampipe query
```

You should get output on the screen, and you can also check `~/.steampipe/logs`.

**Comment by e-gineer** [comment]
Very helpful - seems like the issue is from the `azuread` plugin.

For the simpler `azuread` query that fails is there anything in the `~/.steampipe/logs/plugin-XYZ.log` when you do `STEAMPIPE_LOG=trace`?

**Comment by e-gineer** [comment]
Oh - sorry - I see now that the partial results come from the join.

Anything in the plugin log for that?

**Comment by createchange** [comment]
Here is a clean log, with the only minimal redactions where needed.

[plugin-2022-07-19.log](https://github.com/turbot/steampipe/files/9145091/plugin-2022-07-19.log)

**Comment by kaidaguerre** [comment]
thanks @createchange, that plugin log has some clues: ```2022-07-19 22:28:11.462 UTC [WARN]  steampipe-plugin-azuread.plugin: [WARN]  1658269691156: Execute recover from panic: callId: 1658269691156 table: azuread_user error: runtime error: invalid memory address or nil pointer dereference
```

Let me see if I can reproduce it

**Comment by kaidaguerre** [comment]
cannot reproduce in current version
