### ISSUE TITLE
Dynamic plugin configuration per query

### ISSUE THREAD

**Issue by astro44** [turbot/steampipe#226]
Looks like all connection configurations are based on files from the file system. This becomes a hurdle for more security hardened environments, where file system changes are limited to /opt or /tmp.
Looking to see if it's possible to pass in an array of configurations reflecting plugins installed. (*even in future builds)
so you might have something like:
Steampipe query "Select..." -configs 'aws:[acct:[key,secrt,[rgn1,rgn2]],acct2:[key2,secrt2,\*]],azure:[acctA:[...]]' -output csv
this would allow each request to have dynamic configurations for all plugins and not worry about updating the file system.
thanks

**Comment by e-gineer** [comment]
One workaround that may help:
* Install steampipe, this creates the `~/.steampipe` dir
* Install the plugins, which creates various `~/.steampipe/config/*.spc` files (e.g. `aws.spc`)
* Leave those config files as default (no profile / region options etc)

Now, when running steampipe pass in environment variables for your AWS_* / AZURE_* / etc configuration. Unfortunately this will mean you are limited to one connection per service (e.g. one AWS account), but it will allow you to work with a different account each time (per the env vars passed).

But ... it would make sense to allow the config directory to be passed as an option to steampipe. Then the config data could be stored in another location. Question for you:
* Should the whole ~/.steampipe directory be moved? We store other writable files in there (e.g. logs).
* Or is it just the config files you need separated / passed?

Another question, is this for a container setup (e.g. read only file system)?

**Comment by astro44** [comment]
if the entire directory could be moved to /<newdir> that would make things a lot easier... this would have to include the postgres install also.
Having said that isolating the query to each configuration would be ideal to get closer to simulate "multi-tenant" requests.... or if it can be done with config files. i.e. set a different path for each query  like:
/tmp/query_config001/config.json.  vs. /tmp/query_config002/config.json.
then in the "steampipe query "select....." -config /tmp/query_config002/config.json -output csv

**Comment by astro44** [comment]
@e-gineer hope all is well was wondering if there was any additional suggestions you may have in the meantime?

**Comment by e-gineer** [comment]
@astro44 Unfortunately we don't currently support a way to configure the location of the `~/.steampipe` directory. That directory contains the config files, but also log output and other database files. So, I think for now the only option is to get that dir out to a writable filesystem.

I've spoken with @kaidaguerre about this issue, and per your suggestion, we're considering an option to set the config directory location - for example with something like `steampipe --config-dir /path/to/my/.steampipe ...`.

For the multi-tenant requests, with the addition of [connection management in v0.2.x](https://steampipe.io/docs/using-steampipe/managing-connections) you should be able to easily mix and match queries across accounts using the schema - e.g. `select * from config001.aws_s3_bucket` and `select * from config002.aws_s3_bucket`. Is that what you have in mind, or something else?

**Comment by astro44** [comment]
@e-gineer   thanks!!! 
"we're considering an option to set the config" - this would be awesome... any idea when it may be possible?
"easily mix and match queries across accounts " - I think this could work.. once the above is set. I think having the above configuration flexibility will go a very long way!!!

**Comment by kaidaguerre** [comment]
```
"we're considering an option to set the config" - this would be awesome... any idea when it may be possible?
```
@astro44 our aim is to get something out in our patch release this week (Thursday), but we've hit a small complication so I don't want to commit to it and then disappoint you :) If we miss this week, it will be next week. 

I'll keep you updated.

**Comment by kaidaguerre** [comment]
@astro44 a quick update: we have a fix planned for this, tracked by https://github.com/turbot/steampipe/issues/241

It is a slightly large change for a patch release so it will be going out in the next minor release. These fall on the third Thursday of the month - 18th March in this case.

**Comment by kaidaguerre** [comment]
@astro44 just to let you know, the `--install-dir` flag was added to steampipe 0.3.0, released yesterday
