### ISSUE TITLE
.multi doesn't work when typing query from scratch

### ISSUE THREAD

**Issue by createchange** [turbot/steampipe#2260]
**Describe the bug**
`.multi on` doesn't have desired effect.

I am unable to write a query from scratch using `.multi`

```
~ ➜  steampipe query
Welcome to Steampipe v0.15.3
> .multi on
> select
> *
> from
> slack_user;
Error: syntax error at or near "slack_user" (SQLSTATE 42601)
>
```

It does work when pasting though:
```
> select
  domain,
  expiration_date
from
  whois_domain
where
  domain in ('apple.com','steampipe.io');
+--------------+---------------------------+
| domain       | expiration_date           |
+--------------+---------------------------+
| apple.com    | 2023-02-20T00:00:00-05:00 |
| steampipe.io | 2022-10-13T15:28:29-04:00 |
+--------------+---------------------------+
```

I tried typing the above:
```
> .multi on
> .multi
multi-line mode is on. You can disable it with: .multi off
>
> select
>   domain,
>   expiration_date
> from
>   whois_domain
> where
>   domain in ('apple.com');
Error: syntax error at or near "domain" (SQLSTATE 42601)
```

**Steampipe version (`steampipe -v`)**
~ ➜  steampipe -v
steampipe version 0.15.3

**To reproduce**
See above

**Expected behavior**
Multi line functions when typing a query from scratch.

**Additional context**
Mac Monterey 12.4
iTerm2 Build 3.4.16
zsh

**Comment by e-gineer** [comment]
oof - thanks for letting us know @createchange!

I've confirmed this is an issue with both `.multi on` in the interactive terminal and when setting `multi = true` in the `default.spc` config file.

Until we get a fix, here are a couple of workarounds that may be helpful:
* You can use a file for the query with `steampipe query my_queries/my_query.sql` [see examples](https://steampipe.io/docs/reference/cli/query#examples)
* [Use named queries in mods](https://steampipe.io/docs/query/batch-query#named-queries)

**Comment by createchange** [comment]
Thanks you for the workarounds!

**Comment by createchange** [comment]
Thank you for the workarounds!
