### ISSUE TITLE
Graph node not actionable even when configured

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#2303]
I am seeing a few graph nodes are not showing it's properties nor it's icon.

example: 
for the row:
from_id|to_id|id|title|category|properties
-- | -- | -- | -- | -- | --
null | null | arn:aws:s3:us-xxxx-2:xxxxxxxxxxxx:accesspoint/sp-flow-xxxxxxxx-xxxxxxx-accesspoint | sp-flow-xxxxxxxx-xxxxxxx-accesspoint | aws_s3_access_point | { "ARN": "arn:aws:s3:us-west-2:xxxxxxxxxxxx:accesspoint/sp-flow-s3bucket-logsink-accesspoint", "Account ID": "xxxxxxxxxxxx", "Name": "sp-flow-xxxxxxxx-xxxxxxx-accesspoint", "Region": "us-xxxx-2" }

with the config: 
```
category "aws_s3_access_point" {
  icon = format("%s,%s", "image://data:image/svg+xml;base64", filebase64("./icons/s3_access_point.svg"))
}
```
where 
```
binaek@Turingmbp steampipe-mod-aws-insights % ls -l  ./icons/s3_access_point.svg
-rw-------@ 1 binaek  staff  2543  5 Aug  2020 ./icons/s3_access_point.svg
```

I am only seeing the following:
![Screenshot 2022-08-08 at 7 00 22 PM](https://user-images.githubusercontent.com/1114038/183429638-b2235e6b-78a1-4555-aaa6-3cca064f6e94.png)

> **Note:** for nodes which have this error, it's also not following the `href` value in the `category` block

**Comment by MichaelBurgess** [comment]
@binaek should be resolved in latest react-flow approach - please re-open or raise again if you see any issues.
