### ISSUE TITLE
`ignore if empty` on graph node/edge properties

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#2304]
When creating the `properties` column, it will be great if I could set an `on empty` behaviour for some properties.

Use case:
For Application and Network LB, we can set a bucket to log to with a particular (optional) prefix. Since the prefix is optional, it's showing up even when empty. We can take care of this by not including this in the `properties` JSON when empty, but that will leads to a messy SQL.

**Comment by MichaelBurgess** [comment]
Currently the only option we have here is to set `display = "none"` for the category `field`, but clearly that is static and will apply to all fields of that name for that category, even if they have a value.

Could we consider expanding out the interpolated string functionality to the field `display` property? Then we could conditionally hide the column? my jq may be off here, but something like:

```
display = "{{ if .prefix == null then "none" else "all" }}"
```

An (simpler) alternative is we show empty values with a value such as:

```
Prefix
<italic>Empty</italic>
```

@e-gineer / @johnsmyth thoughts on this?
