### ISSUE TITLE
Error when starting Steampipe

### ISSUE THREAD

**Issue by sapg** [turbot/steampipe#2316]
**Describe the bug**

I installed Steampipe using brew on MacOS 10.15.7 (Catalina).

Initially, it worked, I could run `steampipe query` but after I tried installing and using a dashboard (which never loaded, it looked like it was loading something but it never appeared) I can't run `steampipe query` anymore, I get this error:

Error: error acquiring database connection, failed to create introspection tables: ERROR: invalid byte sequence for encoding "UTF8": 0x96 (SQLSTATE 22021)

**Steampipe version (`steampipe -v`)**
0.15.4

**To reproduce**
As above.

**Expected behavior**
I was hoping to do some Steampipe queries and I was hoping to use the AWS Thrifty dashboard.

**Comment by sapg** [comment]
I got a dashboard to load but I still get a database error, albeit a different one.

![image](https://user-images.githubusercontent.com/1245849/184142011-5515c50f-c604-4431-8537-7e16e0006eae.png)

**Comment by kaidaguerre** [comment]
@sapg sorry for delay in following this up. A few questions: 
- if you run `steampipe query` from an empty folder does it work?
- you say you installed a dashboard - which mod did you install?  It is failing when you run `steakmpipe query` from within the mod folder?

**Comment by e-gineer** [comment]
As background, once you have a `mod.sp` file in a directory, Steampipe will recursively search for `*.sp` and `*.sql` files from that point. So, perhaps one of your files has invalid UTF8?
