### ISSUE TITLE
`Unsupported argument` should show the connection name 

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe#232]
I get an error when starting steampipe because one of my connection files has a bad argument.   The error message should say which connection is causing the error:

```bash
$ steampipe query
Error: failed to refresh connections: failed to parse connection config: Unsupported argument: An argument named "account" is not expected here.
```

**Comment by kaidaguerre** [comment]
fixed by 3262deb4031763095eae719fa4f5430b67a327c7
