### ISSUE TITLE
steampipe `CI` mode

### ISSUE THREAD

**Issue by binaek89** [turbot/steampipe#233]
We should have a `--ci` flag for all commands.

`TBD: do we also need an environment variable?`

When `CI` mode is enabled, the CLI will:
* disable `scheduled tasks` (`cli update check`, `plugin update check`, `log trimming`)
* disable `spinner` display
* disable `paging` of output

**Comment by kaidaguerre** [comment]
closing - we need a wider rethink of the display encapsulation
