### ISSUE TITLE
Table of Contents in dashboards

### ISSUE THREAD

**Issue by tnelson-doghouse** [turbot/steampipe#2338]
**Is your feature request related to a problem? Please describe.**

Dashboards get long; it'd be nice to be able to jump to the right part

**Describe the solution you'd like**
* To start with, anchor links for the headers
* Then, a section (like table or chart) that collates the headers and puts them in, with links to the headers

**Describe alternatives you've considered**
Just doing step 1 and not step 2

**Comment by tnelson-doghouse** [comment]
Just add water; then it won't be stale.

**Comment by MichaelBurgess** [comment]
We agree this would be a good feature to add, however we're not able to look at this currently due to other priorities, so will close this issue for now.
