### ISSUE TITLE
Intermittent issues with all dashboard resources not loading properly

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#2344]
**Describe the bug**
Sometimes when loading dashboards with multiple resources (inputs, graphs, charts, cards), some resources will not load properly (difficult to tell if the query is experiencing errors or not).

**Steampipe version (`steampipe -v`)**
v0.17.0-alpha.6

**To reproduce**
Run several dashboards from the `new-relationship-graphs` branch in https://github.com/turbot/steampipe-mod-aws-insights/tree/new-relationship-graphs, in particular the EC2 Instance Detail dashboard.

**Expected behavior**
All components should render properly.

**Additional context**

**Comment by kaidaguerre** [comment]
fixed by [a712d9defc2b0850ae6602685d9e19d1b9cac9fb](https://github.com/turbot/steampipe-plugin-sdk/commit/a712d9defc2b0850ae6602685d9e19d1b9cac9fb)
