### ISSUE TITLE
package steampipe for debian stable

### ISSUE THREAD

**Issue by pathcl** [turbot/steampipe#2362]
**Is your feature request related to a problem? Please describe.**
Be able to install steampipe from debian stable.

**Describe the solution you'd like**
A package available in debian official repository.

**Describe alternatives you've considered**
N/A

**Additional context**
[slack thread](https://steampipe.slack.com/archives/C01UECB59A7/p1661244969895979)

**Comment by pskrbasu** [comment]
@pathcl 

Thank you for the issue. We did some initial work and discussions on how to proceed with this, but it is not our immediate priority to get it out. 

I believe you can use our installer script to install Steampipe in your Debian system (https://steampipe.io/downloads) for now.

We will definitely work on this and get this done, but "not now".

Thanks
