### ISSUE TITLE
Add snapshot as output and export  format for `query` and `check` commands

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#2366]
- a new `snapshot` output format (`--output`) will be added to `steampipe check`, `steampipe query`, and `steampipe dashboard`
  - `snapshot` is the 'standard' json output format for snapshots, as we are currently doing in steampipe cloud

- `steampipe check` should also add `snapshot` as an `--export` option

**Comment by pskrbasu** [comment]
Completed
