### ISSUE TITLE
Export does not merge benchmark results when running multiple benchmark checks in one steampipe command

### ISSUE THREAD

**Issue by sfunkernw** [turbot/steampipe#2380]
**Describe the bug**

Export does not merge benchmark results when running multiple benchmark checks in one steampipe command. 

**Steampipe version (`steampipe -v`)**
steampipe version 0.16.0

**Plugin version (`steampipe plugin list`)**
- hub.steampipe.io/plugins/turbot/aws@latest 0.74.1
- hub.steampipe.io/plugins/turbot/steampipe@latest 0.5.0

**To reproduce**

```bash
steampipe check aws_compliance.benchmark.cis_v140 aws_compliance.benchmark.foundational_security aws_compliance.benchmark.other --export sp-cis-foundational-other-compliance-mod.json --max-parallel 5
```
This command runs properly all 3 benchmarks sequentially, but in the output file `sp-cis-foundational-other-compliance-mod.json` only the JSON formatted output of the last benchmark (`aws_compliance.benchmark.other`) is included.

**Expected behavior**

I would expect that the output of all 3 executed benchmarks end up in the exported output file.
In the case of the JSON output, expect to have have in the root object the sum of the status attributes for all benchmarks and in the top level groups array, I expect to have the 3 benchmark groups included as array elements.

**Additional context**

This behavior seems to be the same for the other formats (CSV etc.) as well.

Please note, whoever has the same problem, you could simply run the 3 benchmarks after each other and merge the results manually as described in my expected behavior.

**Comment by cbruno10** [comment]
@sfunkernw I've transferred this issue to the Steampipe repo, as this issue looks to be about more overall CLI behavior than one specific to the AWS Compliance mod. If you have any other questions though, please let us know.
