### ISSUE TITLE
Need to build a dashboard for aws resource usage, need a graph data type visualization

### ISSUE THREAD

**Issue by someshkoli** [turbot/steampipe#2398]
**Is your feature request related to a problem? Please describe.**
As a day to day usage, its often the case where I need to audit resources associated to a particular resource. I'm certain that we can get this via query but want a visualization for the same. 
This would require a graph type data structure visualization.

**Describe the solution you'd like**
Not very clear on the solution yet but happy to explore things and build this :D 

**Describe alternatives you've considered**

**Additional context**

**Comment by e-gineer** [comment]
Hey @someshkoli ... Great minds think alike 😄  ... We're actually working on relationship diagrams with a `graph` component in the dashboard model right now. It's early, it's rough, but it does work.

You can try using `v0.17.0-alpha.10` or similar - https://github.com/turbot/steampipe/releases/tag/v0.17.0-alpha.10

And then run it with the AWS Insights mod branch here - https://github.com/turbot/steampipe-mod-aws-insights/tree/new-relationship-graphs

Feedback very welcome ... and we'd love your help! Suggest discussion in [our Slack community](https://steampipe.io/community/join), or through issues on the AWS Insights mod for now.

**Comment by someshkoli** [comment]
> Hey @someshkoli ... Great minds think alike 😄  ... We're actually working on relationship diagrams with a `graph` component in the dashboard model right now. It's early, it's rough, but it does work.
> 
> You can try using `v0.17.0-alpha.10` or similar - https://github.com/turbot/steampipe/releases/tag/v0.17.0-alpha.10
> 
> And then run it with the AWS Insights mod branch here - https://github.com/turbot/steampipe-mod-aws-insights/tree/new-relationship-graphs
> 
> Feedback very welcome ... and we'd love your help! Suggest discussion in [our Slack community](https://steampipe.io/community/join), or through issues on the AWS Insights mod for now.

Hey @e-gineer 🤝😂, will give it a shot. Hopping in slack ✨
