### ISSUE TITLE
Table inspect command is not working with table name format "test.my.table"

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe#2455]
**Describe the bug**
```
> select name, api_version from "certificates.cert-manager.io"
+---------+--------------------+
| name    | api_version        |
+---------+--------------------+
| root-ca | cert-manager.io/v1 |
+---------+--------------------+


> .inspect "certificates.cert-manager.io"
Error: Could not find connection called 'certificates'
```

**Steampipe version (`steampipe -v`)**
Example: 0.17.0-alpha.15

**To reproduce**
 Run .inspect command for any table with format "test.my.table"

**Expected behavior**
It should provide all the column details.

**Additional context**

**Comment by bigdatasourav** [comment]
@kaidaguerre, Could you please look into it? As we are going to release the dynamic tables, the above should work.

**Comment by johnsmyth** [comment]
FYI - We have a number of plugins that create dynamic table names that may require quoting, and they do not work with `.inspect`.
