### ISSUE TITLE
Routing errors in development environment

### ISSUE THREAD

**Issue by cliffpyles** [turbot/steampipe#2458]
**Describe the bug**

When working on the dashboard's UI in Storybook, some of the components throw an error that reads:

```
useNavigate() may be used only in the context of a <Router> component.
```

Once this is thrown, the developer can no longer navigate the items in the Storybook sidebar.

**To reproduce**

1. Load storybook
2. Open browser to localhost:6006
3. Navigate to Area > Single Series

**Expected behavior**

Developers can navigate the stories in Storybook

**Additional context**

https://user-images.githubusercontent.com/904039/191692052-a4679754-136a-4f8c-adf3-8a4fff5acac8.mp4

**Comment by MichaelBurgess** [comment]
Thanks for reporting @cliffpyles - we'll get this sorted.
