### ISSUE TITLE
failed to connect to host=localhost user=root database=postgres

### ISSUE THREAD

**Issue by GonzoMG** [turbot/steampipe#2465]
**Describe the bug**
When running Steampipe initially, the failed to connect error comes along with a dial error of (dial tcp:9193: connect: connection refused)

**Steampipe version (`steampipe -v`)**
v0.16.3

**To reproduce**
Simply run **_steampipe query_** for an interactive session, then it the prompt shows up  then a few seconds later the error happens.
**Expected behavior**
I expect to run my query and proceed as I have for the past year or so

**Additional context**
N/A

**Comment by e-gineer** [comment]
🙁 sorry to hear you've hit that bump @GonzoMG - but thanks for letting us know!

We optimize the Postgres install for in memory operation, but unfortunately that makes it more susceptible to data corruption. I suspect that is what may have happened here.

I suggest you try resetting the steampipe database completely:
```
# delete the steampipe install dir
rm -rf ~/.steampipe/db

# ensure steampipe is not running
pkill -f steampipe

# try running again, should re-install the database
steampipe query
```

Please let us know if that resolves the issue.

**Comment by GonzoMG** [comment]
WOW!!  Thanks so much!!  Huge help!!

On Mon, Sep 26, 2022 at 9:57 AM Nathan Wallace ***@***.***>
wrote:

> 🙁 sorry to hear you've hit that bump @GonzoMG
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_GonzoMG&d=DwMFaQ&c=Z4P52L0foFKAY1wcP-GmiQ&r=mgcWzvtxKLGumXrWf50K-ujuxtR_HNEDsOAgIcKpb4k&m=bduOEBVEVR1Tu5FoZVmhIoMNqcgP1Eyi6fZdCaQ8Nq4IayLaOs-AGhzntO8Jjgv3&s=30NcJM4w3EbPdnCb60wC0HDWtfJRP5Hi4zPLL1WSgPk&e=>
> - but thanks for letting us know!
>
> We optimize the Postgres install for in memory operation, but
> unfortunately that makes it more susceptible to data corruption. I suspect
> that is what may have happened here.
>
> I suggest you try resetting the steampipe database completely:
>
> # delete the steampipe install dir
> rm -rf ~/.steampipe/db
>
> # ensure steampipe is not running
> pkill -f steampipe
>
> # try running again, should re-install the database
> steampipe query
>
> Please let us know if that resolves the issue.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_turbot_steampipe_issues_2465-23issuecomment-2D1258083502&d=DwMFaQ&c=Z4P52L0foFKAY1wcP-GmiQ&r=mgcWzvtxKLGumXrWf50K-ujuxtR_HNEDsOAgIcKpb4k&m=bduOEBVEVR1Tu5FoZVmhIoMNqcgP1Eyi6fZdCaQ8Nq4IayLaOs-AGhzntO8Jjgv3&s=Qd8SIOULV6jnprcoDau41KQI4XsZ-XajBrvu6b0fo_Y&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A3GS36RHQLMS3ZNSJDOBGUDWAGTVVANCNFSM6AAAAAAQV2A4TY&d=DwMFaQ&c=Z4P52L0foFKAY1wcP-GmiQ&r=mgcWzvtxKLGumXrWf50K-ujuxtR_HNEDsOAgIcKpb4k&m=bduOEBVEVR1Tu5FoZVmhIoMNqcgP1Eyi6fZdCaQ8Nq4IayLaOs-AGhzntO8Jjgv3&s=f5x0ACb7STNvs4URvrL51uGccDBzQszHD6ZEZg3Kz8I&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

-- 
NOTICE: This email message is for the sole use of the addressee(s) named 
above and may contain confidential and privileged information. Any 
unauthorized review, use, disclosure or distribution of this message or any 
attachments is expressly prohibited. If you are not the intended recipient, 
please contact the sender by reply email and destroy all copies and backups 
of the original message.

**Comment by GonzoMG** [comment]
Okay, you've helped me get past one hurdle and I'm hoping this next one is
as easy...

Now when I run my query I get the following message...  I'm guessing it's
our proxy...

caused by: open http://127.0.0.1:9000: no such file or directory

LoadCustomCABundleError: failed to open custom CA bundle PEM file

On Mon, Sep 26, 2022 at 11:11 AM Hector Gonzalez ***@***.***> wrote:

> WOW!!  Thanks so much!!  Huge help!!
>
> On Mon, Sep 26, 2022 at 9:57 AM Nathan Wallace ***@***.***>
> wrote:
>
>> 🙁 sorry to hear you've hit that bump @GonzoMG
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_GonzoMG&d=DwMFaQ&c=Z4P52L0foFKAY1wcP-GmiQ&r=mgcWzvtxKLGumXrWf50K-ujuxtR_HNEDsOAgIcKpb4k&m=bduOEBVEVR1Tu5FoZVmhIoMNqcgP1Eyi6fZdCaQ8Nq4IayLaOs-AGhzntO8Jjgv3&s=30NcJM4w3EbPdnCb60wC0HDWtfJRP5Hi4zPLL1WSgPk&e=>
>> - but thanks for letting us know!
>>
>> We optimize the Postgres install for in memory operation, but
>> unfortunately that makes it more susceptible to data corruption. I suspect
>> that is what may have happened here.
>>
>> I suggest you try resetting the steampipe database completely:
>>
>> # delete the steampipe install dir
>> rm -rf ~/.steampipe/db
>>
>> # ensure steampipe is not running
>> pkill -f steampipe
>>
>> # try running again, should re-install the database
>> steampipe query
>>
>> Please let us know if that resolves the issue.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_turbot_steampipe_issues_2465-23issuecomment-2D1258083502&d=DwMFaQ&c=Z4P52L0foFKAY1wcP-GmiQ&r=mgcWzvtxKLGumXrWf50K-ujuxtR_HNEDsOAgIcKpb4k&m=bduOEBVEVR1Tu5FoZVmhIoMNqcgP1Eyi6fZdCaQ8Nq4IayLaOs-AGhzntO8Jjgv3&s=Qd8SIOULV6jnprcoDau41KQI4XsZ-XajBrvu6b0fo_Y&e=>,
>> or unsubscribe
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A3GS36RHQLMS3ZNSJDOBGUDWAGTVVANCNFSM6AAAAAAQV2A4TY&d=DwMFaQ&c=Z4P52L0foFKAY1wcP-GmiQ&r=mgcWzvtxKLGumXrWf50K-ujuxtR_HNEDsOAgIcKpb4k&m=bduOEBVEVR1Tu5FoZVmhIoMNqcgP1Eyi6fZdCaQ8Nq4IayLaOs-AGhzntO8Jjgv3&s=f5x0ACb7STNvs4URvrL51uGccDBzQszHD6ZEZg3Kz8I&e=>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

-- 
NOTICE: This email message is for the sole use of the addressee(s) named 
above and may contain confidential and privileged information. Any 
unauthorized review, use, disclosure or distribution of this message or any 
attachments is expressly prohibited. If you are not the intended recipient, 
please contact the sender by reply email and destroy all copies and backups 
of the original message.

**Comment by GonzoMG** [comment]
Looks like the port 9000 was on my end. 

Thanks again!!
