### ISSUE TITLE
Alt-d causes strange behavior in interactive shell

### ISSUE THREAD

**Issue by rmaalouf** [turbot/steampipe#2480]
Version: 0.16.4
Platform: WSL2

alt-d is a common shell shortcut to delete the word after the cursor. Using it in the interactive shell seems to insert an invisible character as well as cause other strange behavior. The invisible character will cause an otherwise correct query to error with "Error: syntax error at or near "QLSTATE 42601)". The command history also retains the invisible character so you can spend a very long time trying to "fix" a query that is actually valid.

**Comment by kaidaguerre** [comment]
@rmaalouf thanks for report - that's clearly not desired behaviour!

I'll take a look at getting a fix for that in place.

**Comment by rmaalouf** [comment]
Thanks @kaidaguerre 

more info:

alt+f and alt+b work fine but it seems like alt+ any other <character> adds both <character> and that sneaky invisible character. 

Other than the 2 mentioned above, alt+d and alt+backspace are the other useful shortcuts I use in the shell.
