### ISSUE TITLE
Hovering color for icons

### ISSUE THREAD

**Issue by Ayushbajpai19** [turbot/steampipe#2489]
**Is your feature request related to a problem? Please describe.**
There have been times when steampipe.io website seems too simple and there are too much negative spaces which makes it look very dull and sort of not attractive to audience.
**Describe the solution you'd like**
What I want to do is add colors whenever the cursor is hovered over cloud providers in the hero section as well as when the cursor is hovered over community section in footer, the color does not have to be in multicolor but just in a single or two colors.
**Describe alternatives you've considered**
Maybe just a little bit increase in size or a popup with details of the cloud provider
**Additional context**
I hope you will like this feature and get it added onto the current website, also i would really like to get it labelled as hacktoberfest

**Comment by jainrishi2001** [comment]
Can I try to work on this?
