### ISSUE TITLE
Connection is removed from the connection state file but the db schema is not removed

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#2496]
When a connection is removed and verified that it is indeed removed from the connection state file, but the connection still shows up in the `search_path` and the foreign schema, i.e db schema is not removed.

Reproduction steps could not be defined for this case.

Similar issue Reported here:
https://turbothq.slack.com/archives/C01AC8JQNHH/p1665144466796359

**Comment by rajlearner17** [comment]
I faced the same issue with the Azure plugin and demoed it to @pskrbasu. The hacking was to use the same connection name in my aggregator connection to unblock. I will keep posted in case this is repeatable.
