### ISSUE TITLE
Support M1

### ISSUE THREAD

**Issue by yi2020** [turbot/steampipe#253]
Noticed "Error: ARM is not supported yet" in the installer. Would love to see M1, now that Go 1.16 is out :)

**Comment by e-gineer** [comment]
Thanks @yi2020 ... We agree that Apple M1 support would be great.

Our Postgres FDW sits at the intersection of Postgres, C, CGO and Go so unfortunately it's more work than a straight cross-compile...

**Comment by cbruno10** [comment]
Hey @yi2020 , I just tried installing the latest version of Steampipe on the latest M1 Pro Macbook, and I was able to install + run a query. I'm closing this issue since it looks we support M1 chips now, but if you run into any issues, please let us know!
