### ISSUE TITLE
Update acceptance test jobs in release workflows

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#2552]

**Comment by SaumyaBhushan** [comment]
Hi @pskrbasu I would like to work on this if you could guide me .

**Comment by pskrbasu** [comment]
> Hi @pskrbasu I would like to work on this if you could guide me .

Hi, @SaumyaBhushan 
Thank you very much for your interest. Sorry, but I had already started working on it, as this issue was our high priority for today.

However, I would recommend a similar [issue](https://github.com/turbot/steampipe/issues/2369) for you to work on, please take a look. 

Please reach out to me, @kaidaguerre or @binaek if needed.

Thanks
