### ISSUE TITLE
Single job with tests for acceptance and release workflows

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#2553]
Currently, even though we have a single set of test files, they are run as jobs described from the acceptance test and the release workflow.

This may lead to fragmentation on how the tests are run in the two.

Ideally, there should be one workflow which runs just the tests and which is triggered by the acceptance and release workflows.

Reference: https://docs.github.com/en/actions/using-workflows/reusing-workflows#reusable-workflows-and-starter-workflows

**Comment by Pankaj-SinghR** [comment]
hey @binaek can i work on this issue?

**Comment by binaek** [comment]
@Pankaj-SinghR thank you for extending your helping hands. Have at it! 

Let us know if you need any input

**Comment by binaek** [comment]
@Pankaj-SinghR we want to get this in! Are you looking at this? Let us know if you need any help from us.

**Comment by Pankaj-SinghR** [comment]
@binaek Thanks, can you provide me some references, regarding workflow?

**Comment by binaek** [comment]
@Pankaj-SinghR 

You may have noticed that we run acceptance tests during release as well as on commits to branches which have active PRs:
- https://github.com/turbot/steampipe/blob/main/.github/workflows/release_cli_and_assets.yml#L306
- https://github.com/turbot/steampipe/blob/main/.github/workflows/test.yml#L87

This is useful for us - but has repetition in different workflows and we have had to keep these two jobs in sync whenever we add a test suite.

What we are looking for is a single `workflow` (let's call it `Acceptance Tests`) which can be nested in the Release and Merge workflows.

This document may be helpful:
https://docs.github.com/en/actions/using-workflows/reusing-workflows
