### ISSUE TITLE
Add terminal option to disable auto-complete

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#2560]
For very large environments autocomplete in the interactive terminal can be annoying slow for typing. While it should be faster, it would also be helpful at times to just disable autocomplete.

I'd propose a setting for terminal - https://steampipe.io/docs/reference/config-files/terminal

```
auto_complete = false
```

**Comment by TomerPacific** [comment]
Hey @e-gineer , I'd like to help out here. Any details I should be aware of before starting?

**Comment by e-gineer** [comment]
We'd love your help @TomerPacific! As a starting point, I imagine the implementation would be similar to `multi`

https://github.com/turbot/steampipe/search?l=Go&q=multi

**Comment by TomerPacific** [comment]
@e-gineer , I have tried looking for a way to set up a local development environment, but couldn't find anything.
Is there a resource you can point me to?

I saw the [Contributing ](https://github.com/turbot/steampipe/blob/main/CONTRIBUTING.md)guide, but it did not have this information. Especially if this feature is related only to the terminal.

I want to have a way to test out my changes.

**Comment by TomerPacific** [comment]
@e-gineer - seems like I have been bamboozled by [Mr-Destructive](https://github.com/Mr-Destructive) (what an appropriate name).
