### ISSUE TITLE
steampipe mod init should warn users when the directory is large / unusual

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#2562]
We've seen a few users accidentally run `steampipe mod init` in their home directory, which then causes steampipe commands in that location or lower to try and load all files (slow performance, easy to error if files are invalid).

When running `steampipe mod init` It would be great to warn if:
* It's run in the home directory
* It's run in a directory with a lot of files or subdirectories (e.g. >5 files that are not .sql or .sp)

**Comment by SaumyaBhushan** [comment]
Hey @e-gineer I would like to work on this . Can you please guide me how to do this?

**Comment by kaidaguerre** [comment]
Hey @SaumyaBhushan thanks for that. 

The mod init is performed by this function: https://github.com/turbot/steampipe/blob/f80f9c1b21b9a3d8edc6c54b5f4de15d29bef55b/cmd/mod.go#L215

I suggest adding a function `verifyModLocation` to be called before 
```
mod := modconfig.CreateDefaultMod(workspacePath)
```

**Comment by Aaronstotle** [comment]
Hello, I'd like to work on this issue, thanks for the description/breaking it down

**Comment by Aaronstotle** [comment]
https://github.com/Aaronstotle/steampipe_mod_init/commit/fac993ccd4ecbc3ee2d45471bc35b53ccc0e70bc

So I have a basic function here that will trigger when I run this in my home directory, however I'm not sure how I stop make the program stop and confirm for the user
