### ISSUE TITLE
Update deprecated `set-output` and use `GITHUB_OUTPUT` environment files in our workflows

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#2572]
GitHub actions is deprecating `save-state` and `set-output` commands. We use the `set-output` command in our acceptance tests and other workflows. Time to update.
![Screenshot 2022-10-21 at 5 26 15 PM](https://user-images.githubusercontent.com/45908484/197190253-3d4e7609-3c76-46af-b5f4-39a5f44484b3.png)

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by SaumyaBhushan** [comment]
Hi @pskrbasu I would like to work on this . Can you please assign it to me ?

**Comment by pskrbasu** [comment]
Sure @SaumyaBhushan, go ahead and take a look. Reach out to us if needed.

**Comment by SaumyaBhushan** [comment]
Hi @pskrbasu Please review the pull-request .
