### ISSUE TITLE
Error message display in CLI should include special chars and line/char number position

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#263]
While working on a new table today, I ended up getting this error message:
```
~/src/steampipe-plugin-terraform $ steampipe query
Welcome to Steampipe v0.2.3
For more information, type .help
> select * from foo_item
Error: syntax error at or near ""
> 
```

Digging into the logs, the real error was actually:

![image](https://user-images.githubusercontent.com/1328145/110208130-521ec400-7e55-11eb-8bf3-006400724b9f.png)

Two things:
* Notice how the ^D characters are specially rendered / shown in my vi editor?
* This log error makes it clear the problem is in my query at character 29

Turns out that a Ctrl-D character had somehow made it into my query string. (I think through a quit sequence gone wrong?). So, pressing up in my history showed a query that had worked previously (the Ctrl-D is hidden) but then I go the cryptic `near ""` error.

It would be great if the real, detailed error message with rendering of the special chars into steampipe cli?

**Comment by binaek** [comment]
Closed by https://github.com/turbot/steampipe/pull/1167
