### ISSUE TITLE
Dashboard table - Sorting Boolean columns doesn't work

### ISSUE THREAD

**Issue by rmaalouf** [turbot/steampipe#2636]
**Describe the bug**
From a dashboard, clicking on a Boolean column's header doesn't have the desired effect of grouping all trues and falses together.

**Steampipe version (`steampipe -v`)**
0.16.4

**Workaround**
Cast the column to **::text** in the select statement

**Comment by MichaelBurgess** [comment]
@rmaalouf thanks for reporting this - will be released in the forthcoming v0.17 release dropping soon.
