### ISSUE TITLE
Rationalise use of spinners and status hooks

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#2683]
The usage between the various commands is confusing at present. 

For example, the database package should probably not set status hooks directly - and has tactical workarounds such as https://github.com/turbot/steampipe/blob/42c2323eb22015671cc31ff350d3d7b1b521a95d/pkg/db/db_client/db_client_execute.go#L382

Simplify, document and improve.

**Comment by binaek** [comment]
Idea: `spinner` usage can be scoped to a `show` and `done` pair.

An interface can be provided like: `statushooks.Scope(callback_function)` (name TBD) where the `Scope` function takes responsibility of the spinner lifecycle.

```
fn Scope(cb) {
  spinner.show()
  cb()
  spinner.hide()
}
```
