### ISSUE TITLE
`select count(*) from any table` always returns `Hydrate calls: 0`

### ISSUE THREAD

**Issue by misraved** [turbot/steampipe#2700]
**Describe the bug**
On running `select count(*) from aws_s3_bucket`, the number of hydrate calls information is always `0`. I am assuming that, in order to fetch the count we are making API calls(Hydrate calls) in the background.

**Steampipe version (`steampipe -v`)**
v0.17.0-rc.7

**To reproduce**
1. open the terminal and run `select count(*) from aws_s3_bucket`, the `Hydrate calls` parameter will always display `0`.

**Expected behavior**
I think we should display the number of API calls that are beings made in the background.

**Additional context**
Sample output:
```
> select count(*) from aws_s3_bucket
+-------+
| count |
+-------+
| 28    |
+-------+

Time: 1.5s. Rows fetched: 28. Hydrate calls: 0.
```

**Comment by kaidaguerre** [comment]
This is by design 

when running a count, we pass an empty column list to the plugin. We _do not_ want to call hydrate functions just top get a count.
