### ISSUE TITLE
When default variables are used, send that in the "execution_complete" event.

### ISSUE THREAD

**Issue by chandru89new** [turbot/steampipe#2730]
**Describe the bug**
When default variables are used, snapshot data "execution_complete" event does not get the variables that were originally used to render the dashboard. For eg, in the case of `net_insights.benchmark.dns_best_practices` dashboard, we get an empty string for `domains_names` even though the benchmark/dashboard uses some domains by default (eg github.com).

**Steampipe version (`steampipe -v`)**
Example: ~v0.17.0 v0.17.3~ v0.18.1

**To reproduce**
Easier to replicate on SPC. Run the Net Insights / DNS Best Practices dashboard, take a snap and view the details (by going to the details page for that snapshot). 

**Expected behavior**
If there are defaults used by the CLI, these should be passed on to the socket instead of what was originally given by the user.

**Additional context**
None.

**Comment by MichaelBurgess** [comment]
@chandru89new have you gone over this issue with @kaidaguerre?

**Comment by chandru89new** [comment]
> @chandru89new have you gone over this issue with @kaidaguerre?

@MichaelBurgess yes, and Kai suggested I create this issue here. I will follow-up on this today with Kai.

**Comment by chandru89new** [comment]
@kaidaguerre sorry to have dropped the ball on this thread, but any update on this?

**Comment by chandru89new** [comment]
Update: In my recent tests with v0.17.3, I do notice that the socket event returns the right `variables` value (ie, if defaults are being used, those defaults are sent in the `variables` property). However, this does not happen when on SPC test envs. Happy to close this issue here and move it to SPC if that makes sense.

**Comment by chandru89new** [comment]
@kaidaguerre can you look into this?
