### ISSUE TITLE
Sorting Numerics in Strings

### ISSUE THREAD

**Issue by johngarner-dwp** [turbot/steampipe#2745]
When ordering on string columns with numbers it would be very useful to be able to utilise collations to ensure the ordering is correct.

See https://dbfiddle.uk/cptUkufH

**Comment by pskrbasu** [comment]
Hello @johngarner-dwp, thank you for the issue.

I understand you're trying to order string columns with numbers, but can you give us a deeper look into your use case, as in why/how you want to create/utilise collations?

From your example [here](https://dbfiddle.uk/cptUkufH), I was able to achieve the same ordering by doing something like this: `select * from data order by length(label), label asc;`
```
+----+---------+
| id | label   |
+----+---------+
| 1  | DISK 2  |
| 7  | DISK 8  |
| 5  | DISK 15 |
| 3  | DISK 33 |
+----+---------+
```
So we would prefer to learn more about your business use case and how you are using Steampipe, and in the process, we can explore and discuss what we need to do(collations or anything else) to achieve what you're looking for and enhance your user experience.

Thanks

**Comment by johngarner-dwp** [comment]
Hi thanks for looking at this...

I'm using the JIRA plugin and searching in this case against "title" column in the "jira_issue" table.  The column contains three uppercase letters followed by a hyphen and four numbers, e.g. ABC-1234.

Executing your SQL recommendation returns the resultset in the desired order.

I came up with the rather less elegant... 

```sql
select title 
from jira_issue
where project_key = 'ABC' 
and status = 'In Progress' 
order by substring(title, '\d+')::int;
```

Your method is much more refined and easier on the eye.  It is very much the better solution for general users.

The collation (or a view?) would hide the `order by` completely, but I'm not sure it warrants the effort in this case.

Really appreciate your feedback - thanks again!
