### ISSUE TITLE
Edges for self-referencing nodes not rendering properly in graphs

### ISSUE THREAD

**Issue by karanpopat** [turbot/steampipe#2749]
**Describe the bug**

Edges for self-referencing nodes are not rendering properly.
Example in the screenshot below where an S3 bucket is logging into itself - 

![image](https://user-images.githubusercontent.com/16674560/201956514-c806d637-b233-474e-a90d-c71e3c0b3a99.png)

**Steampipe version (`steampipe -v`)**
steampipe version 0.18.0-dev.8

**Comment by MichaelBurgess** [comment]
Will re-open if we decide to fix this one.

**Comment by rajlearner17** [comment]
@MichaelBurgess, we have a similar issue in this case as well. Is there a way to address this?
![image](https://user-images.githubusercontent.com/26873346/216545006-b0da60a9-0340-471d-abb4-aae97bd04325.png)
