### ISSUE TITLE
Error: out of shared memory (SQLSTATE 53200) during cli launch when high number of aws.spc connections 

### ISSUE THREAD

**Issue by ndemouron** [turbot/steampipe#2756]
Error: out of shared memory (SQLSTATE 53200) during cli launch when high number of aws.spc connections  on macos ventura arm with Steampipe v0.17.1

To be reproduce with more than 70 aws connections, all regions.
Launching in debug with
`STEAMPIPE_LOG=trace steampipe query` 
show these messages:
```
2022-11-15 20:39:10.154 UTC [TRACE] steampipe: executeConnectionUpdateQueries: num updates 73
2022-11-15 20:39:10.155 UTC [TRACE] steampipe: executing 73 update queries
> 2022-11-15 20:39:34.168 UTC [TRACE] steampipe: all update queries executed
2022-11-15 20:39:34.169 UTC [TRACE] steampipe: executing 71 comment queries
2022-11-15 20:39:48.578 UTC [TRACE] steampipe: executeUpdateQueries returned error: ERROR: out of shared memory (SQLSTATE 53200)

Error: out of shared memory (SQLSTATE 53200)
```

Without debug, stuck with 
`⠏ Initializing... `
then
`Error: out of shared memory (SQLSTATE 53200)`

fixed by the team by increasing the `max_locks_per_transaction from 64 to 6400`
in a dedicated .conf file in` ~/.steampipe/db/14.2.0/data/postgresql.conf.d`

```
> show max_locks_per_transaction
+---------------------------+
| max_locks_per_transaction |
+---------------------------+
| 64                                           |
+---------------------------+
```

**Comment by GonzoMG** [comment]
Not sure if this will fix your particular instance but I was able to get mine working properly once I did the following:
_brew upgrade_ (during this postgres gets upgraded as well)
_brew install steampipe_
And because I'm a big chicken, installed my plugins one at a time.

And....  Happy happy joy joy! 

Y'all have a great Thanksgiving!

**Comment by sshvetsov** [comment]
Been having the same problem after upgrading to 1.17.1. @ndemouron, huge thanks for describing the fix.
