### ISSUE TITLE
Incorrect control severity tags on the Steampipe hub

### ISSUE THREAD

**Issue by misraved** [turbot/steampipe#2780]
**Describe the bug**
The Steampipe hub only seems to identify `severity=low` and `severity=critical` tags even though the controls have tags like `severity = "medium"` or `severity = "high"`.

**Steampipe version (`steampipe -v`)**
Example: 0.18.0-alpha.1

**To reproduce**
Control file - https://github.com/turbot/steampipe-mod-aws-compliance/blob/fd0b6cff69b2451f646f141e9d4f10369c61b9dd/foundational_security/autoscaling.sp

UI link - https://hub-steampipe-io-git-staging-turbot.vercel.app/mods/turbot/aws_compliance/controls/control.foundational_security_autoscaling_1?context=benchmark.foundational_security/benchmark.foundational_security_autoscaling

**Expected behavior**
The control tags on the Steampipe hub should match the tags defined in the `.sp` file.

**Additional context**

**Comment by MichaelBurgess** [comment]
Wrong repo.
