### ISSUE TITLE
Add validate configuration option

### ISSUE THREAD

**Issue by volphy** [turbot/steampipe#2804]
It would be great to add Steampipe configuration (*.spc files) validation to steampipe i.e.,

```
steampipe validate
```

This command could perform two high-level actions:
- perform static validation a la CloudFormation validation: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/validate-template.html
- perform dynamic validation such as verifying if connections can be established successfully

Related issue:
https://github.com/turbot/steampipe-plugin-aws/issues/1404

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pskrbasu** [comment]
Hi @volphy, thank you for the issue, and yes it sounds like a good idea to validate the steampipe configuration files.
However, we would have to discuss this internally and we will get back to you if we need any feedback on this.

Thanks
