### ISSUE TITLE
Dynamic Bootstrapping Tool/ Template Generator

### ISSUE THREAD

**Issue by td4b** [turbot/steampipe#2839]
**Is your feature request related to a problem? Please describe.**
Problem is that steampipe configuration templates do not scale very well in large AWS environments, this tool solves this (to some degree).

**Describe the solution you'd like**
This solution takes the AWS provider and is to be able to bootsrap the configuration template. The limitation is that the target set of accounts must be part of an AWS Organization that uses AWS Identity center to manage it's accounts. As well, the user must be an Organizations Auditor/Admin (has access to read all account data).

**Describe alternatives you've considered**
The alternative is to manually configure all AWS CLI Profiles and then all Steampipe Configuration profiles manually. In large account environments this can be very annoying. 

**Additional context**
I am thinking rather than this be a steampipe PR it can be part of a set of configuration tools? This is a CLI tool that more or less just sets up steampipe to run.

**Comment by pskrbasu** [comment]
Hi @td4b, thank you for the issue, and yes it sounds like a good idea to be able to generate steampipe configuration files using a template.
This is a very complex issue and will have to be supported across all our plugins(not just aws).
We will have to discuss this internally and we will get back to you if we need any feedback on this.

Thanks
