### ISSUE TITLE
CSV output for null values

### ISSUE THREAD

**Issue by xcambar** [turbot/steampipe#2847]
**Describe the bug**
When asking for CSV output (using `--output csv`), NULL values as serialized as `<null>`.

**Steampipe version (`steampipe -v`)**
steampipe version 0.17.4

**To reproduce**
```
$ steampipe query "select 1 as foo, NULL as null_value, 2 as bar" --output csv
foo,null_value,bar
1,<null>,2
```

While json output works as expected:
```
steampipe query "select 1 as foo, NULL as null_value, 2 as bar" --output json
[
 {
  "bar": 2,
  "foo": 1,
  "null_value": null
 }
]
```

**Expected behavior**
`NULL` values should be output with as `` (zero-length string).

The above example should be:
```
$ steampipe query "select 1 as foo, NULL as null_value, 2 as bar" --output csv
foo,null_value,bar
1,,2
```

**Additional context**
N/A

**Comment by e-gineer** [comment]
Thanks for the question @xcambar.

Putting `NULL` into a CSV file is a difficult problem.

For example, consider a column of strings where the value can be either `""` or `null` ... if we treat null as an empty string that's a lossy output? (Technically the same thing could happen with `<null>`, but it seems less likely.)

Languages like golang treat strings as not being valid for a null value, so `""` is their "empty" value.

Perhaps it's worth a review of common / similar tools for how they handle the problem to ensure we're consistent? e.g. what does psql do for CSV output of null?

**Comment by xcambar** [comment]
I am new to Go but I'm happy to give it a try if you point me in the right direction.
