### ISSUE TITLE
Is it possible at the moment to join data across multiple services?

### ISSUE THREAD

**Issue by codingkarthik** [turbot/steampipe#2862]
**Is your feature request related to a problem? Please describe.**

Let's say I have the Google sheets and the Slack plugins installed and a google sheet contains the user ids of the slack employees. Can I make a query to get the slack conversations of the user ids present in the google sheet?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pskrbasu** [comment]
Hello @codingkarthik 

Yes, it is possible to join the data from two separate plugins. In fact, this is one of the most utilised use cases among Steampipe users. 
You can find inspiration and examples from our [Blog and Resource Center](https://steampipe.io/blog) category [Shift Left Join](https://steampipe.io/blog?category=Shift%20Left%20Join).

If you get stuck, feel free to contact us here or even better in our [Slack community](https://steampipe.slack.com/join/shared_invite/zt-1kv2zsbw0-5~WrmEsBWVvhIvq1hfWawQ#/shared-invite/email).

Thanks
