### ISSUE TITLE
Acceptance tests which run on PR should do a `merge` with `main` before running the tests

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#2869]
When running acceptance tests on a PR, the acceptance tests should be run after the contents of the PR have been merged with `main` locally.

This helps in two way:
1. We will immediately know when a PR is not mergeable
2. We will never end up with a situation where a PR is good on it's own merit, but fails integration

**Comment by pskrbasu** [comment]
Done in https://github.com/turbot/steampipe/pull/2993
