### ISSUE TITLE
Vim mode in the interactive prompt

### ISSUE THREAD

**Issue by farzadmf** [turbot/steampipe#2879]
**Is your feature request related to a problem? Please describe.**
Basically what the title says 🙂

**Describe the solution you'd like**
I'm addicated to using vim in every place, and it would be really nice if `steampipe` also supported.

**Describe alternatives you've considered**
None; I think this is something that should be considered by the prodct itself, so I don't think there are any alternatives here.

**Additional context**
FWIW, the current EMACS binding has some bugs that have bothered me: sometimes, after using some EMACS mode key bindings to go back and forth, delete, etc. the prompt gets messed up and the characters I type get inserted in a different location other than under the cursor (will update this if I find a reliable way to reproduce)

EDIT:
The thing that breaks the prompt, I think, is `alt+d`, which is supposed to "delete next word" in EMACS mode

In Steampipe prompt, it doesn't delete anything and I think causes the prompt to break.

**Comment by kaidaguerre** [comment]
thanks for the issue. 

Supporting emacs binding is certainly a nice idea - we also have other improvements we would like to make to the interactive interface, but they have not risen high enough on our priority list to get to them yet.

I'll defintely bear this in mind when I do get the time to revisit this code area, but I can't give a timescale right now I'm afraid.

```
The thing that breaks the prompt, I think, is alt+d, which is supposed to "delete next word" in EMACS mode
```
This we can certainly take a look at - I'll raise a separate issue to track it.

**Comment by farzadmf** [comment]
Thank you for your answer

I guess I'm the only one using the interactive prompt then 😆, because it's a bit hard to use it and not be bothered by issues facing you

One HUGE enhancement that I can think of (no matter of Vim or Emacs key bindings) is for the auto-complete dialog to be able to do fuzzy matching

I don't think it'll be done, but thought I'd share anyway

**Comment by Mr-Destructive** [comment]
I would like to work on the vim integration in steampipe, I have played with [pgcli](https://github.com/dbcli/pgcli/blob/main/pgcli/pgtoolbar.py) and it has vim keybindings, it uses the [python prompt toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit/tree/da05f669d00817655f76b82972272d4d5f4d4225).

I am new to golang, does it have any libraries/packages for parsing the vim keybindings?

**Comment by farzadmf** [comment]
I'm trying to think of any Go-based interactive CLI that I have used that supports VIM keybindings, and right now, nothing comes to mind 🙁 

I think [ipython](https://github.com/ipython/ipython) does a very good job of VIM keybindings, but again, Python based unfortunately
