### ISSUE TITLE
Ctrl-C should abort long running queries in interactive mode

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#288]
**Is your feature request related to a problem? Please describe.**

Queries can take a long time (e.g. event lists) and there is no way to abort in interactive mode. Ctrl-C does not register.

**Describe the solution you'd like**

Ctrl-C should abort the query and return any (partial) results collected so far.

**Describe alternatives you've considered**

None.

**Additional context**

See https://github.com/turbot/steampipe-plugin-equinix-metal/issues/2

**Comment by kaidaguerre** [comment]
this is a duplicate of https://github.com/turbot/steampipe/issues/120
