### ISSUE TITLE
execute queries from files, not just from command line

### ISSUE THREAD

**Issue by vielmetti** [turbot/steampipe#289]
**Is your feature request related to a problem? Please describe.**

I'm thinking about steampipe in a situation where you want to run
a series of queries non-interactively, like daily or weekly reporting.
The queries might be complex and the work of several people to
get them just right. Or they might be example queries for a plugin,
that you want to run periodically to see to it that they work right.

**Describe the solution you'd like**

An option to put the query into a file, and then execute the file.
The reference syntax might look something like `steampipe query --file myquery.txt`

**Describe alternatives you've considered**

You could put a query in a file and then use shell quoting
and expansion syntax to get the query expanded by the
shell onto the command line; you'd have to be careful
because queries often use shell metacharacters (like *).

**Additional context**

Prompted in part by a desire to test all the queries given
as examples in the new Equinix Metal plugin.

**Comment by dannysteenman** [comment]
+1 for this feature!

**Comment by kaidaguerre** [comment]
@vielmetti @dannysteenman thanks for your input/suggestions

we're certainly giving serious thought to a good way to solve this problem, watch this space

**Comment by vielmetti** [comment]
From a suggestion from @e-gineer 👍 

```
steampipe --header=false --output csv query "$(cat device-by-os.sql)"
```

will do the trick nicely, and properly quotes multi-line queries and produces results as CSV. 

@dannysteenman might find this helpful too!
