### ISSUE TITLE
brew install steampipe yields SHA256 mismatch

### ISSUE THREAD

**Issue by mgfink** [turbot/steampipe#2899]
**Describe the bug**
I'm attempting to install steampipe via Homebrew on a MacBook Pro.  It's running Ventura 13.1 and has the M1 chip.  When I run brew install steampipe, I get the following

❯ brew install steampipe
==> Fetching turbot/tap/steampipe
==> Downloading https://github.com/turbot/steampipe/releases/download/v0.17.4/steampipe_darwin_arm64.zip
Already downloaded: /Users/mike/Library/Caches/Homebrew/downloads/de740a3d8591e9dcb0ce88dc1e73c4ed3af9461f26140205ce35dda90d5a4124--steampipe_darwin_arm64.zip
Error: steampipe: SHA256 mismatch
Expected: ef951e822b6376b6cb825be63a9c15ec0264ea315ddd05aa593c0f47aeade5eb
  Actual: eff01dff4fb8dd4075f3ccb65d7ca81a9f123181102da34030401f1616f1a5c0
    File: /Users/mike/Library/Caches/Homebrew/downloads/de740a3d8591e9dcb0ce88dc1e73c4ed3af9461f26140205ce35dda90d5a4124--steampipe_darwin_arm64.zip
To retry an incomplete download, remove the file above.

As suggested, I did remove the above file which did not help.  I reviewed the checksums.txt file which did contain the expected SHA256 sum.  Also confirmed was that I could just download the zip via wget and manually calculated the same "actual" sum as described above.

❯ shasum -a 256 ./steampipe_darwin_arm64.zip
eff01dff4fb8dd4075f3ccb65d7ca81a9f123181102da34030401f1616f1a5c0  ./steampipe_darwin_arm64.zip
❯ openssl sha256 ./steampipe_darwin_arm64.zip
SHA256(./steampipe_darwin_arm64.zip)= eff01dff4fb8dd4075f3ccb65d7ca81a9f123181102da34030401f1616f1a5c0

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**To reproduce**
brew install steampipe

-or-

wget https://github.com/turbot/steampipe/releases/download/v0.17.4/steampipe_darwin_arm64.zip
openssl sha256 ./steampipe_darwin_arm64.zip

The checksums.txt file was found [here](https://github.com/turbot/steampipe/releases/download/v0.17.4/checksums.txt).

**Expected behavior**
Successful install of steampipe

**Additional context**
Worth noting, I was able to use the Linux instructions and install via the "install.sh" script.  That script appears to NOT perform a checksum check.

**Comment by pskrbasu** [comment]
Hey @mgfink, sorry to hear you're facing installation issues.

I am however unable to reproduce the issue that you are facing. I tried a fresh install(Ventura 13.1, M1)
```
➜  ~ brew tap turbot/tap
Running `brew update --auto-update`...
==> Tapping turbot/tap
Cloning into '/opt/homebrew/Library/Taps/turbot/homebrew-tap'...
remote: Enumerating objects: 447, done.
remote: Counting objects: 100% (153/153), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 447 (delta 120), reused 118 (delta 93), pack-reused 294
Receiving objects: 100% (447/447), 66.16 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (217/217), done.
Tapped 5 formulae (20 files, 105.7KB).
➜  ~ 
➜  ~ brew install steampipe
==> Fetching turbot/tap/steampipe
==> Downloading https://github.com/turbot/steampipe/releases/download/v0.17.4/steampipe_darwin_arm64.zip
Already downloaded: /Users/pskrbasu/Library/Caches/Homebrew/downloads/de740a3d8591e9dcb0ce88dc1e73c4ed3af9461f26140205ce35dda90d5a4124--steampipe_darwin_arm64.zip
==> Installing steampipe from turbot/tap
🍺  /opt/homebrew/Cellar/steampipe/0.17.4: 3 files, 39.7MB, built in 2 seconds
==> Running `brew cleanup steampipe`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```
Steampipe does get installed properly for me, without any SHA256 mismatch errors.

As per your recommendation, I also tried
`wget https://github.com/turbot/steampipe/releases/download/v0.17.4/steampipe_darwin_arm64.zip`
```
➜  ~ openssl sha256 ./steampipe_darwin_arm64.zip 
SHA256(./steampipe_darwin_arm64.zip)= ef951e822b6376b6cb825be63a9c15ec0264ea315ddd05aa593c0f47aeade5eb
➜  ~ shasum -a 256 ./steampipe_darwin_arm64.zip 
ef951e822b6376b6cb825be63a9c15ec0264ea315ddd05aa593c0f47aeade5eb  ./steampipe_darwin_arm64.zip
```
which gives me the correct/expected SHA256(ef951e822b6376b6cb825be63a9c15ec0264ea315ddd05aa593c0f47aeade5eb)

So, I'd like to understand more about why you are facing this weird checksum mismatch issue -
- Did you have any previous installations of steampipe via brew?
- Can you untap our tap, and try again, see if you're facing the same issue?
- Can you try `brew install steampipe@0.17.4`, see if you're facing the same issue?

Thanks

**Comment by mgfink** [comment]
Hi @pskrbasu thanks for confirming and sorry for jumping the gun on this.  I tried with a different machine and got the expected results.  I'm not sure if there's some AV software causing the issue but this does appear to be my problem.

Thanks for confirming!
