### ISSUE TITLE
Support WSL on Windows on Arm

### ISSUE THREAD

**Issue by vielmetti** [turbot/steampipe#291]
At the moment, Steampipe does not run on Windows on Arm (my Lenovo Yoga C630 using Ubuntu 20.04 WSL).

Looks like similar to #253 (support M1) for degree of difficulty; registering my interest. A standard linux/arm64 binary should work.

```
emv@iyengar:~/src/github.com/turbot$ steampipe query
Error: x Download & install steampipe-postgres-fdw... FAILED! Invalid Image - Image should contain 1 binary file per platform, found 0
```

**Comment by kaidaguerre** [comment]
Thanks for raising this @vielmetti 

As @e-gineer mentioned on #253 it's not a quick fix but certainly something we will bear in mind as we expand coverage

**Comment by binaek** [comment]
@vielmetti Steampipe is not supported on Windows - but since the time this issue was raised, we have added support for ARM64 across the stack and as such closing this issue as resolved.
