### ISSUE TITLE
Configurable base directory for steampipe configurations

### ISSUE THREAD

**Issue by chenrui333** [turbot/steampipe#2927]
Right now, steampipe assuming the following directories exist for the user to run the plugin installation and query

```
$HOME/.steampipe/config
$HOME/.steampipe/internal
$HOME/.steampipe/plugins
$HOME/.steampipe/db
$HOME/.steampipe/logs
$HOME/.steampipe/db/14.2.0
$HOME/.steampipe/db/14.2.0/data
$HOME/.steampipe/db/14.2.0/postgres
```

It would be good to have a configurable path directory, or maybe a configuration file in general. Thanks!!

**Comment by jchrisfarris** [comment]
Greetings @chenrui333  - the `STEAMPIPE_INSTALL_DIR` environment variable allows you to override the default `$HOME/.steampipe` directory location. 

https://steampipe.io/docs/reference/env-vars/steampipe_install_dir

**Comment by binaek** [comment]
@chenrui333 starting from `v0.17.0` steampipe has a new feature for Workspace Profiles. This was designed to make it easier for users to switch between different steampipe installations in the same system.

Take a look at https://steampipe.io/docs/reference/config-files/workspace
