### ISSUE TITLE
steampipe on homebrew-core?

### ISSUE THREAD

**Issue by muescha** [turbot/steampipe#2929]
**Description**
I see there is a new formula on `homebrew-core`: 

- Web: https://formulae.brew.sh/formula/steampipe#default 
- GitHub: https://github.com/Homebrew/homebrew-core/blob/master/Formula/steampipe.rb

**Official**

Is this an official brew formula now?

**Comment by muescha** [comment]
PR: https://github.com/Homebrew/homebrew-core/pull/118928

**Comment by pskrbasu** [comment]
Thanks to @chenrui333 and @p-linnane for getting our steampipe formula into homebrew-core.

@muescha Let us get back to you on this.

CC @e-gineer @johnsmyth @kaidaguerre

**Comment by muescha** [comment]
I asked because the formula is different to the formula in the tap repo

**Comment by p-linnane** [comment]
Hello 👋 , Homebrew maintainer here. There is no concept of an "official" formula. Anyone is able to add software that uses a free software license. We have requirements for syntax and how formula are written in the main repos, so that probably accounts for differences you may see. Hope this helps!

**Comment by chenrui333** [comment]
> I asked because the formula is different to the formula in the tap repo

IMO, they should be the same, the core tap is just building from the source (which means latest golang)

**Comment by chenrui333** [comment]
Not quite sure why this got marked as a bug (should be technically a question 🤔 )

**Comment by muescha** [comment]
When i created the issue it was automatic marked as a bug 🤷‍♂️

**Comment by kaidaguerre** [comment]
b5f713962a2f12d3ab31e12a008a51cc83059d8c
