### ISSUE TITLE
Dashboard UI crashes with error 'Cannot read properties of undefined (reading 'args')'

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe#2930]
**Describe the bug**
Dashboard UI crashes with error `Cannot read properties of undefined (reading 'args')`

**Steampipe version (`steampipe -v`)**
Example: steampipe version 0.18.0-alpha.30

**To reproduce**
1. Set up the Azure Credential
2. Checkout to below branch 
https://github.com/turbot/steampipe-mod-aws-insights/tree/staging
3. Run steampipe dashboard
4. Click on `Azure SQL Server Detail` page

**Expected behavior**

**Additional context**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/46913995/209656317-7d724fc7-0799-4330-851e-62bff537a357.png">

<img width="961" alt="image" src="https://user-images.githubusercontent.com/46913995/209660331-864ccac0-a2a8-4c9b-a00c-f132da7a0706.png">

**Comment by binaek** [comment]
@khushboo9024 do you have any errors showing up in the CLI console? Can you also include the logs from Chrome Dev Console?

**Comment by khushboo9024** [comment]
@binaek This issue is not throwing any CLI errors and also logs from Chrome Dev are attached if that helps.
