### ISSUE TITLE
Defined exit codes for steampipe commands

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#2935]
Exit codes for steampipe commands:

# Service commands
## `steampipe service restart`

# Query commands
## `steampipe query _`

# Check commands
## `steampipe check`
```
0: no runtime errors, no control alarms or errors
1: no runtime errors, 1 or more control alarms, no control errors
2: no runtime errors, 1 or more control errors
3+: runtime error
```

Refer to community slack thread: 
https://steampipe.slack.com/archives/C01UECB59A7/p1668613929383289

# Plugin commands
## `steampipe plugin update _`

# Mod commands
## `steampipe mod update _`

# Dashboard commands
## `steampipe dashboard`

# Variable command
## `steampipe variable list`

**Comment by binaek** [comment]
Error codes for other steampipe commands:

# Service commands
## `steampipe service start`
## `steampipe service stop`
## `steampipe service restart`

# Query commands
## `steampipe query`
## `steampipe query _`

# Plugin commands
## `steampipe plugin install _`
## `steampipe plugin list`
## `steampipe plugin uninstall _`
## `steampipe plugin update _`

# Mod commands
## `steampipe mod init`
## `steampipe mod install _`
## `steampipe mod list`
## `steampipe mod uninstall _`
## `steampipe mod update _`

# Dashboard commands
## `steampipe dashboard`

# Variable command
## `steampipe variable list`

**Comment by pskrbasu** [comment]
## OLD vs NEW exit codes:

#### OLD
```
ExitCodeSuccessful                   = 0
ExitCodeUnknownErrorPanic            = 1
ExitCodeInsufficientOrWrongArguments = 2
ExitCodeLoadingError                 = 3
ExitCodePluginListFailure            = 4
ExitCodeNoModFile                    = 15
ExitCodeBindPortUnavailable          = 31
```

#### NEW
```
ExitCodeSuccessful                   = 0
ExitCodeControlsAlarm                = 1 // check - no runtime errors, 1 or more control alarms, no control errors
ExitCodeControlsError                = 2 // check - no runtime errors, 1 or more control errors
ExitCodeUnknownErrorPanic            = 3 // check - runtime error
ExitCodeInsufficientOrWrongArguments = 4 // check/plugin - runtime error
ExitCodeLoadingError                 = 3
ExitCodePluginListFailure            = 4
ExitCodeNoModFile                    = 15
ExitCodeBindPortUnavailable          = 31
```
