### ISSUE TITLE
Add support for dynamic updates for dynamic plugin schemas

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#2936]
**Is your feature request related to a problem? Please describe.**
When updating a connection config for a dynamic plugin, the schema is not updated.

**Describe the solution you'd like**
For plugins that have dynamic plugin schemas, when the config is updated, the schemas/tables should be updated as well. This allows plugins like CSV, Google Sheets, Prometheus, Salesforce, and potentially others to update the schemas as the config changes.

**Describe alternatives you've considered**
Restarting Steampipe after making changes.

**Additional context**

**Comment by kaidaguerre** [comment]
fixed by 94b73450b544ea7ec952bd951951ea53a901fd97
