### ISSUE TITLE
if `--progress=false`, the snapshot URL is suppressed

### ISSUE THREAD

**Issue by jchrisfarris** [turbot/steampipe#2954]
**Describe the bug**
When using `--snapshot` with `--progress=false` the URL of the snapshot is not returned. 

**Steampipe version (`steampipe -v`)**
0.17.4

**To reproduce**

```bash
steampipe check all --snapshot-location jcfarris/fooli --snapshot --progress=false 
```
The snapshot is uploaded, however the `Snapshot uploaded to` line is not output. 

**Expected behavior**
The output of the snapshot is probably not really progress like the initialization block that comes before the check output. 

**Additional context**
Testing was done in the context of the `steampipe-mod-terraform-aws-compliance`

**Comment by jchrisfarris** [comment]
Also, I noticed when using `--output json` the `Snapshot uploaded to` line is just appended to the json file making it invalid json.

**Comment by kaidaguerre** [comment]
```
When using --snapshot with --progress=false the URL of the snapshot is not returned.
```
I believe this was a deliberate design decision, will confirm/discuss

```
Also, I noticed when using --output json the Snapshot uploaded to line is just appended to the json file making it invalid json.
```
will fix

**Comment by kaidaguerre** [comment]
```Also, I noticed when using --output json the Snapshot uploaded to line is just appended to the json file making it invalid json.```

So, if you want valid json in a file you could use `--export`: 

```
steampipe check all --snapshot-location jcfarris/fooli --snapshot  --export json 
```

or set `progress=false`: 
```
steampipe check all --snapshot-location jcfarris/fooli --snapshot --progress=false --output json > output.json
```

**Comment by kaidaguerre** [comment]
```
I believe this was a deliberate design decision, will confirm/discuss
```
confirmed - closing this
