### ISSUE TITLE
Update requirements for golang packages with high severity vulnerabilities

### ISSUE THREAD

**Issue by zfLQ2qx2** [turbot/steampipe#2975]
**Is your feature request related to a problem? Please describe.**

Update requirements for golang packages with medium and high severity vulnerabilities and fixes:

github.com/containerd/containerd
golang.org/x/net
github.com/aws/aws-sdk-go
golang.org/x/crypto
golang.org/x/text
github.com/dgrijalva/jwt-go

**Describe the solution you'd like**

Running go get -u to update to go.mod and go.sum files, then go mod tidy to clean up remnants. This mostly solves the problem except that going from github.com/containerd/containerd 1.4 to github.com/containerd/containerd 1.6 seems to have API changes that break the compile. 

**Describe alternatives you've considered**

Usually doing go get -u myself before building takes care of the issue, however some of the dependencies seem to introduce breaking changes in minor updates.

**Additional context**

I use trivy to scan my go binaries for vulnerabilities and it does good job of listing the CVEs associated with each dependency, and tracking which version(s) have the fix for the CVE.

**Comment by pskrbasu** [comment]
Hello @zfLQ2qx2, thank you for the issue.

Yes, we realise updating `github.com/containerd/containerd` raises a problem for which we have created an [issue](https://github.com/turbot/steampipe/issues/3021) to track.
We will update the other packages.

Thanks
