### ISSUE TITLE
autodeploy new versions of steampipe to Homebrew

### ISSUE THREAD

**Issue by sebradloff** [turbot/steampipe#3000]
**Is your feature request related to a problem? Please describe.**
When a new version of steampipe is released, it can not be installed via homebrew. Currently, the docs recommend brew as the installation method on mac.

**Describe the solution you'd like**
It would be great if, upon release, a PR for homebrew could be created with the latest info, so we can upgrade to the latest version.

**Comment by sebradloff** [comment]
@misraved sorry about that. I have too many tabs open 😄

**Comment by misraved** [comment]
No issues @sebradloff 😄.

**Comment by binaek** [comment]
@sebradloff you need to configure the Turbot tap if you want to install with brew. 

https://steampipe.io/downloads explains how to configure the tap.

The following commands should work for you:

`brew tap turbot/tap`
`brew install steampipe`

**Comment by sebradloff** [comment]
@binaek yes I have installed steamipe via the [brew instructions](https://steampipe.io/downloads), however, I can not update to the latest (`v0.18.0`) at this time.

Here's the output from my terminal running `brew upgrade steampipe` showing that it believes `0.17.4` to be the latest:
```
> brew upgrade steampipe
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 7 taps (romkatv/powerlevel10k, spacelift-io/spacelift, homebrew/cask-versions, homebrew/core, homebrew/cask, homebrew/services and mongodb/brew).
==> New Formulae
aws-sam-cli         cdebug              gokey               grayskull           pari-nflistdata     plz-cli
==> New Casks
oka-unarchiver

You have 82 outdated formulae and 4 outdated casks installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Warning: steampipe 0.17.4 already installed
```

**Comment by pskrbasu** [comment]
@sebradloff 
I guess when you try `brew upgrade steampipe`, it is looking into the homebrew-core steampipe available formulae and not our turbot/tap. And the latest formula in homebrew-core is 0.17.4(we still haven't started maintaining the homebrew-core formula).

So can you try `brew install turbot/tap/steampipe` or `brew upgrade turbot/tap/steampipe` which should fetch you the latest 0.18.0 from our turbot/tap which we actively maintain?

Let us know if it solves your problem. Apologies for the hiccup, we will try and get these minor issues sorted ASAP.

Thanks

**Comment by sebradloff** [comment]
@pskrbasu Thank you! Upgrading the tap did fetch the latest (0.18.0) for me.

Happy to leave this open as a feature request to either update the docs to upgrade steampipe via the tap or to start actively maintaining the homebrew core formula.
