### ISSUE TITLE
Using meta commands like .inspect outside steampipe interactive shell

### ISSUE THREAD

**Issue by Shaunak-Pandit** [turbot/steampipe#3025]
### Discussed in https://github.com/turbot/steampipe/discussions/3023

<div type='discussions-op-text'>

<sup>Originally posted by **Shaunak-Pandit** January 21, 2023</sup>
Hi, 

Greetings to all,

I've started this discussion to get ideas on using the steampipe meta commands like .inspect via a python script. Since after entering steampipe query it takes us to the steampipe interactive shell, commands like .inspect need to be manually typed. I was searching for a way to automate this process as I have to run this command for multiple resources.

Expecting replies at the earliest!</div>

**Comment by pskrbasu** [comment]
Hello @Shaunak-Pandit

Currently `.inspect` is a meta-command available only in interactive query mode. 

Take a look at our [STEAMPIPE_INTROSPECTION](https://steampipe.io/docs/reference/env-vars/steampipe_introspection#steampipe_introspection) tables that allow you to query the mod resources in the workspace if it can be of any use to you.

Having meta commands outside the interactive shell requires some work and internal design discussions which are not there in our upcoming release milestones. But we will definitely discuss it internally as a future new feature.

Thanks
