### ISSUE TITLE
Property href is not working in node properties

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe#3026]
**Describe the bug**
```
category "pod" {
  title = "Pod"
  color = local.container_color
  href  = "/kubernetes_insights.dashboard.pod_detail?input.pod_uid={{.properties.'UID' | @uri}}"
  icon  = "view_in_ar"
  property "Namespace" {
    href = "/kubernetes_insights.dashboard.namespace_detail?input.namespace_uid={{.properties.'UID' | @uri}}"
  }
}
```
Here href for the property Namespace is not working in node properties.

**Steampipe version (`steampipe -v`)**
Example: v0.18.1

**Comment by MichaelBurgess** [comment]
Also impacts edges. Strange one as the change was made when we changed fields -> properties, but it's got lost for some reason.
