### ISSUE TITLE
How to: query a different AWS account per request?

### ISSUE THREAD

**Issue by RoxKilly** [turbot/steampipe#3043]
**Is your feature request related to a problem? Please describe.**
I'm running Steampipe as a service, with AWS credentials injected as environment variables.  This works well for inspecting a single AWS account.  I'd like to use Steampipe to inspect infrastructure from different AWS accounts.  Is there a paved path for doing this?

For instance, I would expose an API endpoint that accepts a query request for a specific account, then uses Steampipe to look into that account.  The next request coming to the API might be for a different AWS account, and I'd like Steampipe to handle that as well.  I don't know how to best configure Steampipe correctly to do this since the API just makes a SQL request

**Describe the solution you'd like**
A way to use specific parameters (e.g. aws credentials or regions) per SQL query

**Describe alternatives you've considered**
Considered starting a new service process per AWS account, each with its own env variables.  I expect this will not scale well though, once we get to hundreds of accounts. 

**Additional context**
I'm sure this is a solved problem since I can't be the first to wonder about querying multiple accounts with the same plugin.

**Comment by e-gineer** [comment]
Hey @RoxKilly ... you can definitely query a specific connection or a aggregate of many connections

Hopefully these docs will conver your use case?

https://hub.steampipe.io/plugins/turbot/aws#multi-account-connections

**Comment by RoxKilly** [comment]
Thanks @e-gineer ! I was thinking about it all wrong, trying to figure out how to send creds with the request or set creds in the environment vars, when I should have been thinking about how to set them in the configs.

Appreciate the link.  Enjoy the weekend.
