### ISSUE TITLE
Extend validation for viper config values

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#306]
When `default.spc` loads, we need to check that the values provided are within limits for each property.

Examples (not exhaustive):
`database.port` can only range from `1025` to `65535`
`database.listen` can only be one of `(network | local)`
`terminal.output` can be one of `(json | csv | line | table)`

**Comment by kaidaguerre** [comment]
this is slight related to https://github.com/turbot/steampipe/issues/297

**Comment by kaidaguerre** [comment]
i.e. perhaps we need a generic config validation mechanism - as the config can come from a variety of places bu the same validation must apply

**Comment by kaidaguerre** [comment]
We have now have a validation function, which currently just validates `ArgTelemetry`. This could be extended to validate other as well config
