### ISSUE TITLE
Interactive prompt puts duplicate content on up-arrow after startup

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#3061]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/1114038/216292863-b2ac14d5-b7c4-40ec-8314-9962163ed789.png">

**Comment by binaek** [comment]
Things to test:
* Up arrow immediately after prompt appears
* Up arrow immediately after prompt appears and there's a warning from init
* There should not be an extra newline (prompt) when there's a warning from init
* There should not be a newline when FDW updates during init

**Comment by kaidaguerre** [comment]
@binaek please verify this is not an issue
