### ISSUE TITLE
Add login page to dashboard

### ISSUE THREAD

**Issue by mnacharov** [turbot/steampipe#3068]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a login page out of box. Even if it will be authorization for a single user defined by optional command line arguments

**Describe the solution you'd like**
login page as simple as possible, but with same color scheme as steampipe dashboards have

**Describe alternatives you've considered**
Quite common alternatives are: to put a nginx proxy with authorization before steampipe dashboards and to integrate with [dex](https://dexidp.io/) auth. Both of them are much more difficult

**Additional context**

**Comment by e-gineer** [comment]
Hi @mnacharov ... Our plan for the Steampipe CLI is to keep it simple and focused on a great experience for a single user, so we don't plan to add features like password protection at this point. As you suggest, it can be easily configured with a proxy or similar for password protection if that's your use case.

We do provide [Steampipe Cloud](https://steampipe.io/docs/cloud/overview) as an option for secure collaboration & multi-user scenarios.
