### ISSUE TITLE
graphs are sometimes missing nodes and/or edges, fixed by browser refresh 

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe#3102]
**Describe the bug**
graphs are sometimes missing nodes and/or edges after the dashboard has been fully loaded. A browser refresh fixes it.

**Steampipe version (`steampipe -v`)**
Steampipe v0.19.0-alpha.2

**To reproduce**
This happens intermittently, but seems more frequent in the kubernetes insights mod

**Expected behavior**
graph should render completely

**Additional context**

**Comment by judell** [comment]
@MichaelBurgess I see this frequently with the Mastodon mod as well.

**Comment by MichaelBurgess** [comment]
@kaidaguerre did this one get closed out in the end? IIRC you fixed something for this?
