### ISSUE TITLE
Won't start on NixOS

### ISSUE THREAD

**Issue by kolpav** [turbot/steampipe#3105]
Just letting you know `steampipe` doesn't play nicely with [NixOS](https://nixos.org) I would suspect mainly because of code similar to this

https://github.com/turbot/steampipe/blob/e88d75a692ed6f7fb131bd153d1375a6036d53ef/pkg/db/db_local/locations.go#L104-L109

https://github.com/turbot/steampipe/blob/e88d75a692ed6f7fb131bd153d1375a6036d53ef/pkg/db/db_local/install.go#L194-L203

I am not sure about the fix and I imagine it would also require knowledge of nix to test so feel free to close or if you are interested this is relevant issue https://github.com/NixOS/nixpkgs/issues/215945

**Comment by vielmetti** [comment]
From the cross linked nixpkgs issue, I was able to install this just now, with this report on version:

```
[nix-shell:~/steampipe-environment]$ steampipe --version
Steampipe v0.18.6
```
