### ISSUE TITLE
Can i run steampipe on AWS Lambda? 

### ISSUE THREAD

**Issue by nessa829** [turbot/steampipe#3202]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to use steampipe on AWS lambda. 
I want to use steampipe-mod-aws-tags module and scan periodically resources without mandatory tags. 
I am thinking using cloudwatch event and lambda, but have no idea how to run steampipe on Lambda. 
Can i use lambda layer? or should i use customer docker image (turbot/steampipe) on lambda? 

Eventually i want to run command like 
`steampipe check aws_tags.control.s3_bucket_mandatory --var 'mandatory_tags=["Team", "Service" ]'
`
on lambda. 

**Describe alternatives you've considered**

**Additional context**

**Comment by pskrbasu** [comment]
Hi @nessa829,

We have never tried running Steampipe on AWS Lambda. It might be possible, but we haven't had the opportunity to try it out yet and neither have we seen any of our users from our community use it on Lambda.
You can try it out and reach out to us in [Slack](https://steampipe.io/community/join) if you need any input. We and our community members would be more than eager and happy to help you out.

You can try running on AWS ECS using our docker image(turbot/steampipe) following our [Using containers](https://steampipe.io/docs/managing/containers) docs, many of our users use it this way.

Also, you can try using [Steampipe Cloud](https://steampipe.io/docs/cloud/overview). I suppose you could call directly to the Postgres endpoint or the Rest API from your Lambda function.

Thanks

**Comment by judell** [comment]
@nessa829 it looks like @pdecat is making progress on figuring it out: https://steampipe.slack.com/archives/C044P668806/p1678276529588729?thread_ts=1678276449.798679&cid=C044P668806

**Comment by pdecat** [comment]
Hi, I can confirm I made Steampipe work in Lambda deploying as [container image](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-images.html), with a custom PostgreSQL build to disable system dependencies like `shm_open` and `prctl` not available in Lambda, and [this change](https://github.com/turbot/steampipe/pull/3200) to use `127.0.0.1` instead of `localhost` to avoid issues with resolution randomly returning `::1` as IPv6 is not available either.
Details are in the Slack thread mentioned by @judell.
 
> Can i use lambda layer?

Great idea! Packaging Steampipe as a ready to use Lambda layer would definitely be an option, way easier for users.

**Comment by pdecat** [comment]
> You can try running on AWS ECS using our docker image(turbot/steampipe) following our [Using containers](https://steampipe.io/docs/managing/containers) docs, many of our users use it this way.

FWIW, I am still running Steampipe with AWS Batch on Fargate right now, but Batch jobs have a ~60s delay on startup which for scanning hundreds of AWS accounts and Azure subscriptions is not desirable. That's one of the reason I'm looking into switching our process to Lambda.

**Comment by nessa829** [comment]
thank you for the reply. However i do not want that much of customization, so i am now again looking into using container (on EKS). I look forward to new feature release for lambda!!

**Comment by massyn** [comment]
My experience on this was that as soon as you add volume, you run into disk i/o issues. Postgres is very disk hungry, and Lambda and ECS are not very generous on the disk.  So watch out for that - it won't scale very well, unless you start running multiple lambda invocations.
