### ISSUE TITLE
feature: Kubernetes plugin

### ISSUE THREAD

**Issue by vielmetti** [turbot/steampipe#322]
**Is your feature request related to a problem? Please describe.**

Lots of people have written scripts to query Kubernetes (and also
the various managed Kubernetes services) to keep track of resources
in an ad hoc way.

**Describe the solution you'd like**

Eventually, a Kubernetes plugin, which would 
support a generic installation and let you do
interactive queries and generate reports etc.

**Describe alternatives you've considered**

The closest thing that comes to mind is `kubectl get`, documented at
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get

**Additional context**

Prompted by @mckartha

**Comment by kaidaguerre** [comment]
thanks for the suggestion @vielmetti!

we do now have a kubernetes plugin under development: https://github.com/turbot/steampipe-plugin-kubernetes
