### ISSUE TITLE
Update useDashboardWebSocket to consider url.pathname

### ISSUE THREAD

**Issue by oguzhanakan0** [turbot/steampipe#3227]
# Problem
I'm trying to serve Steampipe dashboard under `<myhost>/steampipe`. This is causing a websocket connection failure error because it assumes my websocket server is in root (eg `wss://<myhost>/ws`), which fails eventually.

## Error
```
main.e5f5fea6.js:2 WebSocket connection to 'wss://<myhost>/ws' failed: 
t.createOrJoinSocket @ main.e5f5fea6.js:2
....
VM94 react_devtools_backend.js:2655 Max reconnect attempts of 10 exceeded
```

## Solution suggestion
I assume updating [useDashboardWebSocket.ts#L45](https://github.com/turbot/steampipe/blob/240041a0064f16e558a1aea4dcf9527e044dfdee/ui/dashboard/src/hooks/useDashboardWebSocket.ts#L45) with 
```
return `${url.protocol === "https:" ? "wss" : "ws"}://${url.host}${url.pathname=="/"?"":url.pathname}/ws`;
```
would do the trick. I am not aware of any potential side effects though.

**Comment by e-gineer** [comment]
Interesting catch @oguzhanakan0 ... have you tried making the change? We'd be open to a PR for this if you have a chance to try and test it.

**Comment by MichaelBurgess** [comment]
@oguzhanakan0 I don't see there'd be any real side-effect from this.

I'm happy to review this if you're OK to raise a PR as @e-gineer suggested.

**Comment by oguzhanakan0** [comment]
Thanks for your comments, will raise a PR this week.

**Comment by ajoga** [comment]
Hey, i'm giving a +1 to this issue to remove the stale label :)

I'm trying to serve it through a reverse proxy that will serve the dashboard at hostname.tld/somepath, and all assets seems to be absolutely linked with href="/asset" (js files, css..) so the dashboard does not load at all:

![image](https://github.com/turbot/steampipe/assets/37543966/68d9ca68-960a-4d3b-8412-9299d233286f)
