### ISSUE TITLE
Metabase query plugin

### ISSUE THREAD

**Issue by d416** [turbot/steampipe#3245]
**Is your feature request related to a problem? Please describe.**
Metabase is a popular query-sharing analytics platform which has built in features for data governance and visualizations. It would be nice to be able to access these data sets through Steampipe in other applications. 

**Describe the solution you'd like**
Please consider providing a plugin to read from Metabase. Having a plugin to query Metabase would instantly open up the datasets stored in Metabase to use with other data win Steampipe.  Here is the overview of the Metabase API https://www.metabase.com/learn/administration/metabase-api

**Describe alternatives you've considered**
We use Metabase, PowerBI and Tableau software at work extensively. Data sets can be exchanged between Tableau and PowerBI, but it usually involves exporting to a .csv from one and importing it into another. Metabase is a good common denominator for maintaining data that is accessible to the other BI tools, but there is no standard way (ODBC/JDBC) of connecting to Metabase, and BI tool vendors  would probably never release a connector to other BI tools.

**Additional context**
SQL developers like Metabase because data queries can be instantly visualized with little effort. In other tools like Tableau or Superset, you need to define define each dataset in a data model first, then go to the designer to incorporate that into a visualization.  A great enterprise data workflow would be to use Metabase to manage all your base queries with access controls, then use your BI tool of choice to connect to these queries via Steampipe.

Side Benefit:  In addition to querying, data sources can be set up through the API, so you can even set up data source within Metabase to a Steampipe instance, all orchestrated from within Steampipe. How cool would that be in a demo?

Note: Metabase is in the same space as other BI tools like Tableau, PowerBI, Apache Superset, and Looker. Each one has their own way of dealing with data sets and governance including access controls.  This is one of the main things that locks in an enterprise to one of these tools.  Having plugins for these BI tools would allow customers to avoid vendor lock-in, and can even have multiple BI tools installed, each tool connecting to each others' data sets via Steampipe! For example, here is the Tableau REST API which would also make for a great plugin: https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api.htm

**Comment by judell** [comment]
@d416 Steampipe can already connect to Metabase, PowerBI, and Tableau: https://steampipe.io/docs/cloud/integrations/overview 

Can you say more about how these plugins would enhance those existing integrations?

**Comment by d416** [comment]
I can speak to our particular use case which I'm sure applies to a lot of large enterprises, and perhaps even small ones.  I'll use Tableau as an example because it's the largest in our case, but the same would apply to Metabase and PowerBI


Tableau has a large number of data connectors (they call these 'data sources') which can be used to design a data pipeline within Tableau to aggregate desperate data into usable data sets (they call these 'data extracts' that can be used in Tableau dashboard designs.  These data sets are curated and security controls applied so that only specific groups of users can see the data sets.   Tableau keeps track of user authentication, access control groups,  and a mapping between this and the data sets.

So in Tableau you can pull data from a Postgres db, mash it up with some data from Azure db and maybe Salesforce, store it all into a single data set, then grant access to who needs to see it.

The problem now is that data set that was so lovingly curated now only exists in Tableau.  The only way to get to it is through the Tableau API.

Steampipe is great for doing basically the same thing as above given the 100+ data plugins, but in this particular scenario all of the above would need to be re-created in Steampipe.  So why not just query the Tableau API to gain access to those data sets?  Not only can the Steampipe plugin library be leveraged (some of the same connectors in Tableau are awful btw), this would effectively give an ODBC view into Tableau which I don't believe exists today.

My feature request is for Metabase as this meets an immediate need, but same concept:  Data sets are called "questions" and access to these can be restricted based on user profile.  Metabase has a REST api that can be used to retrieved these already-curated data sets.  

hope this helps
