### ISSUE TITLE
AWS Lambda resolves `localhost` to `IPv4` and `IPv6` randomly

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#3264]

**Comment by pdecat** [comment]
As mentioned in https://github.com/turbot/steampipe/issues/2377#issuecomment-1458969327, this happens not only on Lambda but on other platforms too.

What's true about Lambda, is that IPv6 is unavailable for use, and that `localhost` can resolve to `[::1]` (IPv6) there, causing errors, e.g.:
```
2023/03/08/[$LATEST]c11afd1a70f9481584605c1fda30fd51 2023-03-08 17:32:22.324 UTC [TRACE] steampipe: Trying to create maintenance client with:  host=localhost port=9193 user=root dbname=postgres sslmode=disable
2023-03-08T17:32:22.326000+00:00 2023/03/08/[$LATEST]c11afd1a70f9481584605c1fda30fd51 2023-03-08 17:32:22.326 UTC [TRACE] steampipe: could not connect: failed to connect to `host=localhost user=root database=postgres`: dial error (dial tcp [::1]:9193: socket: address family not supported by protocol)
```

For more details, see comments in this Slack thread: https://steampipe.slack.com/archives/C044P668806/p1678297205414189?thread_ts=1678276449.798679&cid=C044P668806

**Comment by binaek** [comment]
Alternate approach in #3200
