### ISSUE TITLE
Steampipe commands like `dashboard` and `check` should raise warning if a dependent mod's `require` section is not satisfied

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#3276]
**Describe the bug**
If I have mod A that has mod B as a dependency, and mod B has a CLI and/or plugin requirement that my env doesn't meet, I can still run `steampipe dashboard` and `steampipe check all` in mod A's directory and Steampipe will start/run.

**Steampipe version (`steampipe -v`)**
v0.19.3

**To reproduce**
See description above

**Expected behavior**
Steampipe should not finish initializing and tell me why, similar to if my direct mod's `require` section isn't satisfied

**Additional context**

**Comment by binaek** [comment]
Closed by #3334
