### ISSUE TITLE
Cannot add newline to historic or pasted query, event when multiline mode is ON

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#328]
**Describe the bug**

 If I do .multi on and then use my history or paste to create a multiline query, I'm finding that I cannot add an extra line to it? When I click return to add the line (in the middle) it just executes the query. (It does work as expected if I start typing a new query by hand.)

**Steampipe version (`steampipe -v`)**
v0.3.0

**To reproduce**
as above

**Expected behavior**
A newline should be added

**Additional context**

**Comment by pskrbasu** [comment]
Works in v0.20.5
