### ISSUE TITLE
Steampipe suddenly stopped working with message "unrecognized remote plugin message"

### ISSUE THREAD

**Issue by farzadmf** [turbot/steampipe#3297]
**Describe the bug**
Steampipe was working fine for me, and now it's failing with the following message:
```
⠋ Fetching connection map2023-04-03 19:17:44.016 UTC [WARN]  steampipe: plugin manager start() failed to start GRPC client for plugin manager: Unrecognized remote plugin message:
This usually means
  the plugin was not compiled for this architecture,
  the plugin is missing dynamic-link libraries necessary to run,
  the plugin is not executable by this process due to file permissions, or
  the plugin failed to negotiate the initial go-plugin protocol handshake

Additional notes about plugin:
  Path: /home/linuxbrew/.linuxbrew/Cellar/steampipe/0.19.3/bin/steampipe
  Mode: -r-xr-xr-x
  Owner: 21406620 [farzadmf] (current: 21406620 [farzadmf])
  Group: 100 [amazon] (current: 100 [amazon])
  ELF architecture: EM_X86_64 (current architecture: amd64)
2023-04-03 19:17:44.016 UTC [WARN]  steampipe: StartServices plugin manager failed to start: Unrecognized remote plugin message:
This usually means
  the plugin was not compiled for this architecture,
  the plugin is missing dynamic-link libraries necessary to run,
  the plugin is not executable by this process due to file permissions, or
  the plugin failed to negotiate the initial go-plugin protocol handshake

Additional notes about plugin:
  Path: /home/linuxbrew/.linuxbrew/Cellar/steampipe/0.19.3/bin/steampipe
  Mode: -r-xr-xr-x
  Owner: 21406620 [farzadmf] (current: 21406620 [farzadmf])
  Group: 100 [amazon] (current: 100 [amazon])
  ELF architecture: EM_X86_64 (current architecture: amd64)
Error: plugin listing failed - Unrecognized remote plugin message:
This usually means
  the plugin was not compiled for this architecture,
  the plugin is missing dynamic-link libraries necessary to run,
  the plugin is not executable by this process due to file permissions, or
  the plugin failed to negotiate the initial go-plugin protocol handshake

Additional notes about plugin:
  Path: /home/linuxbrew/.linuxbrew/Cellar/steampipe/0.19.3/bin/steampipe
  Mode: -r-xr-xr-x
  Owner: 21406620 [farzadmf] (current: 21406620 [farzadmf])
  Group: 100 [amazon] (current: 100 [amazon])
  ELF architecture: EM_X86_64 (current architecture: amd64)

```

**Steampipe version (`steampipe -v`)**
Steampipe v0.19.3

**To reproduce**
Run `steampipe plugin list` and see the error message

**Expected behavior**
Steampipe should continue working as it was before.

**Additional context**
Honestly, no idea what happened. I was using it, and just suddenly stopped breaking.

Tried removing the `~/.stempipe` folder, removing and reinstalling the plugin(s), but nothing seems to be working.

At first, I thought it's an issue with the `aws` plugin, but, as I mentioned, doing a simple `steampipe plugin list` would result in the error message!

**Comment by e-gineer** [comment]
hmmm ... seems like it's managed to get a plugin version for the wrong architecture downloaded?

Which plugins are you using? What OS version / architecture are you running on?

If you rm the `~/.steampipe` directory and do a plugin list before installing any of them, does that work?

**Comment by farzadmf** [comment]
> What OS version / architecture are you running on?

I'm on Amazon Linux (EC2), and everything was working fine 🙁

> If you rm the `~/.steampipe` directory and do a plugin list before installing any of them, does that work?

So, when I `rm -rf ~/.steampipe`, and I just do a `steampipe plugin list`, I see message about installing embedded PostGres etc., and then it gives me this error:
```
Error: plugin listing failed - cannot listen on port 9193
```

**Comment by e-gineer** [comment]
If you do a `ps aux | grep steampipe` do you have any steampipe processes stuck / running in the background? Sounds like the port is already in use for some reason?

**Comment by farzadmf** [comment]
Hey @e-gineer, I just forgot that there was an issue and "resumed my old life" (which means depending on `steampipe` for all the things), and things are working now.

Since I heavily rely on `steampipe` to do my things, if it doesn't work, it basically breaks my WHOLE FLOW of things. Maybe, as you mentioned, it was an already existing process.

Because I've noticed issues when a process is already running, where a new instance would use the existing process's credentials (not sure if it's by design or not), and maybe this was the same issue.

It would be nice if the `steampipe` CLI would have some debugging features (like verbose logs and alike) for these kinds of situations, because, TBH, the situation was super scary to me (as I mentioned since I'm heavily relying on `steampipe` for my day-to-day cloud tasks)
