### ISSUE TITLE
Update Docker publish workflow to push to ghcr only

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#3327]
v0.21.x will be the last version we publish to Docker Hub. Update Docker publish workflow to stop publishing to dockerhub just before v0.22.0 comes out.

Update turbot/steampipe Docker repository description in docker hub.
![Screenshot 2024-02-15 at 7 17 20 PM](https://github.com/turbot/steampipe/assets/45908484/5f3a9f8a-f293-45c6-8812-63fffc47de1a)

**Comment by kaidaguerre** [comment]
@pskrbasu can you check if this is still needed
