### ISSUE TITLE
Cloning large number of connections result in `out of shared memory (SQLSTATE 53200)` error

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#3333]
**Steps to reproduce:**
- create 1000 connections
- run steampipe query
- steampipe gets stalled for quite a long time showing `⠋ Cloned 1000 of 1000 connections`
- throws `Error: out of shared memory (SQLSTATE 53200)`

**Comment by kaidaguerre** [comment]
not observed in v0.20.0
