### ISSUE TITLE
Message when cancelling mod list command is misleading

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#3352]
**Describe the bug**
```
cbruno@M1P mods % steampipe mod list
Warning: You're in a directory with a lot of files or subdirectories (>10 files that are not .sql or .sp). It's recommended to create a new directory and run steampipe mod list from there.
Do you want to continue? (y/n)
n
Error: Mod installation cancelled
```

**Steampipe version (`steampipe -v`)**
v0.20.0-alpha.5

**To reproduce**
See above

**Expected behavior**
The message should not mention mod installation since I'm listing

**Additional context**

**Comment by pskrbasu** [comment]
Fixed in https://github.com/turbot/steampipe/pull/3354
