### ISSUE TITLE
Can we have all the options selected by default in a multiselect input in dashboards?

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe#3361]
**Is your feature request related to a problem? Please describe.**
We want to select all options by default in a `multiselect` input for a dashboard. 
It would be great if we could add this feature for dashboard.

**Describe the solution you'd like**
For wellarchitected mod we want to select all child resource(Lens) with parent workload in a `multiselect` input by default, but as of now this feature is not supported by steampipe.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Akaame** [comment]
I have started working on this. How do I test it with `aws_well_architected`?

**Comment by pskrbasu** [comment]
Apologies @Akaame for the late response 🙏. Thank you for picking up this issue.

You can test it with our `steampipe-mod-aws-well-architected` by cloning the repo https://github.com/turbot/steampipe-mod-aws-well-architected and following the [Getting started](https://github.com/turbot/steampipe-mod-aws-well-architected#getting-started) guide.

Please let us know if you need any help developing or testing it.

Thanks again!

**Comment by pskrbasu** [comment]
@Akaame You mentioned, you started working on this. Did you get anywhere with this? Do you need any assistance from us?
