### ISSUE TITLE
Allow dashboard service startup timeout to be specified as an environment variabled 

### ISSUE THREAD

**Issue by taliesins** [turbot/steampipe#3369]
**Describe the bug**
When running the dashboard in a container with a couple of mods (all the aws and kubernetes ones) it will very often time out with message `Error: dashboard server startup timed out`.

**Steampipe version (`steampipe -v`)**
Example: v0.19.4

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

Steps to install in container:
```
# Use a constant workspace directory that can be mounted to
WORKDIR /workspace

# create a workdir for all mods
RUN mkdir -p /workspace/mods

# disable auto-update
ENV STEAMPIPE_UPDATE_CHECK=false

# disable telemetry
ENV STEAMPIPE_TELEMETRY=none

# Run steampipe service once and stop it
RUN cd /workspace/mods && \
    steampipe service start --dashboard && \
    steampipe service stop --force && \ 
    rm -f /home/steampipe/.steampipe/internal/.passwd

# Install all plugin and mods
RUN cd /workspace/mods && \
    steampipe plugin install steampipe terraform aws kubernetes && \
    steampipe mod install github.com/turbot/steampipe-mod-aws-compliance && \
    steampipe mod install github.com/turbot/steampipe-mod-aws-insights && \
    steampipe mod install github.com/turbot/steampipe-mod-aws-perimeter && \
    steampipe mod install github.com/turbot/steampipe-mod-aws-tags && \
    steampipe mod install github.com/turbot/steampipe-mod-aws-thrifty && \
    steampipe mod install github.com/turbot/steampipe-mod-kubernetes-insights && \
    steampipe mod install github.com/turbot/steampipe-mod-kubernetes-compliance
```
Entrypoint:
```
steampipe service start --dashboard-listen=network --database-port=5432 --dashboard-port=9194 --dashboard --foreground
```

**Expected behavior**
Should be able to specify the dashboard timeout as an environment variable (consider doing this for the other hard coded values for timeouts as well) for people that want to show a lot on the dashboards.

**Additional context**
I believe that this is the same issue as #2434. I think that the timeout vaules should rather be read from environment variables and default to the values in the code if they are not specified. Forcing a hard coded timeout I think is the issue.

**Comment by binaek** [comment]
> @binaek @kaidaguerre although the issue is closed, the same error happens and it seems that STEAMPIPE_DASHBOARD_START_TIMEOUT environment variable is not honored because when starting steampipe service without the dashboard, the service loads up. otherwise, it fails.

Hi @electriquo, as far as I can recall, the dashboard startup timeout feature is slated to be released in `0.21`. I believe it's not present in the `0.20.x` releases. Which version are you working off of?
