### ISSUE TITLE
Schema names starting with `sp_` are to be reserved for steampipe

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#3402]
* Connection names cannot be named `public` and cannot start with `sp_` 
* If such connection names are detected
    * Show a warning during config loading and parsing
    * Do not load the connection during schema refresh and set the connection to `ERROR` in `connection_state`

**Comment by kaidaguerre** [comment]
fixed by 7703975883d0ede9aad2e56da52f0502d3e571d7
