### ISSUE TITLE
Dynamic Configuration before query

### ISSUE THREAD

**Issue by astro44** [turbot/steampipe#349]
**Is your feature request related to a problem? Please describe.**
As briefly discussed in #226 looking to also have a feature where configuration files can be added and referenced at/before run/query time...  the idea is that upon each new request we want to be able to write the config files for different accounts dynamically before making the query. (*we do realize  that cache wont help here but thats ok)

**Describe the solution you'd like**
as mentioned by @e-gineer  "steampipe --config-dir /path/to/my/configs", with dir containing config files, and allow queries like: select * from config001.aws_s3_bucket

**Comment by e-gineer** [comment]
Hey @astro44 ... thanks for the question and ongoing feedback on Steampipe!

We support changing the location of the installation, including config files, like with [--install-dir](https://steampipe.io/docs/reference/cli-args#global-flags). For example:
```
steampipe --install-dir /path/to/a query
```

You can have multiple installation directories, with different configuration directories in each. Would that solve your problem?
```
steampipe --install-dir /path/to/a query "select * from aws_iam_user"
steampipe --install-dir /path/to/b query "select * from aws_iam_user"
```

If you have many AWS accounts you now set those up as [different connections / schemas](https://steampipe.io/docs/reference/config-files) through the config files. So then you can do `steampipe query` and run queries like:
```
select * from config001.aws_s3_bucket
select * from config002.aws_s3_bucket

-- default search_path is alphabetical, so this uses config001
select * from aws_s3_bucket
```

It's manual right now, but you can also choose to change the postgres `search_path` within a session, so you could do:
```
-- reverse the search path order
set search_path to config002,config001
```

Do those features cover your request? Or do you have something different in mind?

**Comment by astro44** [comment]
Understood, the other challenge is around all "writes"/"cache" that occur during an --install-dir or query.
is it possible to have those outputs set to a different directory? 
and/or in some cases like caching turn it off?
especially if the user has limited access to specific directories after the initial install.

**Comment by astro44** [comment]
@e-gineer is "export STEAMPIPE_CACHE=false" the only option for reducing local writes(I/O) so far? or are there other options in the works?
thanks again!

**Comment by e-gineer** [comment]
@astro44 All of the writes go to the `--install-dir` (logs, database, config files, etc). We don't write to any other directory or location. The cache itself is actually in memory, so you can leave it on if you prefer. I believe setting the `--install-dir` should cover what you need, but am happy to discuss further if you can offer more details on the issue you are seeing.

**Comment by kaidaguerre** [comment]
@astro44 If you can spare a few minutes at some point, I'd love to have a chat to better understand your steampipe usage and requirements. 

If you are good with this, please drop me a line at kai at turbot dot com and we can arrange something.

**Comment by astro44** [comment]
@e-gineer thanks for the fast feedback... looking for a way to split into:
-  core --> SteamPipe + Postgress + plugins in a restricted directory (*no writes) this is installed in the docker container
-  outputs/configs --> Configs + Logs + Other writes to a defined directory (dont know if --install-dir would still be feasable)

**Comment by e-gineer** [comment]
So the primary goal you have is to run steampipe from a docker container where the setup is pre-installed / pre-built (e.g. database + plugins), but the configuration (e.g. connections) and output (e.g. logs) is separate per run?

If so, then I see that `--install-dir` is only a partial solution because it pulls all of those items outside the pre-built docker container?

**Comment by astro44** [comment]
@e-gineer thats correct.

**Comment by e-gineer** [comment]
This definitely makes sense as a best practice setup of steampipe for a read-only docker container. We will give that more thought, likely as part of a larger "how should steampipe be configured in docker" discussion.

Suggested workarounds for now are:

1. Just use `--install-dir`. It's not optimal, but it moves all the writable pieces out of the docker file system with a simple setting.

2. Try mounting each directory in `./steampipe` separately, except for the plugins directory. That moves each of the writable dirs (config, db, internal, logs) out of your docker file system, while allowing the `plugins` one to be setup in advance. A bit fiddly, but should work. (Disclaimer - We have not tested this, please let us know how you go.)
