### ISSUE TITLE
Installation inconsistency when specifying a Git tag

### ISSUE THREAD

**Issue by foolioo** [turbot/steampipe#3513]
**Describe the bug**
When specifying the (Git) tag, e.g. [`v0.104.0`](https://github.com/turbot/steampipe-plugin-aws/tree/v0.104.0), the installation fails. Where this is not the case when using the same tag without the `v` prefix, e.g. `0.104.0`.

This cause many update managers that track Git for new tags and updates Steampipe accordingly.

**Steampipe version (`steampipe -v`)**
```shell
$ steampipe --version
Steampipe v0.20.5
```

**To reproduce**
```shell
$ steampipe plugin install aws@v0.104.0

aws@v0.104.0                   [====================================================================] Not found

Skipped the following plugin:

Plugin:   aws@v0.104.0
Reason:   Not found

$ steampipe plugin install aws@0.104.0

aws@0.104.0                    [====================================================================] Done

Installed plugin: aws@0.104.0 v0.104.0
Documentation:    https://hub.steampipe.io/plugins/turbot/aws
````

**Expected behavior**
Both `steampipe plugin install aws@v0.104.0` and `steampipe plugin install aws@0.104.0` should install the plugin without any errors.

**Additional context**
The issue results in inconsistent experience through Steampipe, since this is not the case for modules
```shell
$ steampipe mod install github.com/turbot/steampipe-mod-aws-insights@v0.12.0

Installed 1 mod:

local
└── github.com/turbot/steampipe-mod-aws-insights@v0.12.0
```

**Comment by kaidaguerre** [comment]
I agree, seems reasonable to be forgiving about the formats we accept. We'll take a look
