### ISSUE TITLE
CLI does not support .inputrc in query mode

### ISSUE THREAD

**Issue by beacomni** [turbot/steampipe#352]
After typing `steampipe query` and entering query mode, the interactive CLI shell does not respect the vi mode setting in my .inputrc file.

It sounds like the postgres CLI does respect .inputrc
https://www.reddit.com/r/PostgreSQL/comments/2w1tjj/you_can_use_vi_mode_editing_in_psql/
Would be very useful to have similar behavior, as I'm accustomed to vi mode in the shell rather than emacs-style bindings.

The priority on this may be lowered by using service mode and connecting with postgres client!

**Comment by e-gineer** [comment]
Honestly @beacomni ... you just blew my mind. I use vi all the time and had absolutely no idea it could do this inside psql etc! Wow!!

It's interesting to see the benefits of leaning more and more into `readline` as the basis for our shell. @kaidaguerre and @binaek89 will be interested in this as it may bring other benefits like Ctrl-R etc.

FWIW, you can use the postgres client with steampipe ... here is how I do it:

```
~ $ steampipe service start

Steampipe database service is now running:

  Host(s):  localhost, 127.0.0.1, 192.168.7.220
  Port:     9193
  Database: steampipe
  User:     steampipe
  Password: 91f0-47f8-EXAMPLE

Connection string:

  postgres://steampipe:91f0-47f8-EXAMPLE@localhost:9193/steampipe?sslmode=disable

Steampipe service is running in the background.

  # Get status of the service
  steampipe service status
  
  # Restart the service
  steampipe service restart

  # Stop the service
  steampipe service stop

~ $ psql postgres://steampipe:91f0-47f8-EXAMPLE@localhost:9193/steampipe?sslmode=disable
psql (12.4, server 12.1)
Type "help" for help.

steampipe=> -- I am in vi mode now I understand ~/.inputrc & ~/.editrc!
steampipe=> \q
~ $ 
```

**Comment by kaidaguerre** [comment]
@beacomni yes very interesting - we'll look into what is required to implement this within the steampipe cli

**Comment by beacomni** [comment]
Thanks for taking a look and for the rapid reply - I think using the psql client or other clients can be a nice workaround - thanks for implementing the service mode 👍
