### ISSUE TITLE
Temporary table disappears after a few minutes

### ISSUE THREAD

**Issue by jacksgt** [turbot/steampipe#3539]
Hello,
first of all a huge shout out to the authors for this amazing tool!

## Description

I created a [temporary postgresql table](https://www.postgresql.org/docs/current/sql-createtableas.html) as follows (the query itself does not matter that much, the first line is the interesting part):

```sql
> CREATE TEMPORARY TABLE my_namespaces AS (SELECT name,namespace
FROM kubernetes_pod
WHERE EXISTS (
          SELECT TRUE 
          FROM jsonb_array_elements(volumes) x 
          WHERE x->'persistentVolumeClaim'->>'claimName' IN (
                    SELECT DISTINCT name
                    FROM kubernetes_persistent_volume_claim
                    WHERE storage_class LIKE 'cvmfs%'
          )
));
```

The table is populated correctly:

```
> SELECT * FROM my_namespaces;
+----------------------------+----------------+
| name                       | namespace      |
+----------------------------+----------------+
| httpd-7878f84494-w5bwf     | test-paas-stg2 |
| server-dc-1-m9gxb          | test-foobar    |
| server-dc-1-p8zkr          | test-foobar    |
+----------------------------+----------------+
```

I can run the above command multiple times in a row and it returns data.
However, after a 2-3 minutes I get:

```
SELECT * FROM my_namespaces;
Error: relation "my_namespaces" does not exist (SQLSTATE 42P01)
```

### Steampipe version

```
steampipe -v
Steampipe v0.20.3
```

### Steps to reproduce

*see above*

### Expected behavior

The temporary table stays available until I exit the interactive session (Ctrl-C / Ctrl-D).

The [postgres documentation about temporary tables](https://www.postgresql.org/docs/current/sql-createtable.html) says:

> TEMPORARY or TEMP:
> If specified, the table is created as a temporary table. Temporary tables are automatically dropped at the end of a session, or optionally at the end of the current transaction (see ON COMMIT below). 

### Additional context

Creating temporary tables is super useful (IMO) because it allows easier access to complex data structures and has the benefit of caching computationally expensive results.

**Comment by jacksgt** [comment]
Hi,
thanks for the quick reply.
Do I understand correctly that the entire DB is dropped at the end of each session?
In that case a "regular" table actually serves the same purpose as a temporary table (as far as I can tell).

**Comment by binaek** [comment]
@jacksgt As far as I can tell, postgresql `temporary` tables are scope to sessions (database connections)

Steampipe uses a `connection pool` to connect to the database. We try to reuse connections as much as possible, but  connections get dropped and recreated periodically. This is to prevent and recover from situations where connections may get stuck in unstable states.

I found the section on `TEMPORARY` tables in the https://www.postgresql.org/docs/14/sql-createtable.html document helpful.

**Comment by binaek** [comment]
As @judell suggested, using the `public` schema is the advisable route here. The DB, once created, is never dropped (unless the `data` directory is removed).

We enable and keep the `public` schema writable for exactly the kind of use case you are looking for (take point-in-time snapshot of data)

We also setup the `search_path` in a way so that the `public` schema is always first, by default. So a `CREATE TABLE` will create tables in the `public` schema.

Can you try with this:
```
CREATE TABLE my_namespaces AS (SELECT name,namespace
FROM kubernetes_pod
WHERE EXISTS (
          SELECT TRUE 
          FROM jsonb_array_elements(volumes) x 
          WHERE x->'persistentVolumeClaim'->>'claimName' IN (
                    SELECT DISTINCT name
                    FROM kubernetes_persistent_volume_claim
                    WHERE storage_class LIKE 'cvmfs%'
          )
));
```
and see if that solves your problem?

**Comment by jacksgt** [comment]
Hi again,
I can confirm that `CREATE TABLE foobar` (without `TEMPORARY`) does not loose the table after a while.
But it also persists the table after restarting the steampipe - which is not the desired result.

```
$ steampipe query
> CREATE TABLE foobar AS (...);
> SELECT COUNT(*) FROM foobar;
+-------+
| count |
+-------+
| 111   |
+-------+
Ctrl-c 

$ steampipe query
> SELECT COUNT(*) FROM foobar;
+-------+
| count |
+-------+
| 111   |
+-------+
```

But I would like to automatically "drop" the table when I end the (interactive) session.

Regarding this:

> As far as I can tell, postgresql temporary tables are scope to sessions (database connections).
> Steampipe uses a connection pool to connect to the database. We try to reuse connections as much as possible, but connections get dropped and recreated periodically. This is to prevent and recover from situations where connections may get stuck in unstable states.

Temporary tables are tied to an authenticated session, not an individual connection from a connection pool - otherwise no application that uses connection pooling could ever use temporary tables.
So I believe something else must be going on.

**Comment by binaek** [comment]
@jacksgt It looks like `public` schema will not solve what you are after.

I have opened up an issue at https://github.com/turbot/steampipe/issues/3543 which should solve your problem once merged.

**Comment by binaek** [comment]
Closed by https://github.com/turbot/steampipe/issues/3634
