### ISSUE TITLE
JSON output comparison tests should use JSONDiff tools instead of `assert_equal` checks

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#3556]
Update all JSON output tests to use JSONDiff tool `jd --patch`

**Comment by Mr-Destructive** [comment]
I have tried to check the output with jd, but it shouldn't use `jd -p` right? Beacuase that will be used to apply the diff to another file, right? Or is there another use case for that command. Let me know if it is correct or not.

This is an example that I have tested locally

```bash
@test "plugin list - output json" {
  export STEAMPIPE_DISPLAY_WIDTH=100
  tmpdir="$(mktemp -d)"
  steampipe plugin install hackernews@0.6.0 bitbucket@0.3.1 --progress=false --install-dir $tmpdir

  steampipe plugin list --install-dir $tmpdir --output json > output.json
  
  # compare the two files
  run jd $TEST_DATA_DIR/expected_plugin_list_json.json output.json
  assert_success

  rm output.json
  rm -rf $tmpdir
}

```
Is this the pattern I could replicate in the relevant places?

Thank you.

**Comment by pskrbasu** [comment]
Hi @Mr-Destructive,

Our idea behind using `jd` in our JSON comparison tests is that JSON is not ordered, so just checking the file's contents using assert_equal might lead to files not being equal because of the ordering. By using jd, we don't need to worry about that.

We used `jd -f patch` previously in some of our tests([here](https://github.com/turbot/steampipe/blob/0fd4deb161334cb8eec933a85a48ce0c8c958b7b/tests/acceptance/test_files/dashboard.bats)) because while comparing our JSON snapshots, we needed to ignore the `created_at` and other timestamp related properties while comparing the files, that's why we created the patch file to examine(using [json_patch.sh](https://github.com/turbot/steampipe/blob/0fd4deb161334cb8eec933a85a48ce0c8c958b7b/tests/acceptance/json_patch.sh) script).

What you did might be right and enough, but I would encourage you to test and play with tests like [@test "steampipe check - output json"](https://github.com/turbot/steampipe/blob/0fd4deb161334cb8eec933a85a48ce0c8c958b7b/tests/acceptance/test_files/check.bats#L109) by changing the ordering the file [expected_check_json.json](https://github.com/turbot/steampipe/blob/0fd4deb161334cb8eec933a85a48ce0c8c958b7b/tests/acceptance/test_data/templates/expected_check_json.json) and running a jd and see if it returns anything?

I hope I was clear, any questions regarding this, feel free to ask them here.

Thanks

**Comment by Mr-Destructive** [comment]
Ok, tested that, the order matters in the jd operation which is not appropriate. I'll test with `jd -f patch` or other ways for the order-insensitive checks and ignore the timestamp fields.

Thanks for clarifying.

**Comment by binaek** [comment]
> There is an issue in the `--output` flag maybe, it shouldn't print the pattern (version upgrade warning) especially for `json`, can it be in the warnings list, or way to suppress that?
> 
> The output of `steampipe plugin list --output json --install-dir $tmpdir` :
> 
> ```shell
> $ cat /tmp/tmp.r3oud6qt30/output.json
> 
> +-------------------------------------------------------------------+
> |                                                                   |
> | A new version of Steampipe is available! 0.20.8 → 0.20.9          |
> | You can update by downloading from https://steampipe.io/downloads |
> |                                                                   |
> +-------------------------------------------------------------------+
> 
> {
>   "installed": [
>     {
>       "name": "hub.steampipe.io/plugins/turbot/bitbucket@0.3.1",
>       "version": "0.3.1",
>       "connections": [
>         "bitbucket"
>       ]
>     },
>     {
>       "name": "hub.steampipe.io/plugins/turbot/hackernews@0.6.0",
>       "version": "0.6.0",
>       "connections": [
>         "hackernews"
>       ]
>     }
>   ],
>   "failed": null,
>   "warnings": null
> }
> ```
> 
> This is a bug or should there be a way to suppress this? While using `jd -f patch` or even any jd command it returns a non-zero return status code.
> 
> ```shell
> $ jd -f patch $TEST_DATA_DIR/expected_plugin_list_json.json /tmp/tmp.r3oud6qt30/output.json
> 2023/07/13 15:56:57 invalid character '+' looking for beginning of value
> ```
> 
> Sorry for that wired debugging, but was not able to replicate that issue outside the test env, this doesn't show up on the local steampipe install dir.
> 
> Here was the sample test
> 
> ```shell
> @test "plugin list - output json" {
>   export STEAMPIPE_DISPLAY_WIDTH=100
>   tmpdir="$(mktemp -d)"
>   steampipe plugin install hackernews@0.6.0 bitbucket@0.3.1 --progress=false --install-dir $tmpdir
>   steampipe plugin list --install-dir $tmpdir --output json > $tmpdir/output.json
>   run jd -f patch $TEST_DATA_DIR/expected_plugin_list_json.json $tmpdir/output.json
> 
>   diff=$($MY_PATH/json_patch.sh $output)
>   echo $diff
> 
>   #rm -rf $tmpdir
>   assert_equal "$diff" ""
> }
> ```
> 
> Let me know if this needs to be changed in the output flag. Thank you

@Mr-Destructive - this looks like a bug in the `plugin list` command. For `query` command we do suppress the version upgrade notifications for "pipe-able"  outputs. Take a look at `pkg/tasks/display.go#displayNotifications`.

**Comment by Mr-Destructive** [comment]
Ok, @binaek I have tried to see to run the tests, and the warning only appears once each test for the `list` command. After subsequent calls to the `list` command, it doesn't give any warnings.

```bats
# gives the upgrade warning
run steampipe plugin list --install-dir $tmpdir --output json

# after this it doesn't
steampipe plugin list --install-dir $tmpdir --output json > "$tmpdir/output.json"
```

The below test succeeds but it requires running the list command twice. 
```bats
@test "plugin list - output json" {
  export STEAMPIPE_DISPLAY_WIDTH=100
  tmpdir="$(mktemp -d)"
  steampipe plugin install hackernews@0.6.0 bitbucket@0.3.1 --progress=false --install-dir $tmpdir
  run steampipe plugin list --install-dir $tmpdir --output json
  steampipe plugin list --install-dir $tmpdir --output json > "$tmpdir/output.json"
  run jd -f patch $TEST_DATA_DIR/expected_plugin_list_json.json "$tmpdir/output.json"
  echo $output

  diff=$($MY_PATH/acceptance/json_patch.sh $output)
  echo $diff

  #rm -rf $tmpdir
  assert_equal "$diff" ""
}
```

Based on the `pkg/task/display.go` for the commands, it shouldn't return the warnings, but it is somehow doing that. Even for the install command, it seems to be displaying the warning while setting up tests.

![image](https://github.com/turbot/steampipe/assets/40317114/8e5613c9-1806-42b8-893d-d651f4e2c396)

**Comment by pskrbasu** [comment]
@Mr-Destructive Are you working on this?

**Comment by Mr-Destructive** [comment]
I had some changes, but have not raised the PR for the initial changes. I wanted to confirm if these changes aligned with what was intended.

```bat
@test "plugin list - output json" {
  export STEAMPIPE_DISPLAY_WIDTH=100
  tmpdir="$(mktemp -d)"
  steampipe plugin install hackernews@0.6.0 bitbucket@0.3.1 --progress=false --install-dir $tmpdir
  steampipe plugin list --install-dir $tmpdir --output json > "$tmpdir/output.json"
  run jd -f patch $TEST_DATA_DIR/expected_plugin_list_json.json "$tmpdir/output.json"
  echo $output

  diff=$($MY_PATH/acceptance/json_patch.sh $output)
  echo $diff

  #rm -rf $tmpdir
  assert_equal "$diff" ""
}
```

This is a specific example, but is it how the diff should be compared?
Let me know about the changes so that I can apply those to the other tests accordingly. 

Thank you.

**Comment by Smithjuanita** [comment]
> Update all JSON output tests to use JSONDiff tool `jd --patch`
