### ISSUE TITLE
`.timing` does not print timing info when `.output` is set to anything other than table

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#3557]
`.timing` does not print timing info when `.output` is set to anything other than table.
Steps:
- start interactive
- .timing on
- .output json
- select * from aws_account

Does not show `.timing` info

**Comment by graza-io** [comment]
This appears to be as expected based on this [specific check](https://github.com/turbot/steampipe/blob/main/pkg/display/display_options.go#L16) which checks that `constants.ArgOutput == constants.OutputFormatTable` - @kaidaguerre / @binaek will know better if this is still intended behaviour.
