### ISSUE TITLE
HTTP proxy support 

### ISSUE THREAD

**Issue by mosajjal** [turbot/steampipe#3570]
currently, `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` env variables are not passed from `steampipe`'s environment to the plugin. is there a way to incorporate that in, or have a configuration item to set the proxy. 

Thanks.

**Comment by kaidaguerre** [comment]
Hi @mosajjal 

I have confirmed that the env vars _are_ passed through to the plugin process - so whatever the problem is here, it is not that the env var is missing...

**Comment by kaidaguerre** [comment]
Does the Azure SDK support the proxy env vars? @cbruno10 @misraved

**Comment by sadath-12** [comment]
> Hi [@mosajjal](https://github.com/mosajjal)
> 
> I have confirmed that the env vars _are_ passed through to the plugin process - so whatever the problem is here, it is not that the env var is missing...

I agree as I justed tested it . Wondering if I can rely on that variable for all plugins since they might be using http connections . Currently I just tested for aws . But want confirmation if all plugins use http api calls itself
