### ISSUE TITLE
steampipe cloud timestamp in log has incorrect format

### ISSUE THREAD

**Issue by valankar** [turbot/steampipe#3586]
The DB log on cloud.steampipe.io currently shows me "20:00pm" under the when column. This is not a correct timestamp format.
![timestamp log](https://github.com/turbot/steampipe/assets/31250800/1707d141-209c-4f5b-af66-54cfb1418c27)

**Comment by binaek** [comment]
@mike this looks like an issue for steampipe cloud. Leaving it open here as well

CC @siddharthaturbot

**Comment by MichaelBurgess** [comment]
Thanks for reporting this @valankar. This has now been resolved.
