### ISSUE TITLE
`steampipe service start` and `service status` are not listening on `network` by default

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#3593]
Also, the output of `service start` and `service status` are incorrect for `*` . It's showing `[*]` whereas it should be showing all interfaces.

This broke during the time we merged the #3200 pull request from @pdecat .

**Comment by pdecat** [comment]
Hi @binaek, I've submitted https://github.com/turbot/steampipe/pull/3594 as a starting point to fix the issue and discuss options.
