### ISSUE TITLE
x-509 server certificates are not getting refreshed

### ISSUE THREAD

**Issue by nakulnakhare-cnx** [turbot/steampipe#3596]
**Describe the bug**
Running Steampipe query or Steampipe compliance check would throw an error "failed to connect to `host=localhost user=root database=postgres`: tls error (x509: certificate has expired or is not yet valid")

**Steampipe version (`steampipe -v`)**
Example: v0.20.6

**To reproduce**
I just updated it to the latest version by using the bash script from the website. The only thing different was that I updated all the plugins before updating steampipe.

**Expected behavior**
The server certificate is hardcoded to expire in a year. But they also should auto refresh.

**Additional context**
Manually removing the certificate solved the issue as suggested by @binaek

**Comment by binaek** [comment]
Fixed by #3761
