### ISSUE TITLE
Add ability to add links to control result text

### ISSUE THREAD

**Issue by muescha** [turbot/steampipe#3604]
**Is your feature request related to a problem? Please describe.**

I see my repos listed. but there is no link to my repo

**Describe the solution you'd like**

change all repo names to a clickable link

**Describe alternatives you've considered**

I need to search manually my github repos

**Additional context**

<img width="1421" alt="Bildschirm­foto 2022-12-27 um 01 26 23" src="https://user-images.githubusercontent.com/184316/209590361-55448ce5-c62f-486d-8baf-bf706d4e3f31.png">

**Comment by cbruno10** [comment]
Thanks @MichaelBurgess , I've transferred this issue to the Steampipe repo for better tracking, as this looks to be a CLI addition ultimately

**Comment by muescha** [comment]
what can I do to remove the stale label?

**Comment by kaidaguerre** [comment]
@muescha while this would definitely be useful feature, the implementation of it would need careful thought and design to introduce richer text in the json output.

Not ruling out looking into this further in the future, but it's not something we would prioritise right now so I'm closing this.
