### ISSUE TITLE
Steampipe query paging issue inside container

### ISSUE THREAD

**Issue by tyagiparth** [turbot/steampipe#362]
**Describe the bug**
Steampipe seems to be having a pagination issue when running inside a container. If I minimize the screen to a certain level it gives me the expected results. Screenshots attached.

**Steampipe version (`steampipe -v`)**
steampipe version 0.3.5

**To reproduce**
```
docker pull tyagiparth/steampipe
docker run -it --name steampipe tyagiparth/steampipe "query"
```
try running a query that gives large result example 
`select * from chaos_all_column_types;`

**Expected behavior**
Queries should give the results the same way as we'd expect while running query locally.

**Additional context**
![Screenshot 2021-04-09 at 12 44 22 PM](https://user-images.githubusercontent.com/17849237/114143065-5137f100-9931-11eb-8206-6c869a06d0e0.png)
![Screenshot 2021-04-09 at 12 44 54 PM](https://user-images.githubusercontent.com/17849237/114143139-64e35780-9931-11eb-9150-03dd2f78f807.png)

**Comment by binaek89** [comment]
This happens because the `ubuntu` image is slimmed down and does not contain interactive utilities.

A workaround for the problem is `apt-get install less`
