### ISSUE TITLE
Intermittent failures when looping `check`

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#3644]
When running `steampipe check` in a loop (`for run in {1..10}; do steampipe check ... ; done`) - queries sometime come back with a few unexpected errors:

- `failed to start plugin '[hub.steampipe.io/plugins/turbot/aws@latest](http://hub.steampipe.io/plugins/turbot/aws@latest)': close of closed channel (SQLSTATE HV000)`
- `failed to start plugin '[hub.steampipe.io/plugins/turbot/aws@latest](http://hub.steampipe.io/plugins/turbot/aws@latest)': timed out waiting for [hub.steampipe.io/plugins/turbot/aws@latest](http://hub.steampipe.io/plugins/turbot/aws@latest) to startup after 20 seconds (SQLSTATE HV000)`
- `connection error: desc = "transport: error while dialing: dial unix /var/folders/g2/xyz2244x44q4jgcl8jszvqhm0000gn/T/plugin1828397196: connect: connection refused" (SQLSTATE HV000)`

**Comment by binaek** [comment]
cmd line:

```
binaek@Turingmbp steampipe-mod-aws-compliance % steampipe service stop ; STEAMPIPE_LOG=info steampipe service start ; steampipe query "select * from aws_account" ; ps -ef | grep steampipe; sleep 5 ; echo "waiting another 10" ; sleep 10 ; STAMP=$(date +%s) && for run in {1..10}; do echo "" > ~/.steampipe/logs/plugin-2023-07-04.log ; echo "" > ~/.steampipe/logs/database-2023-07-04.log ; steampipe check benchmark.cis_v150 --export $(echo $STAMP)_$(echo $run)_cis150_$(date +%s).csv --export $(echo $STAMP)_$(echo $run)_cis150_$(date +%s).json --timing; cat ~/.steampipe/logs/database-2023-07-04.log > $(echo $STAMP)_$(echo $run)_database.log; cat ~/.steampipe/logs/plugin-2023-07-04.log > $(echo $STAMP)_$(echo $run)_plugin.log; done ; steampipe service stop
```

**Comment by kaidaguerre** [comment]
could not reproduce
