### ISSUE TITLE
Add ability to add config args to aggregator connections that apply to connections in it

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#3677]
**Is your feature request related to a problem? Please describe.**
When I have an aggregator with connections, if I want to set a common config arg for all connections in the aggregator, I have to define it in each connection.

**Describe the solution you'd like**
Add the ability to define a config arg in an aggregator connection that would apply to all connections of the same plugin type. If a connection has its own value for that config arg, it overrides the aggregator value.

**Describe alternatives you've considered**
Set the config arg in each connection

**Additional context**

**Comment by kaidaguerre** [comment]
a good idea but we are not implementing in the near future
