### ISSUE TITLE
SteamPipe attempts use of READ only file system, and cant use DB even though "--install-dir" used

### ISSUE THREAD

**Issue by astro44** [turbot/steampipe#368]
**Describe the bug**
Error: could not create tmp directory mkdir tmp: read-only file system
Error: Could not start steampipe service: Error: could not establish connection with database
running "--version" outputs with
steampipe version 0.3.6

**Steampipe version (`steampipe -v`)**
steampipe version 0.3.6

**To reproduce**
READ ONLY system except in /tmp
export STEAMPIPE_INSTALL_DIR=/tmp/programs/configs 
didn't seem to have any effect
select name from steampipe_registry_plugin; --install-dir=/tmp/programs/configs

ended up pulling the steampipe binary to /tmp/programs (/tmp/programs/steampipe query select name from.....)
and installed all configs under /tmp/programs/configs

**Expected behavior**
query should work since all dependencies should be in given --install-dir value

**Additional context**

**Comment by kaidaguerre** [comment]
Thanks for the report @astro44 , I'll have a dig into it and see what I can find

**Comment by astro44** [comment]
@kaidaguerre any luck?  let me know if you still want to do a call.

**Comment by kaidaguerre** [comment]
@astro44 yes some progress. I would like to have that call - I'll ping you via email
