### ISSUE TITLE
Include Dashboard Table item

### ISSUE THREAD

**Issue by oaulicino** [turbot/steampipe#3681]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pskrbasu** [comment]
Hey @oaulicino, we need more information, to take a call on this. Can you please explain your use case along with some examples?

Thanks

**Comment by oaulicino** [comment]
I believe this was opened by mistake, Puskar.I clearly opened two issues instead of one. The one I was really trying to open was https://github.com/turbot/steampipe/issues/3682Apologies for the confusion!Best Regards,Otto Aulicino - C|CISO, CISSP, CCSP, CISA, CISMhttps://www.linkedin.com/in/ottoaulicinoOn Aug 2, 2023, at 4:45 AM, Puskar Basu ***@***.***> wrote:﻿
Hey @oaulicino, we need more information, to take a call on this. Can you please explain your use case along with some examples?
Thanks
