### ISSUE TITLE
Include 'height' argument for the Dashboard 'table' block

### ISSUE THREAD

**Issue by oaulicino** [turbot/steampipe#3682]
**Is your feature request related to a problem? Please describe.**
I am currently creating a number of dashboards or detail pages using Steampipe Dashboard, which is great. However, when creating detail pages, sometimes the table block is extremely long, so a height argument could be added, similar to the width that is available at https://steampipe.io/docs/reference/mod-resources/table#argument-reference

**Describe the solution you'd like**
I believe the solution would be something like 
```
table {
  title = "Just an example"
  query = query.just_an_example_query
  width = 2
  height = 4 <-- This is what I need
}
```

**Describe alternatives you've considered**
I am currently moving long tables to separate detail pages, but they are unlikely to be required to be seen separately, at least in my case. 

**Additional context**
No additional context other than provided above, but the attached image can be of help to explain what is happening.
![feature_request](https://github.com/turbot/steampipe/assets/31516700/82e53c30-b1c7-40e7-95c6-d95e17017c04)

**Comment by johnsmyth** [comment]
We have discussed adding `height` previously and decided against it for simplicity.  We still may introduce it at some point, but needs thought around alignment, relativity to width, etc.  Even adding it for a single element like `table` means we need to account for it generally as it affects the placement of all the other panes on the dashboard.  As a result we don't want to prioritize this right now.  

We do have another proposition that we think would solve your problem and would like your feedback though.  We could implement an argument to `table` that allows you to specify the number of rows to display, and allow client-side pagination.  This would implicitly reduce the table size based on the number of rows.  Thoughts?

**Comment by oaulicino** [comment]
This would be perfect!! Best Regards,Otto Aulicino - C|CISO, CISSP, CCSP, CISA, CISMhttps://www.linkedin.com/in/ottoaulicinoOn Aug 3, 2023, at 11:43 AM, johnsmyth ***@***.***> wrote:﻿
We have discussed adding height previously and decided against it for simplicity.  We still may introduce it at some point, but needs thought around alignment, relativity to width, etc.  Even adding it for a single element like table means we need to account for it generally as it affects the placement of all the other panes on the dashboard.  As a result we don't want to prioritize this right now.
We do have another proposition that we think would solve your problem and would like your feedback though.  We could implement an argument to table that allows you to specify the number of rows to display, and allow client-side pagination.  This would implicitly reduce the table size based on the number of rows.  Thoughts?

**Comment by MichaelBurgess** [comment]
We agree this would be a good feature to add, however we're not able to look at this currently due to other priorities, so will close this issue for now.

I've tagged the issue for future review though.
