### ISSUE TITLE
Review of outputs of steampipe commands

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#3703]
* `steampipe dashboard`

* `steampipe dashboard <dashboard.name>`

* `steampipe dashboard list`

**Comment by binaek** [comment]
`steampipe service start`
* normal start
* port in use
* listen local
* listen network
* specific network interface
* `--dashboard-
    * listen local
    * listen network
    * port in use

**Comment by binaek** [comment]
`steampipe service restart`

**Comment by binaek** [comment]
`steampipe service status`

**Comment by binaek** [comment]
* `steampipe plugin install <plugin_name>`
    * with valid `plugin[@stream]` which is not installed
       ![Screenshot 2023-08-03 at 7 11 39 PM](https://github.com/turbot/steampipe/assets/45908484/14b11155-c4eb-44d6-8e86-2f4481395737)
    * with valid `plugin[@stream]` which is already installed
       ![Screenshot 2023-08-03 at 7 12 33 PM](https://github.com/turbot/steampipe/assets/45908484/76e9ab7b-1168-435c-9c78-757908ad3041)
    * with bad plugin name
       ![Screenshot 2023-08-03 at 7 13 53 PM](https://github.com/turbot/steampipe/assets/45908484/25683953-b78d-4038-98f8-30906878367f)


* `steampipe plugin update <plugin_name>`
    * with valid `plugin[@stream]` which is installed
       ![Screenshot 2023-08-03 at 7 21 17 PM](https://github.com/turbot/steampipe/assets/45908484/9f119769-ab5e-4060-a96b-139100e0a00d)
    * with valid `plugin[@stream]` which is not installed
       ![Screenshot 2023-08-03 at 7 22 02 PM](https://github.com/turbot/steampipe/assets/45908484/200630d3-d958-491a-88aa-48c94a04d64a)
       ![Screenshot 2023-08-03 at 7 27 47 PM](https://github.com/turbot/steampipe/assets/45908484/70d319a3-e7ef-4a1c-87e8-b22c842d799c)

    * with bad plugin name
       ![Screenshot 2023-08-03 at 7 22 55 PM](https://github.com/turbot/steampipe/assets/45908484/4d140b35-b999-4c37-a488-5600d7c8107e)
    * with --all argument
       ![Screenshot 2023-08-03 at 7 26 42 PM](https://github.com/turbot/steampipe/assets/45908484/70dfe8ff-d5a5-4097-9de2-b8141f86eb2c)
    * with all
       ![Screenshot 2023-08-03 at 7 25 15 PM](https://github.com/turbot/steampipe/assets/45908484/d78174e9-7ccf-4f44-a61d-1d0f1cf4b4a8)
    * with --all argument and a plugin name
       ![Screenshot 2023-08-03 at 7 24 07 PM](https://github.com/turbot/steampipe/assets/45908484/f4355ee1-9c69-4892-8dce-e680d01f6d23)

  
* `steampipe plugin uninstall <plugin_name>`
    * with valid `plugin[@stream]` which is installed
      ![Screenshot 2023-08-03 at 7 10 15 PM](https://github.com/turbot/steampipe/assets/45908484/f52b3263-0e94-4681-acca-b36032cdca59)
    * with valid `plugin[@stream]` which is not installed
       ![Screenshot 2023-08-03 at 7 15 24 PM](https://github.com/turbot/steampipe/assets/45908484/1bcae6b2-58c7-4e85-b2b5-968356ebba94)
    * with bad plugin name
       ![Screenshot 2023-08-03 at 7 16 04 PM](https://github.com/turbot/steampipe/assets/45908484/75186957-0409-43cb-991b-8924b8ecc90e)


* `steampipe plugin list`
     ![Screenshot 2023-08-04 at 11 57 15 AM](https://github.com/turbot/steampipe/assets/45908484/3968edd1-921c-4c33-9c18-2bfe5e615da6)

**Comment by binaek** [comment]
* `steampipe plugin install <plugin_name>`
    * with valid `plugin[@stream]` which is not installed
       ![Screenshot 2023-08-03 at 7 11 39 PM](https://github.com/turbot/steampipe/assets/45908484/14b11155-c4eb-44d6-8e86-2f4481395737)
    * with valid `plugin[@stream]` which is already installed
       ![Screenshot 2023-08-03 at 7 12 33 PM](https://github.com/turbot/steampipe/assets/45908484/76e9ab7b-1168-435c-9c78-757908ad3041)
    * with bad plugin name
       ![Screenshot 2023-08-03 at 7 13 53 PM](https://github.com/turbot/steampipe/assets/45908484/25683953-b78d-4038-98f8-30906878367f)


* `steampipe plugin update <plugin_name>`
    * with valid `plugin[@stream]` which is installed
       ![Screenshot 2023-08-03 at 7 21 17 PM](https://github.com/turbot/steampipe/assets/45908484/9f119769-ab5e-4060-a96b-139100e0a00d)
    * with valid `plugin[@stream]` which is not installed
       ![Screenshot 2023-08-03 at 7 22 02 PM](https://github.com/turbot/steampipe/assets/45908484/200630d3-d958-491a-88aa-48c94a04d64a)
       ![Screenshot 2023-08-03 at 7 27 47 PM](https://github.com/turbot/steampipe/assets/45908484/70d319a3-e7ef-4a1c-87e8-b22c842d799c)

    * with bad plugin name
       ![Screenshot 2023-08-03 at 7 22 55 PM](https://github.com/turbot/steampipe/assets/45908484/4d140b35-b999-4c37-a488-5600d7c8107e)
    * with --all argument
       ![Screenshot 2023-08-03 at 7 26 42 PM](https://github.com/turbot/steampipe/assets/45908484/70dfe8ff-d5a5-4097-9de2-b8141f86eb2c)
    * with all
       ![Screenshot 2023-08-03 at 7 25 15 PM](https://github.com/turbot/steampipe/assets/45908484/d78174e9-7ccf-4f44-a61d-1d0f1cf4b4a8)
    * with --all argument and a plugin name
       ![Screenshot 2023-08-03 at 7 24 07 PM](https://github.com/turbot/steampipe/assets/45908484/f4355ee1-9c69-4892-8dce-e680d01f6d23)

  
* `steampipe plugin uninstall <plugin_name>`
    * with valid `plugin[@stream]` which is installed
      ![Screenshot 2023-08-03 at 7 10 15 PM](https://github.com/turbot/steampipe/assets/45908484/f52b3263-0e94-4681-acca-b36032cdca59)
    * with valid `plugin[@stream]` which is not installed
       ![Screenshot 2023-08-03 at 7 15 24 PM](https://github.com/turbot/steampipe/assets/45908484/1bcae6b2-58c7-4e85-b2b5-968356ebba94)
    * with bad plugin name
       ![Screenshot 2023-08-03 at 7 16 04 PM](https://github.com/turbot/steampipe/assets/45908484/75186957-0409-43cb-991b-8924b8ecc90e)


* `steampipe plugin list`
     ![Screenshot 2023-08-04 at 11 57 15 AM](https://github.com/turbot/steampipe/assets/45908484/3968edd1-921c-4c33-9c18-2bfe5e615da6)

**Comment by pskrbasu** [comment]
* `steampipe plugin update <plugin_name>`
    * with valid `plugin[@stream]` which is installed
       ![Screenshot 2023-08-03 at 7 21 17 PM](https://github.com/turbot/steampipe/assets/45908484/9f119769-ab5e-4060-a96b-139100e0a00d)
    * with valid `plugin[@stream]` which is not installed
       ![Screenshot 2023-08-03 at 7 22 02 PM](https://github.com/turbot/steampipe/assets/45908484/200630d3-d958-491a-88aa-48c94a04d64a)
       ![Screenshot 2023-08-03 at 7 27 47 PM](https://github.com/turbot/steampipe/assets/45908484/70d319a3-e7ef-4a1c-87e8-b22c842d799c)

    * with bad plugin name
       ![Screenshot 2023-08-03 at 7 22 55 PM](https://github.com/turbot/steampipe/assets/45908484/4d140b35-b999-4c37-a488-5600d7c8107e)
    * with --all argument
       ![Screenshot 2023-08-03 at 7 26 42 PM](https://github.com/turbot/steampipe/assets/45908484/70dfe8ff-d5a5-4097-9de2-b8141f86eb2c)
    * with all
       ![Screenshot 2023-08-03 at 7 25 15 PM](https://github.com/turbot/steampipe/assets/45908484/d78174e9-7ccf-4f44-a61d-1d0f1cf4b4a8)
    * with --all argument and a plugin name
       ![Screenshot 2023-08-03 at 7 24 07 PM](https://github.com/turbot/steampipe/assets/45908484/f4355ee1-9c69-4892-8dce-e680d01f6d23)

  
* `steampipe plugin uninstall <plugin_name>`
    * with valid `plugin[@stream]` which is installed
      ![Screenshot 2023-08-03 at 7 10 15 PM](https://github.com/turbot/steampipe/assets/45908484/f52b3263-0e94-4681-acca-b36032cdca59)
    * with valid `plugin[@stream]` which is not installed
       ![Screenshot 2023-08-03 at 7 15 24 PM](https://github.com/turbot/steampipe/assets/45908484/1bcae6b2-58c7-4e85-b2b5-968356ebba94)
    * with bad plugin name
       ![Screenshot 2023-08-03 at 7 16 04 PM](https://github.com/turbot/steampipe/assets/45908484/75186957-0409-43cb-991b-8924b8ecc90e)


* `steampipe plugin list`
     ![Screenshot 2023-08-04 at 11 57 15 AM](https://github.com/turbot/steampipe/assets/45908484/3968edd1-921c-4c33-9c18-2bfe5e615da6)

**Comment by pskrbasu** [comment]
* `steampipe plugin uninstall <plugin_name>`

    * with valid `plugin[@stream]` which is installed
      ![Screenshot 2023-08-03 at 7 10 15 PM](https://github.com/turbot/steampipe/assets/45908484/f52b3263-0e94-4681-acca-b36032cdca59)
    * with valid `plugin[@stream]` which is not installed
       ![Screenshot 2023-08-03 at 7 15 24 PM](https://github.com/turbot/steampipe/assets/45908484/1bcae6b2-58c7-4e85-b2b5-968356ebba94)
    * with bad plugin name
       ![Screenshot 2023-08-03 at 7 16 04 PM](https://github.com/turbot/steampipe/assets/45908484/75186957-0409-43cb-991b-8924b8ecc90e)

**Comment by pskrbasu** [comment]
* `steampipe plugin list`

     ![Screenshot 2023-08-04 at 4 34 37 PM](https://github.com/turbot/steampipe/assets/45908484/cf38b94e-3b9a-4572-a52c-a860e4607c66)

**Comment by pskrbasu** [comment]
* `steampipe check all`
    * in a folder with no mod.sp
       ![Screenshot 2023-08-23 at 11 46 40 AM](https://github.com/turbot/steampipe/assets/45908484/a81cc3e2-1bb0-4313-bcbd-0862b6c475fc)

    *

**Comment by binaek** [comment]
* `steampipe query list`

* `steampipe query <sql>`
    * invalid SQL
    * valid SQL

* `steampipe query <file.sql>`
    * `file not exist`
    * `file bad permission`

* `steampipe query <query.name>`
    * `query.name` not exist

**Comment by binaek** [comment]
# `steampipe query` (interactive)

**Comment by pskrbasu** [comment]
Opened https://github.com/turbot/steampipe/issues/3849
