### ISSUE TITLE
Review upgrade of hcl library https://github.com/turbot/steampipe/pull/3508

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#3727]
this changes the behaviour of cty.Value.RawEquals, which is used for variables

ensure nothing is broken

https://github.com/turbot/steampipe/pull/3508

**Comment by pskrbasu** [comment]
Looks good!
<img width="919" alt="Screenshot 2023-08-16 at 7 01 56 PM" src="https://github.com/turbot/steampipe/assets/45908484/682a8926-1ee8-4e77-a2a7-3699661eb955">
