### ISSUE TITLE
Defining a table twice causes plugin initialization to hang

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#3730]
https://github.com/turbot/steampipe-plugin-aws/pull/1858#discussion_r1275328991

**Comment by pdecat** [comment]
Tried to reproduce the issue with the AWS plugin duplicating the `account_aliases` column, and it does not seem to hang the plugin initialization anymore, and I can see the in the log:

```
==> /home/patrick/.steampipe/logs/database-2023-10-08.log <==
2023-10-08 07:12:01.393 UTC [1440880] ERROR:  column "account_aliases" specified more than once
```
