### ISSUE TITLE
Broken input in interactive mode when holding arrow keys

### ISSUE THREAD

**Issue by oasaph** [turbot/steampipe#3739]
When on interactive mode `$ steampipe query`, I have to be extremely careful when navigating with my arrow keys to not be too fast, otherwise, at random, unwanted characters are inserted in  the string, rendering the query useless, so I have to `Ctrl+C` and  start typing again

**Steampipe version**
v0.20.9

**To reproduce**
Enter interactive mode `steampipe query`
Type anything on prompt
Hold any lateral arrow key

**Expected behavior**
The cursor should navigate as fast as possible without inserting new unwanted characters and it would be nice if `Ctrl+Arrow` jumped to the next word

**Additional context**
I have seen #865, but I am still able to reproduce it on v0.20.9

**Comment by kaidaguerre** [comment]
@asaph96 sorry for the protracted delay - are you still seeing this issue. What platform are you using? I am unable to reproduce on a mac.

**Comment by ptsteadman** [comment]
I see this as well with steampipe 0.23.3 on OSX. It is much more severe when using tmux for some reason.
The issue can be avoided by turning off key repeat, but that is quite painful for all other applications.
