### ISSUE TITLE
Steampipe CLI log location configuration

### ISSUE THREAD

**Issue by vhadianto** [turbot/steampipe#3757]
Currently Steampipe can only be configured to set the root of Install Directory with no ability to set the log location outside this hierarchy.

There's a requirement in `Pipes` to set the log location in a non-standard location.

**Describe the solution you'd like**
A flag or env variable will work.

**Comment by binaek** [comment]
Implement a `STEAMPIPE_LOG_DIR`  env var (only - no flag or config file item at this time) to change the target logging directory.

All logs will be written in the directory.

Defaults to `$STEAMPIPE_INSTALL_DIR/logs`

**Comment by binaek** [comment]
@vhadianto Is this necessary anymore? If not, can we close it?

**Comment by binaek** [comment]
Not necessary in Steampipe. Can be setup by orchestration
