### ISSUE TITLE
Error: dashboard server startup timed out

### ISSUE THREAD

**Issue by electriquo** [turbot/steampipe#3811]
**Describe the bug**
steampipe does not honor neither dashboard start timeout, nor database start time out environment variables.

**Steampipe version (`steampipe -v`)**
```shell
$ steampipe --version
Steampipe v0.20.11
```

**To reproduce**
```shell
$ env | grep ^STEAMPIPE
STEAMPIPE_DASHBOARD_START_TIMEOUT=500
STEAMPIPE_DATABASE_START_TIMEOUT=360

$ ps aux | grep -v grep | grep -i steampipe

$ time steampipe service start --foreground --show-password --dashboard --dashboard-listen=local
Error: dashboard server startup timed out

real	0m33.537s
user	0m0.160s
sys	0m0.200s

$ ps aux | grep -v grep | grep -i steampipe
ubuntu      5985  122 14.7 1247552 578532 pts/1  Sl   11:10   0:44 /usr/local/bin/steampipe dashboard --dashboard-listen=local --dashboard-port=9194 --install-dir=/home/ubuntu/.steampipe --mod-location=/home/ubuntu/steampipe-mods --service-mode=true --input=false

# repeat previous command after few seconds
$ ps aux | grep -v grep | grep -i steampipe
ubuntu      5985  114 16.8 1386428 663820 pts/1  Sl   11:10   0:59 /usr/local/bin/steampipe dashboard --dashboard-listen=local --dashboard-port=9194 --install-dir=/home/ubuntu/.steampipe --mod-location=/home/ubuntu/steampipe-mods --service-mode=true --input=false
ubuntu      6019  3.0  1.4 153716 56320 pts/1    S    11:11   0:00 /home/ubuntu/.steampipe/db/14.2.0/postgres/bin/postgres -p 9193 -c listen_addresses="localhost" -c application_name=steampipe -c cluster_name=steampipe -c log_directory=/home/ubuntu/.steampipe/logs -c ssl=on -c ssl_cert_file=/home/ubuntu/.steampipe/db/14.2.0/data/server.crt -c ssl_key_file=/home/ubuntu/.steampipe/db/14.2.0/data/server.key -D /home/ubuntu/.steampipe/db/14.2.0/data
ubuntu      6020  0.0  0.1  46436  5232 ?        Ss   11:11   0:00 postgres: steampipe: logger
ubuntu      6022  0.0  0.1 153716  5536 ?        Ss   11:11   0:00 postgres: steampipe: checkpointer
ubuntu      6023  0.0  0.1 153716  5920 ?        Ss   11:11   0:00 postgres: steampipe: background writer
ubuntu      6024  0.0  0.1 153716  5664 ?        Ss   11:11   0:00 postgres: steampipe: walwriter
ubuntu      6025  0.0  0.1 154252  7840 ?        Ss   11:11   0:00 postgres: steampipe: autovacuum launcher
ubuntu      6026  0.0  0.1  46568  5408 ?        Ss   11:11   0:00 postgres: steampipe: stats collector
ubuntu      6027  0.0  0.1 154148  7328 ?        Ss   11:11   0:00 postgres: steampipe: logical replication launcher
```

**Expected behavior**
1. steampipe must honor its environment variable
2. steampipe must not load services in the background when it fails to load

**Additional context**
- #3369
- [configuration file](https://steampipe.io/docs/reference/config-files/options) does not support environment variables equivalent configurations
- STEAMPIPE_DASHBOARD_START_TIMEOUT in undocumented

**Comment by binaek** [comment]
Hi @electriquo 

A couple of questions:
* Which `mod` are you using?
* What's your OS? (`ubuntu` from what I can see)

Can you please collect the log files for when a dashboard start times out. You will find the log files in `~/.steampipe/logs`.

The latest `alpha` release should contain the support for specifying a dashboard start timeout. Can you please check if that solves your problem?

**Comment by binaek** [comment]
> > The latest alpha release should contain the support for specifying a dashboard start timeout. Can you please check if that solves your problem?
> 
> seems like version v0.21.0-alpha.7 solves the issue. let me know if you still interested in answering all your other questions and share the logs.
> 
> will be waiting for 0.21.0 release

@electriquo 

Good to know that `21` fixes it for you!

The logs would still be useful though. The hard-coded timeout for the dashboard server is 30 seconds (in `20.x`). That should be more than enough for the server to complete parsing and start listening.

I would be interested to know what is causing the server to take more than 30 seconds to start up.
