### ISSUE TITLE
ERROR:  failed to resolve query "":  does not define  either a 'sql' property or a 'query' property

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe#3854]
**Describe the bug**

Getting error `ERROR: cannot run docker_compliance.control.cis_v160_1_1_5 - failed to resolve query "":  does not define  either a 'sql' property or a 'query' property` when attempting to incorporate a ternary operator within the control block for the query, 

```
variable "control_types" {
  type        = list(string)
  default = ["docker", "exec"]
}

control "cis_v160_1_1_5" {
  title       = "1.1.5 Ensure auditing is configured for Docker files and directories - /var/lib/docker"

  query = contains(var.control_types, "docker") ? query.query_one : query.query_two
}
```

The above control block throws error  as it is not able to parse the query.

Note: We tried the same above logic with sql  and it works.

```
control "cis_v160_1_1_6" {
  title         = "1.1.6 Ensure auditing is configured for Docker files and directories - /etc/docker"
  sql = contains(var.control_types, "docker") ?  "select 'docker' as resource, 'docker_control' as reason, 'alarm' as status": "select 'exec' as resource, 'ok' as status, 'exec_control 'as reason"
}
```
**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by kaidaguerre** [comment]
The fix for this is non-trivial - for some reason the parsing code is failing to convert the result of he conditional ` contains(var.control_types, "docker") ? query.query_one : query.query_two` back into a `*Query`. The fix for this is not clear right now.

 I believe a workaround would be to do something like:
```
control "cis_v160_1_1_5" {
  title       = "1.1.5 Ensure auditing is configured for Docker files and directories - /var/lib/docker"

  sql = contains(var.control_types, "docker") ? query.query_one.sql : query.query_two.sql
}
```
i.e. populate the `sql` property not `query`
