### ISSUE TITLE
Interactive query multi-line issues with go-prompt

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#3855]
This issue is to track and fix various interactive prompt `multi-line` issues.

- autocomplete does not show suggestions when entering a new multiline query ([#150](https://github.com/turbot/steampipe/issues/150))
![image](https://user-images.githubusercontent.com/2838960/107363648-5532c880-6ad2-11eb-8012-85e80970e376.png)
![image](https://user-images.githubusercontent.com/2838960/107363479-1e5cb280-6ad2-11eb-82c4-68b29c15ba3c.png)

- up arrow does not work correctly when entering a new multiline query ([#151 ](https://github.com/turbot/steampipe/issues/151))
    - when midways through entering a multiline query, up arrow shows history instead of moving cursor within the multiline query

- up arrow moves to wrong column when navigating a multiline query retrieved from history ([#152](https://github.com/turbot/steampipe/issues/152))
    - it move to the column length of the line below, instead of maintaining the cursor x position

**Comment by kaidaguerre** [comment]
meta issue - closing
