### ISSUE TITLE
Create a Plugin for SFTP Server

### ISSUE THREAD

**Issue by Mebin01** [turbot/steampipe#3858]
**Describe the solution you'd like**
I want a SFTP Plugin which can access CSV Files or any static files like JSON,CSV,XLSX files, basically a plugin for SFTP Server

**Comment by cbruno10** [comment]
Hi @Mebin01 , I've transferred this issue to the main Steampipe repository, since a new plugin isn't something we'd embed into the existing CSV plugin.

**Comment by Mebin01** [comment]
Hey @cbruno10  what can I expect next after you have transferred this issue to the main repository

**Comment by cbruno10** [comment]
Hey @Mebin01 , we're always looking at new plugin ideas, so we'll add this plugin to our existing backlog. We don't have a concrete timeline on when we'll start developing it or when it'll be released, but any updates we have, we'll post here in this issue.

If anyone from the community is interested in trying to create an SFTP plugin, we have some docs over at https://steampipe.io, like https://steampipe.io/docs/develop/writing-plugins and https://steampipe.io/docs/develop/plugin-release-checklist that should help them get started writing their own plugin.

In terms of SFTP client packages, something like https://github.com/pkg/sftp seems like a good starting place (I haven't had a chance to look at the package in depth though).

**Comment by cbruno10** [comment]
Hi @Mebin01 , it's still in our backlog, but not actively being worked on. If we have any additional updates, we'll post back in this thread.
