### ISSUE TITLE
Makefile target `pluginmanager` no longer exists

### ISSUE THREAD

**Issue by pdecat** [turbot/steampipe#3871]
**Describe the bug**

Only noticed this as I usually only call `make`:
```
# make all
make -C pluginmanager
make[1]: *** pluginmanager: No such file or directory.  Stop.
make: *** [Makefile:10: all] Error 2

```

**Steampipe version (`steampipe -v`)**

```
# steampipe --version
Steampipe v0.21.0-beta.0
```

**To reproduce**

Run `make all`.

**Expected behavior**

No error :)

**Additional context**

Probably an oversight from https://github.com/turbot/steampipe/pull/2741/files#diff-f23856bb94462cfda7ffe84e3a3152daccd019f402fa39d41510d75038615a7b

**Comment by kaidaguerre** [comment]
thanks @pdecat
