### ISSUE TITLE
Reenable `search_path` acceptance tests

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#3885]
The tests have been modified to query `select 1` before running `show search_path`.

This is because of a race condition that exists between the search path getting set after refreshing connections and the client getting initialised.

**Comment by Smithjuanita** [comment]
> The tests have been modified to query `select 1` before running `show search_path`.
> 
> This is because of a race condition that exists between the search path getting set after refreshing connections and the client getting initialised.
