### ISSUE TITLE
Helm Chart for Steampipe

### ISSUE THREAD

**Issue by amartingarcia** [turbot/steampipe#3935]
I am currently using Steampipe in my company, we run Steampipe in Kubernetees with a Helm Chart I developed, would you be interested in me creating a Pull Request with the code?, if so let me know how to proceed.

Regards

**Comment by e-gineer** [comment]
Hey @amartingarcia ... fantastic that you are working on this!

We'd encourage you to share them in your own repo at this point. There will definitely be interest from the community - the question has been asked multiple times in our Slack. You may even find others happy to contribute / help.

We'd prefer not to put this in the main Steampipe repo at this stage as we're not in a position to be able to support it for questions / setup etc.

Thanks :rocket:

**Comment by amartingarcia** [comment]
Hey @e-gineer , Thanks for your comment. I add the link to the repository for anyone who reads this issue and wants to use it.

https://github.com/devops-ia/helm-charts/tree/main/charts/steampipe

Regards.
