### ISSUE TITLE
Error in Node That Utilizes Github Plugin

### ISSUE THREAD

**Issue by laikas123** [turbot/steampipe#3939]
**Describe the bug**

When adding a node for a dashboard, certain syntax changes cause a bug when they shouldn't.

**Steampipe version (`steampipe -v`)**
Steampipe v0.20.12

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

1) Add this code to a graph in a dashboard and it will work fine:

```sql
node {

      sql = <<-EOQ
        SELECT
       u.login as id,
       u.login AS "User Name",
       u.name AS "Full Name",
       u.location AS "Location",
       u.login as title

      FROM github.github_user as u join github_repository_collaborator as c
      on u.login = c.user_login and c.repository_full_name = '(YOUR REPO FULL NAME)'
      EOQ
    }
```

2) Add either of the variations shown below and it will break:

**Variation 1**

```sql
node {

      sql = <<-EOQ
        SELECT
      --removed 3 of the selected columns, but they aren't required columns
       u.login as id,
       u.login as title

      FROM github.github_user as u join github_repository_collaborator as c
      on u.login = c.user_login and c.repository_full_name = '(YOUR REPO FULL NAME)'
      EOQ
    }
```

**Variation 2**

```sql
node {

      sql = <<-EOQ
        SELECT
      --modified 2 of the selected columns (first and last) but shouldn't break things
       c.permission as id,
       u.login AS "User Name",
       u.name AS "Full Name",
       u.location AS "Location",
       c.permission.login as title

      FROM github.github_user as u join github_repository_collaborator as c
      on u.login = c.user_login and c.repository_full_name = '(YOUR REPO FULL NAME)'
      EOQ
    }
```

You can see the **only** changes made are with regards to what is being selected. Nothing in the FROM clause is actually changed.

In both cases the resulting error message is:

**ERROR: rpc error: code = Internal desc = 'List' call for table 'github_user' is missing 1 required qual: column:'login' operator: = (SQLSTATE HV000)**

**Expected behavior**

I wouldn't expect the changes I list above to cause the resulting error. You can see that `u.login = c.user_login` is set in each case so the error seems erroneous. Changing what is selected (which is the only change made from the original working code) shouldn't break this.

**Additional context**

I have seen this error pop up a fair amount when using the github plugin even when I use some `u.login = ' statement appropriately.
Any insight would be helpful especially if I am making an error and not realizing it. Thank you.

**Comment by pskrbasu** [comment]
@laikas123 Thank you for raising the issue - I'll try to reproduce it. Meanwhile, can you try the same queries failing for you in steampipe interactive query mode and see if you still see the error(or is it just in )?

**Comment by laikas123** [comment]
@pskrbasu Thanks for the quick reply, yep it also happens in interactive mode as seen below:

![image](https://github.com/turbot/steampipe/assets/50219221/002e369e-4fee-4d05-b9f4-c86f55f397ac)

**Comment by e-gineer** [comment]
In the case above, the postgres planner is deciding that it's better to scan the `github_user` table and then match on `login`, which means we're not passed the matching value at the Steampipe plugin layer.

Often, rewriting to use a CTE may fix this issue so the query occurs in phases.

You can also use `explain analyze select ...` to see what the planner is going to do.

**Comment by laikas123** [comment]
@e-gineer thank you for your comment. So it sounds like this isn't really bug with steampipe but more so the result of how postgres is handling the query...

I will look into the postgres planner and also try using CTES.

Thank you for the help
