### ISSUE TITLE
![Service Badge](https://img.shields.io/endpoint?url=https://winget-pme.azurefd.net/api/GetServiceComponentStatusBadge?component=ValidationPipeline "Validation Pipeline Badge") &nbsp;![Service Badge](https://img.shields.io/endpoint?url=https://winget-pme.azurefd.net/api/GetServiceComponentStatusBadge?component=PublishPipeline "Publish Pipeline Badge") &nbsp;

### ISSUE THREAD

**Issue by Smithjuanita** [turbot/steampipe#3985]
![Service Badge](https://img.shields.io/endpoint?url=https://winget-pme.azurefd.net/api/GetServiceComponentStatusBadge?component=ValidationPipeline "Validation Pipeline Badge") &nbsp;![Service Badge](https://img.shields.io/endpoint?url=https://winget-pme.azurefd.net/api/GetServiceComponentStatusBadge?component=PublishPipeline "Publish Pipeline Badge") &nbsp;

_Originally posted by @wingetbot in https://github.com/microsoft/winget-pkgs/pull/124252#issuecomment-1784532879_

**Comment by cbruno10** [comment]
@Smithjuanita I'm not sure what this issue is for, but I'm closing it as it doesn't seem relevant to this repository. If you have anymore details though, feel free to add them and re-open. Thanks!
