### ISSUE TITLE
Capital letters in connection names cause 

### ISSUE THREAD

**Issue by delenamalan** [turbot/steampipe#3986]
**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by cbruno10** [comment]
Hi @delenamalan , can you please add more details on what error you're getting and what your connections look like? Thanks!

**Comment by delenamalan** [comment]
Hi @cbruno10, sorry, I must've created this issue by accident. It's a duplicate of https://github.com/turbot/steampipe/issues/3987.
