### ISSUE TITLE
Capital letters in connection names cause "relation does not exist" errors

### ISSUE THREAD

**Issue by delenamalan** [turbot/steampipe#3987]
**Describe the bug**
When a connection name contains capital letters, then I get "relation <connection name> does not exist" errors.

**Steampipe version (`steampipe -v`)**
v0.21.1

**To reproduce**
Create an AWS connection, for example:

```
connection "Myaccount" {
  plugin  = "aws"
  profile = "myprofile"
  regions = ["*"]
}
```

And try to run a query, for example: `select * from Myaccount.aws_vpc limit 1;`

**Expected behavior**
Connection names containing capital letters should be queryable.

**Comment by e-gineer** [comment]
Hey @delenamalan … in Postgres any identifier with capitals needs to be wrapped in double quotes.

Does this work for you?

`select * from “Myaccount”.aws_vpc limit 1;`

**Comment by delenamalan** [comment]
Hi @e-gineer, yes, that works. Thank you!
