### ISSUE TITLE
Steampipe Tag-Based Scanning AWS Resources

### ISSUE THREAD

**Issue by CansuCandan** [turbot/steampipe#4029]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CansuCandan** [comment]
Dear Steampipe Team,

I hope this message finds you well.

I am writing to seek guidance regarding a specific issue we are encountering with tag-based scanning of our AWS resources using Steampipe. Our team has utilized the steampipe-mod-aws-well-architected module for this purpose, following the steps below:

Cloning the repository: git clone https://github.com/turbot/steampipe-mod-aws-well-architected.git
Navigating to the directory: cd steampipe-mod-aws-well-architected
Modifying the steampipe.spvars file to include:

# Dimensions
common_dimensions = ["account_id", "region"]
tag_dimensions = ["Environment", "Prod"]

Our objective is to scan AWS resources that are specifically tagged with Key: "Environment" and Value: "Prod". However, upon executing the command steampipe check all --var='mandatory_tags=["Environment", "Prod"]', Steampipe continues to scan all AWS resources, not just those matching our specified tags.

We are keen to understand how we can modify our approach to ensure that only resources with the specified tags are scanned. Any insights or step-by-step guidance you can provide on this matter would be greatly appreciated.

Thank you in advance for your assistance. I look forward to your expert advice on resolving this issue.

Best regards,
Cansu Candan

**Comment by e-gineer** [comment]
The tag_dimensions variable expects a list of tag key names. The key/value of these tags will then be added as dimensions (i.e. metadata) to the output of each control in the results.

Unfortunately there is no way to target the scan at particular resources by tag. AWS does not provide a reliable or repeatable way to filter resources by tag across their APIs.

So, one option is to:
1. Add the tag key you want to filter on as a tag_dimension.
2. Run the check, output to CSV.
3. Use a spreadsheet or the CSV steampipe plugin to filter the results to the tag you care about.

I hope that helps!
