### ISSUE TITLE
Add support for Postgres 16

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#4067]
Right now, `steampipe` operates with a stripped down version of `pg14`

This needs to be updated to `pg16`

Tasks:
- [ ] Build and Deploy `PG16` image to `hub.steampipe.io`
- [ ] Build and Deploy `FDW` compatible with `PG16` to `hub.steampipe.io`

**Comment by pataquets** [comment]
Stalebot closed the issue as "not planned"?
@binaek: bringing this to your attention, as what can be understood from the issue, steampipe is not going to keep up to date with new versions of Pg, which sounds quite weird :smile:, specially given the awesome interoperability and wide range of integrations it has.
Hint: I'd like to suggest you to configure stalebot to skip legit/accepted enhancement issues, so you don't get too much keep-alive noise.

**Comment by binaek** [comment]
@pataquets as far as I can remember, the upgrade was a bit more complicated than we had anticipated.

Especially with the fdw compilation with PG16 bindings ... 

Also, the upgrade to PG16 doesn't offer much upgrade in terms of query capability or planning.

@kaidaguerre ^^^
