### ISSUE TITLE
Add support for mod.sp formating

### ISSUE THREAD

**Issue by remyleone** [turbot/steampipe#4081]
**Is your feature request related to a problem? Please describe.**

I sometimes have consistency in formatting with my mod.sp. I would like to have a format subcommand in the steampipe binary that would handle that for me.

**Describe the solution you'd like**

steampipe mod fmt or any other formatting sub command in the steampipe binary

**Describe alternatives you've considered**

Using terraform but it does not allow for sp file extensions

**Additional context**

**Comment by k-kawa** [comment]
FYI.
I use https://github.com/hashicorp/hcl/tree/main/cmd/hclfmt as alternative. `*.sp` and `*.spc` files are written in HCL so that `hclfmt` works.

```bash
go install github.com/hashicorp/hcl/v2/cmd/hclfmt@latest

find . -name '*.sp' | xargs hclfmt -w 
find . -name '*.spc' | xargs hclfmt -w 
```
