### ISSUE TITLE
Add documentation about how to configure editor completion for IDE

### ISSUE THREAD

**Issue by remyleone** [turbot/steampipe#4082]
**Is your feature request related to a problem? Please describe.**

When I'm in my IDE developing SQL queries for steampipe. I would like to have completion and documentation for the tables columns.

**Describe the solution you'd like**

I would like to have a documentation page that show how to configure my editor (vscode, intellij, ...) to find the right data source so that auto discovery of tables format could happen natively.
I don't mind using sqlite for making this easier

**Describe alternatives you've considered**

I think a postgres instance is run by steampipe in the background to make it happen but I don't know how to configure the IDE to connect to it without disturbing its behavior.

**Comment by pataquets** [comment]
Still relevant...

**Comment by pataquets** [comment]
Feeding the stalebot. Sorry for the comment noise.
@remyleone: any chance an issue can be tagged for the Stalebot to skip? (e.g. desired/accepted FRs with no milestone decided)

**Comment by pataquets** [comment]
> Feeding the stalebot. Sorry for the comment noise.
> @remyleone: any chance an issue can be tagged for the Stalebot to skip? (e.g. desired/accepted FRs with no milestone decided)

Copypasting...
/cc @remyleone

**Comment by e-gineer** [comment]
Steampipe runs a standard postgres server embedded, so most IDEs can connect directly to Postgres to query information about the tables etc. Steampipe sets up the schemas, column comments, everything to support that.

One catch is that some IDEs don't support foreign tables in Postgres, so they don't find the Steampipe managed tables. (Many / most IDEs do.)

Service mode can be a good way to run steampipe for this capability and find the endpoint - https://steampipe.io/docs/managing/service

We've also documented many different ways to connect to Steampipe / Turbot Pipes at https://turbot.com/pipes/docs/connect

Is that what you need, or are you looking for something else?
