### ISSUE TITLE
Not able to enable opentelemetry  

### ISSUE THREAD

**Issue by kartik7153** [turbot/steampipe#4096]
**Describe the bug**
I want enable opentelementry on steampipe service. I have exported the variables STEAMPIPE_OTEL_LEVEL=TRACE and OTEL_EXPORTER_OTLP_ENDPOINT=<locally hosted collector with grpc port> 

`error: failed to initialise functions: ERROR: failed to initialise telemetry: grpc: no transport security set (use grpc.WithTransportCredentials(insecure.NewCredentials()) explicitly or set credentials) (SQLSTATE HV000)`

**Steampipe version (`steampipe -v`)**
Steampipe v0.21.4

**To reproduce**
STEAMPIPE_OTEL_LEVEL=TRACE steampipe service restart 
Error: failed to initialise functions: ERROR: failed to initialise telemetry: grpc: no transport security set (use grpc.WithTransportCredentials(insecure.NewCredentials()) explicitly or set credentials) (SQLSTATE HV000)

**Expected behavior**
Service should restart and traces should be sent to collector

**Additional context**
So when I start the service without OTEL variables export. It works and when I do 

STEAMPIPE_OTEL_LEVEL=TRACE steampipe query <query>. It gives the output of the query and gives the warning error. 
`Warning: grpc: no transport security set (use grpc.WithTransportCredentials(insecure.NewCredentials()) explicitly or set credentials)`

**Comment by pskrbasu** [comment]
@kartik7153 This has been fixed in Steampipe v0.21.7. Thanks!
