### ISSUE TITLE
Intermittently getting runtime error: invalid memory address or nil pointer dereference while using AWS plugin

### ISSUE THREAD

**Issue by kartik7153** [turbot/steampipe#4097]
**Describe the bug**
We have been getting Intermittently nil pointer dereference. It works on the first execution of the query and when I try to execute it second time it fails. 

**Steampipe version (`steampipe -v`)**
Steampipe v0.21.4
hub.steampipe.io/plugins/turbot/aws@latest | 0.125.0

**To reproduce**
1. Run the steampipe server. 
2. Execute the query - `steampipe query "select * from lsq_dev.aws_ec2_launch_template"` 
3. You will get correct results
4. Execute it again - `steampipe query "select * from lsq_dev.aws_ec2_launch_template"` 
5. It fails with  nil pointer dereference

**Expected behavior**
Ideally it should have returned back with the same result. 

**Additional context**
[correct-execution-logs.txt](https://github.com/turbot/steampipe/files/14093214/correct-execution-logs.txt)
[error-execution-logs.txt](https://github.com/turbot/steampipe/files/14093216/error-execution-logs.txt)

**Comment by kaidaguerre** [comment]
thanks @kartik7153 - I've reproduced, looking for a fix

**Comment by og-stevelee** [comment]
@kaidaguerre ,
Is there an update with this issue?  This is happening on the `terraform_resource` as well.

Thanks,

**Comment by jeffreymp17** [comment]
Hi @kaidaguerre any update on this one?  we're having issues on this using Azure plugin getting the same error

**Comment by kaidaguerre** [comment]
@jeffreymp17 apologies for delay on this one. Are you still seeing these issues? I cannot reproduce with steampipe v0.23.1 and aws v0.138.0

**Comment by jeffreymp17** [comment]
I'm having the issue with SOME gcp queries as well
I created this issue with the example queries https://github.com/turbot/steampipe/issues/4279
