### ISSUE TITLE
steampipe fresh installation not working on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by paolo-losi** [turbot/steampipe#4117]
**Describe the bug**
Fresh installation is install script does not work on ubuntu 20.04 LTS

**Steampipe version (`steampipe -v`)**
$ steampipe -v
Steampipe v0.21.5

**To reproduce**
$ steampipe plugin install steampipe

steampipe                      [====================================================================] Done                

Installed plugin: steampipe@latest v0.10.0
Documentation:    https://hub.steampipe.io/plugins/turbot/steampipe

$ steampipe query "select name from steampipe_registry_plugin;"
Warning: You have a mod.sp file in your home directory. This is not recommended.
As a result, steampipe will try to load all the files in home and its sub-directories, which can cause performance issues.
Best practice is to put mod.sp files in their own directories.
Hit Ctrl+C to stop.

Error: no rows in result set
$ find . -name "mod.sp"
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Additional context**
recompiling from source with go 1.21.6 the warning disappears but the query still returns no rows

**Comment by pskrbasu** [comment]
@paolo-losi Thank you for reporting. 

I'll try to install it in Ubuntu 20.04 LTS and see if I can reproduce it.

**Comment by pskrbasu** [comment]
@paolo-losi Seems like a bug we introduced in v0.20.5. We are working on a fix. Thanks ✌️

**Comment by pskrbasu** [comment]
@paolo-losi v0.20.6 is released. I tried it out - seems to be working now!

**Comment by paolo-losi** [comment]
I can confirm that I get no warnings now.
But I still get no rows:

`$ which steampipe
/usr/local/bin/steampipe
$ steampipe -v
Steampipe v0.21.6
$ steampipe plugin install steampipe

steampipe                      [====================================================================] Already installed   

To update this plugin: steampipe plugin update steampipe
To update all plugins: steampipe plugin update --all

$ steampipe plugin update --all

turbot/net                     [====================================================================] Latest already installed      
turbot/steampipe               [====================================================================] Latest already installed      

$ steampipe query "select name from steampipe_registry_plugin;"
Error: no rows in result set
$ 
`

**Comment by pskrbasu** [comment]
@paolo-losi I ran the same query as above, but I did not get the error. I do get the result.

Can you try with `STEAMPIPE_LOG=trace steampipe query "select name from steampipe_registry_plugin;"` and check the logs in `~/.steampipe/logs/plugin-yyyy-mm-dd.log` file? You might see some errors or warnings there.

**Comment by paolo-losi** [comment]
here you have the logs for the command:

$ STEAMPIPE_LOG=trace steampipe query "select name from steampipe_registry_plugin;"

Thanks!

[database-2024-02-07.log](https://github.com/turbot/steampipe/files/14191591/database-2024-02-07.log)
[steampipe-2024-02-07.log](https://github.com/turbot/steampipe/files/14191592/steampipe-2024-02-07.log)

**Comment by pskrbasu** [comment]
@paolo-losi Do you not have any `plugin-yyyy-mm-dd.log` file? 

Can you uninstall the steampipe plugin and re-install and try again?
