### ISSUE TITLE
Race condition between service startup and service status

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#4143]
When 2 containers are started, one of which startsa the steampipe service and one polls service status, sometimes trhe postmaster.pid file is deleted, causing postgres to abort

This is probably a race condition between thge writing of the state file and `service status` calling GetState, which if it fails to load the file checks the pid from the postmaster.pid file, and potentially deletes the file if the pid is not found

**Comment by shaicoleman** [comment]
If steampipe would listen to a random local socket on each execution instead of a network port, this wouldn't happen.

This will also solve #4155
