### ISSUE TITLE
Pass a configuration filepath as an argument to the streampipe command.

### ISSUE THREAD

**Issue by aitoehigie** [turbot/steampipe#4202]
Is your feature request related to a problem? Please describe.
I'm always frustrated when I cannot dynamically pass the Steampipe configuration file path (spc file) as an argument to the Steampipe command. This limitation prevents me from seamlessly integrating Steampipe into my web application where each user supplies their API tokens, and the configuration needs to be generated on the fly.

Describe the solution you'd like
I would like the ability to pass the Steampipe configuration file path (spc file) as an argument to the Steampipe command. This enhancement would allow me to dynamically generate the configuration file for each user in my web application context, ensuring that each user's API tokens are used for querying with Steampipe.

Describe alternatives you've considered
One alternative solution could be to set up separate Steampipe instances for each user, each with their own pre-configured spc file. However, this approach would be less scalable and would require significant overhead in managing multiple instances.

Additional context
This feature would greatly enhance the flexibility and usability of Steampipe in web application contexts, enabling seamless integration with user-specific API tokens and configurations. It would simplify the deployment and management of Steampipe in multi-user environments and improve the overall user experience.

**Comment by aitoehigie** [comment]
I will be calling different instances of Steam pipe for each user, so
would  passing --install-dir <the path to the ephemeral Stripe
configuration file> to the Steam pipe command work?

**Comment by johnsmyth** [comment]
I guess I misunderstood your request.  It sounded like you wanted to share the same database instance from different clients, with different configurations for each.   If you are going to start a separate DB instance for each user then it is reasonable to add a config path arg to the `service start` command.  Is that what you are looking for?

As for the `--install-dir`, that needs to point to the equivalent of the `~/.steampipe` directory.  The drawback is that you would have to install the plugins in each of these instances.

**Comment by aitoehigie** [comment]
Exactly.
I would like to add a config path argument to the Steampipe command.
The steampipe instances aren't long-running instances as I intend calling it from a web server context (with Python's `subprocess`, then passing a config file containing the Stripe API key, that I created in that request cycle) and displaying the output in a dashboard.
Can I do this currently with Steampipe?

**Comment by johnsmyth** [comment]
When you say `displaying output in a dashboard` do you mean a Steampipe/Powerpipe dashboard or your own application's dashboard?

**Comment by johnsmyth** [comment]
If you are treating these instances as ephemeral and short-lived, and you are only accessing them through your own code on the back end, perhaps the [SQLite Extensions]( https://steampipe.io/docs/steampipe_sqlite/overview) or [Export CLIs](https://steampipe.io/docs/steampipe_export/overview) might be a better, more lightweight fit?

**Comment by aitoehigie** [comment]
> When you say `displaying output in a dashboard` do you mean a Steampipe/Powerpipe dashboard or your own application's dashboard?

My application's dashboard

**Comment by aitoehigie** [comment]
> If you are treating these instances as ephemeral and short-lived, and you are only accessing them through your own code on the back end, perhaps the [SQLite Extensions](https://steampipe.io/docs/steampipe_sqlite/overview) or [Export CLIs](https://steampipe.io/docs/steampipe_export/overview) might be a better, more lightweight fit?

I think I will try the export CLI, I see it allows me to pass a --config flag. Which is fits what I am trying to accomplish.

**Comment by kaidaguerre** [comment]
closing this issue - please raise another or get in touch via the steampipe community of you have further issues/questions
