### ISSUE TITLE
Ability to get ALL inventory (exported to csv/whatever), so I can diff it between runs

### ISSUE THREAD

**Issue by neilmcguigan** [turbot/steampipe#4283]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to view differences in inventory between runs, say daily, but cannot see how

**Describe the solution you'd like**
something like `select count(*) from aws.all_resources` or `select identifier from aws.all_resources order by identifier` which i can then export to CSV, and diff between previous run

**Comment by kaidaguerre** [comment]
Hi @neilmcguigan 

This [answer](https://github.com/turbot/steampipe-plugin-aws/issues/10#issuecomment-781715941) to a similar question may prove useful.
