### ISSUE TITLE
Docker Image for latest steampipe

### ISSUE THREAD

**Issue by abhinavgrover15** [turbot/steampipe#4290]
**Is your feature request related to a problem? Please describe.**
I see on docker hub that steampipe new version docker image has been stopped from being published.
How do we build new steampipe docker images. Is there any sample Dockerfile which can be used?

**Comment by pskrbasu** [comment]
Hey @abhinavgrover15 we recently announced that we'll no longer be creating "official" docker images for Steampipe and our other CLI projects.

FAQ - https://steampipe.io/docs/faq/overview#where-is-the-dockerfile-or-container-example

Announcement - https://steampipe.io/changelog/steampipe-cli-remove-official-docker-support

**Comment by abhinavgrover15** [comment]
hey @pskrbasu Thank you for the information. But we have our apps running in k8s cluster.  

How can we build our won steampipe docker image using the binary for our tasks.
I was reading that for turbot pipes, you still use docker images.

**Comment by e-gineer** [comment]
Everyone has a different requirement for these docker images - they end up being very specific to the environment.

I'd suggest that the best place to start would be to grab the existing Dockerfile we'd published previously and modify that for your needs.

**Comment by kaidaguerre** [comment]
closing this now
