### ISSUE TITLE
setting autocomplete in workspaces files has no effect

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe#4291]
**Describe the bug**

Disabling autocomplete in workspaces files has no effect.

**Steampipe version (`steampipe -v`)**
Steampipe v0.23.2

**To reproduce**
turn of autocomplete in workspaces.spc:
```hcl
workspace "default" {
  options "query" {
    autocomplete = "off"
  }
}
```

run `steampipe query`.  Note that autocomplete is still on.

**Expected behavior**
autocomplete should be disabled, per the workspace setting

**Additional context**

**Comment by Mr-Destructive** [comment]
I think this is working fine, not able to replicate the issue with `autocomplete = false`
```hcl
workspace "default" {
  options "query" {
    autocomplete = false
  }
}
```
This works and disables the auto-complete according to the workspace setting. [Workspace Documentation](https://steampipe.io/docs/reference/config-files/workspace#:~:text=Description-,autocomplete,-true)
Thanks.
