### ISSUE TITLE
Docker image for 0.24 doesn't exist in https://hub.docker.com

### ISSUE THREAD

**Issue by refeed** [turbot/steampipe#4393]
Currently the version of steampipe is 0.24.2, but in the [docker registry](https://hub.docker.com/r/turbot/steampipe/tags), the latest version is 0.22. Could we update it to the latest version?

**Comment by e-gineer** [comment]
Hi @refeed ... we announced a while back that we would no longer publish official docker images.

FAQ on this - https://steampipe.io/docs/faq/overview#where-is-the-dockerfile-or-container-example

**Comment by refeed** [comment]
Alright, thank you :)
