### ISSUE TITLE
Remove `check`, `dashboard`, `mod`, `variable` commands

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#4413]
Remove the check, dashboard, mod and variable commands from steampipe, since these functionalities have to moved to Powerpipe.

**Comment by TSP06** [comment]
Hey @pskrbasu I would like to take this up

**Comment by pskrbasu** [comment]
Hey @TSP06 thank you for your interest, but we have already worked on it.

**Comment by pskrbasu** [comment]
https://github.com/turbot/steampipe/commit/e85761021b12b01d20c6e1986170356c545663d8
