### ISSUE TITLE
.cache clear is not working

### ISSUE THREAD

**Issue by cjsrkd3321** [turbot/steampipe#4443]
**Describe the bug**
.cache clear / select from steampipe_internal.meta_cache('clear') is not working.

**Steampipe version (`steampipe -v`)**
v1.0.0

**To reproduce**
```bash
### 1st terminal ###
cd ~/.steampipe/logs
tail -f plugin-*.log
```

```bash
### 2nd terminal ###
steampipe query
> select * from aws_iam_role
```

```bash
### 1st terminal ###
...<SNIP>...
2024-11-17 13:01:27.543 UTC [INFO]  steampipe-plugin-aws.plugin: [INFO]  <SNIP>: queryCacheGet returned CACHE MISS (aws-<SNIP>)
...<SNIP>...
```

```bash
### 2nd terminal ###
> .cache clear
> select * from aws_iam_role
```

```bash
### 1st terminal ###
...<SNIP>...
2024-11-17 13:03:46.500 UTC [INFO]  steampipe-plugin-aws.plugin: [INFO]  <SNIP>: queryCacheGet returned CACHE HIT (aws-<SNIP>)
...<SNIP>...
```

**Expected behavior**
The 1st terminal should have printed "...**returned CACHE MISS**".

**Additional context**
I'm using MAC(Apple Silicon).

**Comment by kaidaguerre** [comment]
Hi @cjsrkd3321 

There does seem to be a bug here. I'll look into it and get a fix sorted. 

Thanks for raising this.
