### ISSUE TITLE
steampipe accepts the query on `STDIN`

### ISSUE THREAD

**Issue by suhlig** [turbot/steampipe#499]
Today, when running a query from the command line, `steampipe query` takes the query as parameter. When composing pipelines, I would like to provide the query on `STDIN`:

```command
cat <<EOQ | steampipe query --output json                                                                                                                                           
  select
    title, url
  from
    hackernews_top
  order by
    score desc
  limit
    10
EOQ
```

This is already possible with `psql` (after `steampipe service start`):

```command
cat <<EOQ | psql 'postgres://steampipe:********@localhost:9193/steampipe?sslmode=disable'
  select
    title, url
  from
    hackernews_top
  order by
    score desc
  limit
    10
EOQ
```

In the examples above, `cat` is used as a placeholder for other commands generating a query.

Thanks for `steampipe`, please keep up the good work!

**Comment by e-gineer** [comment]
Nice suggestion @suhlig - thanks!

We'd need to make sure this is limited to input on the `steampipe query` subcommand only, but agree it would be good to accept stdin.

In the meantime, steampipe query accepts the query directly as the argument ... are you able to use that instead? For example:
```
steampipe query --output json "
  select
    title, url
  from
    hackernews_top
  order by
    score desc
  limit
    10
"
```

**Comment by suhlig** [comment]
Thanks - I can sure use the argument. I just think it's easier to read the command line and understand the whole pipeline when constructed the way I propose (especially if it becomes more complex).
