### ISSUE TITLE
Add reflection table for Steampipe connections

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#505]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to get my connection information from tables to use in queries that rely on this information.

**Describe the solution you'd like**
A table or set of tables that contain my current connection information.

**Describe alternatives you've considered**
None at the moment.

**Additional context**

**Comment by kaidaguerre** [comment]
this has been [implemented](https://github.com/turbot/steampipe/tree/add_reflection_table_for_Steampipe_connections_505) 

However more work is needed on potentially parsing the connection config before insertion

**Comment by kaidaguerre** [comment]
instead, connection information can be injected into the _ctx column
