### ISSUE TITLE
plugin install fails when .steampipe/tmp is on a different partition than .steampipe/plugins

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe#527]
**Describe the bug**
plugin install fails when .steampipe/tmp is on a different partition than .steampipe/plugins. 
**Steampipe version (`steampipe -v`)**
0.5.1

**To reproduce**
mount ~/.steampipe/tmp on a separate partition than ~/.steampipe/tmp and attempt to install a plugin

**Expected behavior**
The plugin should be installed.  

**Additional context**
 I had thought this was fixed previously, but I couldnt find the issue.  From the code, it looks like its still doing a 'rename' style move instead of a copy and delete.  For example:  https://github.com/turbot/steampipe/blob/main/ociinstaller/plugin.go#L100

**Comment by e-gineer** [comment]
I believe this was fixed previously from `/tmp` across to assuming that `~/.steampipe` would always be on the same partition, so a move from `~/.steampipe/tmp` in that context would be safe.

IMO, we should initially save the files into the same `~/.steampipe/plugins` directory and just rename them there.

**Comment by johnsmyth** [comment]
@e-gineer If it is acceptable to require write access to the plugin directory that fine, but it does mean that the plugin directory has to be mounted as writable, which has implications if you want to pre-install plugins into a container that you want to run with a read-only root filesystem.

**Comment by johnsmyth** [comment]
@e-gineer - on the other hand, i suppose its unlikely that you would both want to pre-isntall plugins, and also allow plugins to be installed in the running instance it you are running read-only ?

**Comment by e-gineer** [comment]
I think it’s fine - if the plugin for is available for install then it’s already writable, so tmp download files in there are no worse
