### ISSUE TITLE
`--separator` doesnt work with `steampipe check`

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe#544]
**Describe the bug**
`--separator` doesnt work with `steampipe check`, either with `--output csv` or `--export csv`

**Steampipe version (`steampipe -v`)**
main commit e5b99605cf49dca140d2d83227bc7e59690193b7 

**To reproduce**
 `steampipe check benchmark.cis_v130_2_1 --output csv --export csv:x.psv --separator "|"`

**Expected behavior**
The specified separator ( '|' in this case) should be used in the csv output and export.

**Comment by cbruno10** [comment]
I've encountered this bug again, along with a user, running commands like:
```
steampipe --search-path my_account_name_from_aws_config check --output csv --separator ';' benchmark.ec2
steampipe check control.cis_v150_3_1 --search-path aws_b --output csv "--separator=|"
steampipe check control.cis_v150_3_1 --search-path aws_b --output csv --separator ";"
```

All of these commands still output the data with `,` as the separator. Are the commands above formatted incorrectly?
