### ISSUE TITLE
bash completion bugs

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe#552]
**Describe the bug**
1. Following the instructions from `steampipe completion --help` , I did `source <(steampipe completion bash)`, but it seemed to have no effect at all.
2. I then did `steampipe completion bash > /usr/local/etc/bash_completion.d/steampipe`  (also per `steampipe completion --help`). I received errors.  Upon inspection, the ` /usr/local/etc/bash_completion.d/steampipe` file had output from the auto-update check in it which was causing the error.
3. I removed the autupdate code and sourced the file, but auto-complete still did not work.

**Steampipe version (`steampipe -v`)**
commit 0dad39053d066cefda6890d467fec8c79ab9da68
on mac os:
```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
```

**Comment by kaidaguerre** [comment]
closing as covered by https://github.com/turbot/steampipe/issues/481 (which has been reopened)
