### ISSUE TITLE
Support Linux package managers(`apt-get`, `yum`, `snap`)

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#595]

**Comment by pskrbasu** [comment]
**DONE**
- Customized our goreleaser to create RPM and DEB packages, for yum and apt support
- Can upload to the Google Artifact Registry repositories manually.

**LEFT**
- Creating documentation for end-users on how to configure their machines to receive from our yum and apt repositories hosted on GCP 
- Uploading the RPM and DEB packages to their repos as a part of the release workflow.
- Wrapping the repository URLs
