### ISSUE TITLE
`steampipe query` in different `install-dir` without `service` fails with port clash unless a different port is specified

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#623]
Reproductions 

Start two terminals

In `Terminal 1` execute:
```
$ steampipe query
```

In `Terminal 2` execute:
```
$ steampipe query --install-dir ~/another-dir
```

The second `query` session will never start, unless either one of the two is started as a `service` on a different port.

This happens because both services are trying to bind to `9193`.

**Comment by kaidaguerre** [comment]
The problem is a port clash

Potential solution - StartImplicitService should respect the port specified in the HCL db config

When the service is being started up during install (before the config has been read), a random db port should be used (this service instance is just for the installation)

**Comment by kaidaguerre** [comment]
if a check session is running, and `steampipe query` is run for a different install dir, the check session fails with the error `error creating transaction: pq: SSL is not enabled on the server`

trying to restart check session gives the error `failed to start service: cannot listen on port 9193`
