### ISSUE TITLE
ERROR: context canceled - rendered when 2 terminal executes same control.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe#704]
**Describe the bug**
I tried to run the same control i.e. steampipe check all  in 2 terminal tab, it seems, when it runs in 1 terminal, then in the other one it throws below error, is this expected ?
```
 + Disks attached to stopped instance should be reviewed .........................................................................................................................  1 /  1 [=         ]
  | | 
  | ERROR: context canceled
  | 
  + ECS disks with high IOPS should be reviewed ...................................................................................................................................  1 /  1 [=         ]
  | | 
  | ERROR: context canceled
  | 
  + Disks with over 100 GB should be resized if too large .........................................................................................................................  1 /  1 [=         ]
  | | 
  | ERROR: context canceled 
```

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by binaek89** [comment]
@rajlearner17 

We were unable to reproduce this issue. Do you have any reproduction steps that we can work with?
