### ISSUE TITLE
Issues with aws_ec2_instance table

### ISSUE THREAD

**Issue by privoblaine** [turbot/steampipe#705]
I have been trying to run a query on aws_ec2_instance and continually get the below error with different results every run.  I have confirmed other tables work fine and also had a co-worker try the table in question and it failed for them too. I am expecting about 115 results but the most  I have ever gotten was 20. 

Error: failed to populate column 'state_transition_time': rpc error: code = Internal desc = transform ec2InstanceStateChangeTime failed with panic runtime error: index out of range [1] with length 0 

**Steampipe version**
steampipe version 0.7.0

**To reproduce**
select instance_id,account_id, region from aws_ec2_instance
or
select * from aws_ec2_instance

**Expected behavior**
I would expect this to return all instances, instead of a small portion or none. 

**Additional context**

**Comment by e-gineer** [comment]
Thanks for using Steampipe and reporting this issue @privoblaine. It sounds like the Steampipe AWS plugin is not properly handling the received data for the state change time field for at least one of your instances.

I believe the problem line of code is https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_ec2_instance.go#L583

As a workaround, if you query the `aws_ec2_instance` table without including the `state_transition_time` column then I believe it should work. The problem code will only be run if that specific column is requested (including via `select * ...`), so you should be able to avoid the bug if you avoid that column in your results.

**Comment by privoblaine** [comment]
I have tried this without the `state_transition_time` and am unfortunately getting the same results. I did however update to 0.7.1 and this still looks to be an issue albeit slightly better in that it is returning more results. Below is an example of the query I am using which doesn't select `state_transition_time`
`select instance_id,account_id, region from aws_ec2_instance`

**Comment by e-gineer** [comment]
Bummer ... We'd definitely avoid the bug if it was a `Hydrate` internally (extra API call for the column), but I think because it's just a transform the workaround is not effective.

Thanks again for the bug report, we'll look into a fix.

**Comment by bigdatasourav** [comment]
The above issue is resolved. https://github.com/turbot/steampipe-plugin-aws/pull/574

**Comment by privoblaine** [comment]
This ran successfully this morning after a plugin update. Thanks, guys you all rock!
