### ISSUE TITLE
Integration with Prometheus

### ISSUE THREAD

**Issue by MaikiGirardi** [turbot/steampipe#759]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i discover that some vendors doesn't integrate with grafana or prometheus or if they do, they do poorly, without focus on having a great service. 

**Describe the solution you'd like**
Steampipe is awesome, and it will be nice if we have a oficial prometheus exporter to query Steampipe and bring data into his TSDB and simplify integration to most cloud vendors and other apps in a unified method. OCI is an example on how things could be better.

**Comment by e-gineer** [comment]
Hi @MaikiGirardi ... thanks for using Steampipe!

Do you have suggestions or a detailed outline of how you'd like an integration with Prometheus / Grafana to work? What data are you expecting to see? I suspect you have a deeper working knowledge of those tools than we do, so it would be great to get some detailed insights into how we could make Steampipe work the way you'd like!

**Comment by graza-io** [comment]
Hi @MaikiGirardi 

If you run Steampipe in service mode it's basically an exposed PostgreSQL database, this means you can utilise the following.

- Directly attach it to Grafana as a data source for obtaining information in which you don't need time-series data (e.g. current up/down status of servers).
- Utilise the community-driven [Prometheus exporter for PostgreSQL](https://github.com/prometheus-community/postgres_exporter) to obtain exported time-series information, this [section](https://github.com/prometheus-community/postgres_exporter#adding-new-metrics-via-a-config-file) of the readme file explains how to add custom metrics via a configuration file, which means you can query anything via Steampipe and output it into the exported data.

Hope this is helpful.
