### ISSUE TITLE
Is = required when specifying variable values with the `--var` arg?

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#777]
**Describe the bug**
When I give am improperly formatted `--var` value, I get a message saying it's not correctly specified:
```
Codys-MBP:tagsaws cbruno$ steampipe check benchmark.mandatory --var 'v3=[test2, test3]'
Error: failed to load workspace: Invalid -var option: The given -var option " test3]" is not correctly specified. Must be a variable name and value separated by an equals sign, like -var="key=value".
```

There are two potential issues I think:
- It should be `--var` instead of `-var`
- The message says it must be separated by an equal sign, but I believe using a space works, e.g., `--var my_var=value`

**Steampipe version (`steampipe -v`)**
v0.7.2 (built from `main` branch at time of issue creation)

**To reproduce**
Create a variable:
```
variable "v3" {
    type = list(object({
        internal = number
        external = number
        query = string
    }))
}
```

And then run `steampipe check benchmark.mandatory --var 'v3=[test2, test3]'`

**Expected behavior**
The help message is correct.

**Additional context**

**Comment by cbruno10** [comment]
Terraform examples all include an `=`, but in Steampipe, all of our args allow the use of equal or space delimiters.

**Comment by kaidaguerre** [comment]
Have updated the error message to 
```
Error: failed to load workspace: The given --var option "column" is not correctly specified. Must be a variable name and value separated an equals sign: --var key=value
```

**Comment by kaidaguerre** [comment]
note: the equals sign referred to in the message is the one after `var`, which must be an equals. 

However as you rightly point out, there is no need for the equals sign after `--var` so I have updated the example in the message to reflect this
