### ISSUE TITLE
Required "quals" error message should be more informative

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#80]
From https://github.com/turbot/steampipe-plugin-github/issues/6 we see the error message:

    Error: pq: rpc error: code = Internal desc = 'List' call requires an '=' qual for column: login

causing confusion & delay.

Can we standardize / catch / improve that error message to be more helpful?

**Comment by pskrbasu** [comment]
Now the error is slightly more informative.
`'List' call for table 'github_user' is missing 1 required qual: column:'login' operator: =`
