### ISSUE TITLE
Small suggested updates to the `steampipe service *` output

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#812]
For steampipe service here is the sequence of output I see:
```
~/src/steampipe-plugin-fastly $ steampipe service start

Steampipe database service is now running:

	Host(s):  localhost, 127.0.0.1, 192.168.7.220
	Port:     9193
	Database: steampipe
	User:     steampipe
	Password: 0068-XXXX-XXXX
	SSL:      on

Connection string:

	postgres://steampipe:0068-XXXX-XXXX@localhost:9193/steampipe?sslmode=require

Managing Steampipe service:

	# Get status of the service
	steampipe service status
	
	# Restart the service
	steampipe service restart

	# Stop the service
	steampipe service stop
	

~/src/steampipe-plugin-fastly $ 
~/src/steampipe-plugin-fastly $ steampipe service stop
Steampipe database service stopped
~/src/steampipe-plugin-fastly $ steampipe service status
Steampipe database service is NOT running
~/src/steampipe-plugin-fastly $ 
```

Suggestions:
* Use two spaces instead of tabs to indent the text.
* Remove `?sslmode=require`, it's preferred anyway and we don't technically require it.
* Remove `SSL: on` line, we provide no way to disable it anyway.
* Double line gap at the end should be a single line gap only.
* `Managing Steampipe service:` should be `Managing the Steampipe service:`
* References to `database service` should just be `service` (simpler)
* `Steampipe database service stopped` message should be `Steampipe service stopped [port 9193].`
* `Steampipe database service is NOT running` message should be `Steampipe service is not running [port 9193].`

**Comment by binaek89** [comment]
@e-gineer 

on the last point: 
`Steampipe database service is NOT running` message should be `Steampipe service is not running [port 9193].`

This message comes up when there's no service running. We do not have a statefile here.

Should we put in the default port here?

**Comment by e-gineer** [comment]
@binaek89 I think when running `steampipe service status` we should know which port we'd expect it to be on? (We must since we can do `steampipe service start`.) So we can just use that? Is that the default port you mention?

**Comment by binaek89** [comment]
@e-gineer we know of the port that the service is running on when it is running, but when it's not, and we say that the _service is not running_, should we mention the default port?
