### ISSUE TITLE
`steampipe query *.sql` hangs if a query returns an error

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#823]
I run a series of SQL queries in a single command:
```
steampipe --search-path-prefix steampipe_slack,github query *.sql
```

But, the last query (of 5) seems to fail sometimes per #822.

When one query fails with an error, the whole `steampipe query *.sql` hangs indefinitely on that query.

I'd expect that query to return an error string or similar instead of hanging the whole terminal command.

**Comment by kaidaguerre** [comment]
cannot reproduce
