### ISSUE TITLE
Running a control with the `query` property in interactive mode fails

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#829]
**Describe the bug**
Running any control in REPL/interactive mode results in the error `Error: syntax error at or near "query"`

**Steampipe version (`steampipe -v`)**
v0.7.3 (from `add_support_for_passing_parameters_to_queries_802` branch at time of issue creation)

**To reproduce**
Add a `query` property to a control and run it in `steampipe query` interactive mode with `control.control_name`.

**Expected behavior**
The control should run.

**Additional context**

**Comment by kaidaguerre** [comment]
fixed by 58f4b07449a21e7db836245833423c65d8441124
