### ISSUE TITLE
Array parameters are returned as json instead of jsonb

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#830]
**Describe the bug**
Array parameters, e.g., `["Test", "Test1"]`, come back as type `json` but should be coming back as `jsonb` instead

**Steampipe version (`steampipe -v`)**
v0.7.3 (from `add_support_for_passing_parameters_to_queries_802` branch at time of issue creation)

**To reproduce**
- Define a parameter and set its default value as a list of strings as value, e.g., `["Test", "Test1"]`
- Use that parameter in a SQL statement and check its type

**Expected behavior**
The value should be of type jsonb

**Additional context**

**Comment by kaidaguerre** [comment]
closed by 58f4b07449a21e7db836245833423c65d8441124
