### ISSUE TITLE
Rename `params` -> `param` when defining parameters in a query

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#831]
**Describe the bug**
Today, when defining a new parameter, I use the syntax:
```
query "ec2_instance_mandatory_tag_keys" {
  title  = "EC2 instances have mandatory tags"
  description = "Check if EC2 instances have mandatory tag keys."
  sql = replace(local.sql_query, "__TABLE_NAME__", "aws_ec2_instance")
  params "mandatory_tag_keys" {
    default = var.mandatory_tag_keys
  }
}
```

I believe `params` should be `param` instead

**Steampipe version (`steampipe -v`)**
v0.7.3 (from `add_support_for_passing_parameters_to_queries_802` branch at time of issue creation)

**To reproduce**
Create a new query resource and add a `param` property, and then attempt to run the query.

**Expected behavior**
The `params` property should be renamed to `param`.

**Additional context**

**Comment by kaidaguerre** [comment]
closed by 58f4b07449a21e7db836245833423c65d8441124
