### ISSUE TITLE
Allow param properties to be defined in controls, rename params->args, and restrict args use with query property

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe#832]
**Is your feature request related to a problem? Please describe.**
- I'd like to be able to define controls and use params with them, without also defining a `query` resource type, e.g.,
  ```
  control "ec2_instance_mandatory_tag_keys" {
    title  = "EC2 instances have mandatory tags"
    description = "Check if EC2 instances have mandatory tag keys."
    sql = <<EOT
      select $1 as test from aws_ec2_instance;
    EOT
    param "test" {
      default = "Test"
    }
  }
  ```
- The `params` property should be renamed to `args`
- The `args` property should only be usable in controls if `query` is also defined, e.g.,

  Valid:
  ```
  control "ec2_instance_mandatory_tag_keys" {
    title  = "EC2 instances have mandatory tags"
    description = "Check if EC2 instances have mandatory tag keys."
    query = query.my_query
    args = {
      "test": "New test value"
    }
  }
  ```

  Invalid:
  ```
  control "ec2_instance_mandatory_tag_keys" {
    title  = "EC2 instances have mandatory tags"
    description = "Check if EC2 instances have mandatory tag keys."
    sql = <<EOT
      select $1 as test from aws_ec2_instance;
    EOT
    args = {
      "test": "New test value"
    }
  }
  ```

**Describe the solution you'd like**
- Using `query` and `args` properties together is valid
- Using `sql` and `param` properties together is valid
- `args` and `param` are optional

**Describe alternatives you've considered**

**Additional context**

**Comment by kaidaguerre** [comment]
closed by 58f4b07449a21e7db836245833423c65d8441124
