### ISSUE TITLE
Holding left or right arrow pressed in interactive prompt deletes random characters

### ISSUE THREAD

**Issue by pdecat** [turbot/steampipe#865]
**Describe the bug**
When pressing and holding left or right arrow in interactive prompt, some characters are unexpectedly deleted or replaced by `[D`/`[C` sequences.

**Steampipe version (`steampipe -v`)**
v0.8.0.rc.1

**To reproduce**
1. `steampipe query`
2. type a query, e.g. `select snapshot_id, tags from aws_ebs_snapshot`
3. from the end, press and hold the left arrow,
4. query is altered to something like `select snapshot_id, tags from aws_eb[D[D[Ds_snapshot`

1. `steampipe query`
2. type a query, e.g. `select snapshot_id, tags from aws_ebs_snapshot`
3. press `Home` key,
4. press and hold the right arrow,
4. query is altered to something like `select snapshot_id, tags from[C[C[C a[C[Cws_ebs_snapshot`

**Expected behavior**
The cursor should move without altering the query.

**Additional context**
Can provide a screencast if needed.

**Comment by kaidaguerre** [comment]
thanks for the report @pdecat - thats an interesting one. We'll take a look

**Comment by pdecat** [comment]
Cannot reproduce with 0.8.3.
