### ISSUE TITLE
Youtube plugin not getting installed

### ISSUE THREAD

**Issue by vinayakg** [turbot/steampipe#882]
**Describe the bug**
Youtube plugin not working

**Steampipe version (`steampipe -v`)**
v0.8.0

**To reproduce**
Run the below command from your command line
`steampipe plugin install youtube`

**Expected behavior**
Youtube plugin should get installed and the table list should be present on .tables

**Additional context**
![image](https://user-images.githubusercontent.com/1701204/132942826-ca2fc555-ce76-49fd-8bd6-204f1499b83e.png)

**Comment by e-gineer** [comment]
Thanks for using Steampipe!

Unfortunately we don’t have a YouTube plugin yet! You can see all the available plugins at https://hub.steampipe.io/plugins. (Others are in development and available on In places like GitHub.)

If there was a YouTube plugin, what tables would you be interested in? What would you be trying to use it for?
