### ISSUE TITLE
Add support for rotating service password.

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#924]

**Comment by graza-io** [comment]
Not to be rude here, but maybe consider #725 (allowing the user to specify a password) & in event they don't, auto-generate a random password on service start?

**Comment by kaidaguerre** [comment]
Apologies for the lack of feedback and clarity on this, @graza-io 

We are right now looking into implementing something satisfying https://github.com/turbot/steampipe/issues/725, and we are looking at including a rotation option as part of that solution. It is confusing to have 2 issues open, when it could have been covered by #725

In any case, we hope to have this ready soon and I be sure to keep you updated.

**Comment by kaidaguerre** [comment]
covered by #725
