### ISSUE TITLE
Plugin install should show the version actually installed

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe#93]
Currently we have 
```
$ steampipe plugin install azure
Installed plugin: azure
Documentation:    https://hub.steampipe.io/plugins/turbot/azure

$
```

I think it should be (note version & removal of blank line):
```
$ steampipe plugin install azure
Installed plugin: <bold>azure</bold><light>@0.2.0</light>
Documentation:    https://hub.steampipe.io/plugins/turbot/azure
$
```

**Comment by kaidaguerre** [comment]
like this: 
![image](https://user-images.githubusercontent.com/2838960/106262707-508d2b00-621b-11eb-8226-d6d904393845.png)

or with spaces in between the plugins but not at the end?
