### ISSUE TITLE
Ability to load Postgres conf file from a custom location.

### ISSUE THREAD

**Issue by vhadianto** [turbot/steampipe#938]
**Is your feature request related to a problem? Please describe.**
The only way to load Postgres conf file is by adding the files in a fixed location: 
`~/.steampipe/db/12.1.0/postgresql.conf.d/`

**Describe the solution you'd like**
Point Steampipe to a custom directory, i.e. `/var/custom/dir`. Not sure where we can define this, I'd like this for the `service`.

**Comment by binaek** [comment]
@vhadianto if you put a file in `~/.steampipe/db/12.1.0/postgresql.conf.d/` with the content `include_dir = '/var/custom/dir'`, it should serve what you need.

**Comment by binaek** [comment]
Closing since there are valid and workable workarounds
