### ISSUE TITLE
When running controls, the expiry of the context used to run a query causing issues creating transactions, and seems to clear the session data

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe#939]
A couple of people have reported different symptoms

1) after the context expires, we are unable to create a transaction
```3 Ensure that any identity-based policies don't use wildcard actions ........................................................................................................  1 /  1 [=     ]
  | | 
  | ERROR: context deadline exceeded
  | 
  + 4 Enable S3 protection in GuardDuty to detect suspicious activities .........................................................................................................  1 /  1 [=     ]
  | | 
  | ERROR: error creating transaction - please restart Steampipe```

This suggests the database connection is blocked for come reason - prehaps and FDW crash/freeze

2) after the context expires, the session data is cleared meaning prepared statements cannot by found

**Comment by kaidaguerre** [comment]
https://files.slack.com/files-pri/T02GC4A7C-F02EZ2WLTJS/image.png

**Comment by kaidaguerre** [comment]
![image](https://user-images.githubusercontent.com/2838960/134349903-e035f2f6-e30f-49cd-afae-253f344094aa.png)

**Comment by kaidaguerre** [comment]
To do: 
- Investigate why session data is cleared
- Look into mechanism to ensure session data exists on a connection
- Reinstate the `RefreshClient` functionality to create a new client when we fail to create a transaction. This was removed due to the session data issue
