### ISSUE TITLE
`select * from pg_prepared_statements` from `steampipe-mod-aws-compliance` freezes 

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#940]

**Comment by jackdelab** [comment]
All my queries in the interactive client mode are hanging since upgrading to v0.8.3, not sure if it's related or not. I can open a new ticket with the full error message I get if you'd like

**Comment by e-gineer** [comment]
@jackdelab definitely surprised to hear that! Please share more details if you have them. We'd definitely like more information - don't want to people suffering this problem!

I tried v0.8.3 and it's working for me. I also tried the aws compliance mod and it worked for the query above.

Tips if still stuck:
* Try killing any steampipe processes, I use `pkill -f steampipe`
* Try running from an empty directory, e.g. `/tmp/foo`

Thanks for letting us know.

**Comment by jackdelab** [comment]
I opened https://github.com/turbot/steampipe/issues/970 for my specific issue

**Comment by kaidaguerre** [comment]
fixed by 3bb4bf97d3a857ad985ba3a4f01d4f2324ea32c4
