### ISSUE TITLE
v0.8.2 release sha256 mismatch

### ISSUE THREAD

**Issue by wesley-staples** [turbot/steampipe#941]
**Describe the bug**
In this release https://github.com/turbot/steampipe/releases/tag/v0.8.2. The file checksums.txt says the checksum for steampipe_darwin_amd64.zip is 072ec5f3cee649ae1051071e485058191283c8dfd23f42dd159d9345ee880ebc. However the actual sha256 seems to be 99c75771d7f2a7770b27e9cfe4e77dbb5bfcebc7ca3d1e6d4efc74e0a1a8895e. I think this is breaking the homebrew installer which returns the error:

```
Error: steampipe: SHA256 mismatch
Expected: 072ec5f3cee649ae1051071e485058191283c8dfd23f42dd159d9345ee880ebc
  Actual: 99c75771d7f2a7770b27e9cfe4e77dbb5bfcebc7ca3d1e6d4efc74e0a1a8895e
```

**Steampipe version (`steampipe -v`)**
v0.8.2

**To reproduce**
manually download https://github.com/turbot/steampipe/releases/download/v0.8.2/steampipe_darwin_amd64.zip.

run `shasum -a 256 steampipe_darwin_amd64.zip`

**Expected behavior**
I would expect the output of shasum to match what is in the checksums.txt file.

**Comment by kaidaguerre** [comment]
thanks for reporting this @wesley-staples , I'm looking into it

**Comment by kaidaguerre** [comment]
I'm having issues reproducing @wesley-staples 
- the brew installation works for me
- the checksum in the checksum.txt is `072ec5f3cee649ae1051071e485058191283c8dfd23f42dd159d9345ee880ebc`
- the checksum in the brew formula is `072ec5f3cee649ae1051071e485058191283c8dfd23f42dd159d9345ee880ebc`
- the output of shasum is `072ec5f3cee649ae1051071e485058191283c8dfd23f42dd159d9345ee880ebc`

![image](https://user-images.githubusercontent.com/2838960/134359493-91fbd7c4-20e9-4c9f-95a8-5adf83832683.png)
 
Please could you double check and see if you get the same results

**Comment by wesley-staples** [comment]
You are correct I downloaded this on my person windows machine and everything checked out. It must be some security software I have on this company mac. Sorry for wasting your time.

**Comment by e-gineer** [comment]
Even though a false negative in this case we appreciate you using Steampipe and letting us know! Thanks for confirming 👍
