### ISSUE TITLE
Issue while running brew tap turbot/tap command

### ISSUE THREAD

**Issue by sankeyraut** [turbot/steampipe#943]
**Describe the bug**
I am trying to create a docker image for steampipe. I am using amazon linux and have installed linuxbrew
I am able to run and install `brew install hello` which indicates brew is installed successfully
I am able to add tap for aws by running `brew tap aws/tap`

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**To reproduce**
Using following docker file

```
FROM amazonlinux:latest

# Update AmazonLinux
RUN yum update -y

# Homebrew requirements
RUN yum groupinstall 'Development Tools' -y \
    && yum install curl file git sudo which -y

# Create linuxbrew user
# https://hub.docker.com/r/linuxbrew/linuxbrew/dockerfile
RUN useradd -m -s /bin/bash linuxbrew && echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers
USER linuxbrew
WORKDIR /home/linuxbrew
ENV PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH \
    SHELL=/bin/bash \
    USER=linuxbrew \
    HOMEBREW_NO_ANALYTICS=1 \
    HOMEBREW_NO_AUTO_UPDATE=1

# Install Homebrew
# https://brew.sh/
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" \
    && brew tap homebrew/core \
    && brew cleanup \
    && rm -rf .cache

# Install brew bundle (optional)
RUN brew tap homebrew/bundle \
    && brew cleanup \
    && rm -rf .cache

# NB: the trick below allows us to rebuild only that layer of the image whenever we run
# a `docker build` : this way we keep an up-to-date Homebrew without having to rebuild everything
ARG TIMESTAMP=unknown
RUN TIMESTAMP=${TIMESTAMP} brew update \
    && brew upgrade \
    && brew cleanup \
    && rm -rf .cache

RUN brew install hello
RUN brew tap aws/tap
RUN brew tap turbot/tap
RUN brew install steampipe

```
I get the following error

```
 => ERROR [10/14] RUN brew tap turbot/tap                                                                                                                                                               4.8s
------
 > [10/14] RUN brew tap turbot/tap:
#14 1.220 ==> Tapping turbot/tap
#14 1.239 Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/turbot/homebrew-tap'...
#14 4.694 Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/turbot/homebrew-tap/Formula/steampipe.rb
#14 4.694 formulae require at least a URL
#14 4.804 Error: Cannot tap turbot/tap: invalid syntax in tap!
------
```

**Expected behavior**
It is expected that the tap should be added successfully and steampipe to be installed on docker container

**Additional context**

**Comment by e-gineer** [comment]
Thanks for raising this @sankeyraut. Interesting that you appear to be trying to use brew from Linux ... I'm not sure how much we've tested this, we were mostly focused on OSX there.

I'm not a brew expert, but looking at the Formulae it looks like we might not even have a Linux section...

https://github.com/turbot/homebrew-tap/blob/main/Formula/steampipe.rb

**Comment by pskrbasu** [comment]
@sankeyraut Thank you for raising this. As @e-gineer mentioned, we currently do not have support for Linux in our brew, but we are working on adding support for Linux.

**Comment by pskrbasu** [comment]
Hello @sankeyraut We have updated our brew formulae to support Linux. You can try it out. Let us know if you face any issues.
