### ISSUE TITLE
all releases found for one repo, but not another

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#967]
I'm comparing the `github_release` table for `turbot/steampipe` vs `turbot/steampipe-plugin-github`, and only finding 1 release for the latter.

```
> select count(*) from github_release where repository_full_name = 'turbot/steampipe'
+-------+
| count |
+-------+
| 14    |
+-------+

> select count(*) from github_release where repository_full_name = 'turbot/steampipe-plugin-github'
+-------+
| count |
+-------+
| 1     |
+-------+

```
I can find tags:
```
> select count(*) from github_tag where repository_full_name = 'turbot/steampipe-plugin-github'
+-------+
| count |
+-------+
| 14    |
+-------+
```

Why is `github_release` not seeing corresponding releases?

While doing this, the following error happened a few times but now I can't repro.

> select * from github_release where repository_full_name = 'turbot/steampipe'

Error: failed to populate column 'published_at': rpc error: code = Internal desc = transform convertTimestamp failed with panic runtime error: invalid memory address or nil pointer dereference

**Comment by e-gineer** [comment]
Thanks @judell. Tags and Releases are similar, but different. The GitHub plugin actually only has 1 release defined in GitHub - so I believe that result is correct. See https://github.com/turbot/steampipe-plugin-github/releases

Suggest you open a separate issue for `published_at` if you can narrow it down.

**Comment by judell** [comment]
> The GitHub plugin actually only has 1 release defined in GitHub

OK, I see that, was indeed conflating tags vs releases at https://github.com/turbot/steampipe-plugin-github/releases. 

Will close this and open the other, which is happening a lot now as I poke around in this area.

**Comment by judell** [comment]
Following up, @e-gineer, as part of spelunking to showcase the github plugin, I found that if I focus on just plugins and mods there are only these releases:

```
            full_name             | releases
----------------------------------+----------
 turbot/steampipe-mod-aws-thrifty |        3
 turbot/steampipe-plugin-github   |        1
 ```
 
Spot-checking the list below, that appears to be the case.  Is presence/absence of a release for a plugin/mod meaningful to users?

 https://github.com/turbot/steampipe-mod-kubernetes-compliance/releases             
 https://github.com/turbot/steampipe-mod-aws-top10/releases                         
 https://github.com/turbot/steampipe-mod-gcp-compliance/releases                    
 https://github.com/turbot/steampipe-mod-aws-thrifty/releases                       
 https://github.com/turbot/steampipe-mod-aws-tags/releases                          
 https://github.com/turbot/steampipe-mod-alicloud-thrifty/releases                  
 https://github.com/turbot/steampipe-mod-gcp-labels/releases                        
 https://github.com/turbot/steampipe-mod-oci-compliance/releases                    
 https://github.com/turbot/steampipe-mod-azure-compliance/releases                  
 https://github.com/turbot/steampipe-mod-aws-compliance/releases                    
 https://github.com/turbot/steampipe-mod-gcp-thrifty/releases                       
 https://github.com/turbot/steampipe-mod-oci-tags/releases                          
 https://github.com/turbot/steampipe-mod-googleworkspace-compliance/releases        
 https://github.com/turbot/steampipe-mod-alicloud-compliance/releases               
 https://github.com/turbot/steampipe-mod-azure-tags/releases                        
 https://github.com/turbot/steampipe-plugin-okta/releases                           
 https://github.com/turbot/steampipe-mod-jira-sherlock/releases                     
 https://github.com/turbot/steampipe-plugin-pokemon/releases                        
 https://github.com/turbot/steampipe-mod-github-sherlock/releases                   
 https://github.com/turbot/steampipe-mod-bitbucket-sherlock/releases                
 https://github.com/turbot/steampipe-plugin-gcp/releases                            
 https://github.com/turbot/steampipe-mod-digitalocean-thrifty/releases              
 https://github.com/turbot/steampipe-mod-azure-thrifty/releases                     
 https://github.com/turbot/steampipe-mod-jira-thrifty/releases                      
 https://github.com/turbot/steampipe-plugin-github/releases                         
 https://github.com/turbot/steampipe-plugin-rss/releases                            
 https://github.com/turbot/steampipe-plugin-bitbucket/releases                      
 https://github.com/turbot/steampipe-plugin-abuseipdb/releases                      
 https://github.com/turbot/steampipe-plugin-chaos/releases                          
  https://github.com/turbot/steampipe-mod-web-compliance/releases                 
 https://github.com/turbot/steampipe-mod-zoom-compliance/releases                
 https://github.com/turbot/steampipe-plugin-gitlab/releases                      
 https://github.com/turbot/steampipe-plugin-alicloud/releases                    
 https://github.com/turbot/steampipe-plugin-tfe/releases                         
 https://github.com/turbot/steampipe-plugin-cloudflare/releases                  
 https://github.com/turbot/steampipe-mod-oci-thrifty/releases                    
 https://github.com/turbot/steampipe-plugin-azure/releases                       
 https://github.com/turbot/steampipe-plugin-turbot/releases                      
 https://github.com/turbot/steampipe-plugin-googledirectory/releases             
 https://github.com/turbot/steampipe-plugin-azuread/releases                     
 https://github.com/turbot/steampipe-plugin-sdk/releases                         
 https://github.com/turbot/steampipe-plugin-code/releases                        
 https://github.com/turbot/steampipe-plugin-aws/releases                         
 https://github.com/turbot/steampipe-plugin-twitter/releases                     
 https://github.com/turbot/steampipe-plugin-googleworkspace/releases             
 https://github.com/turbot/steampipe-plugin-shodan/releases                      
 https://github.com/turbot/steampipe-plugin-digitalocean/releases                
 https://github.com/turbot/steampipe-plugin-equinix/releases                     
 https://github.com/turbot/steampipe-plugin-updown/releases                      
 https://github.com/turbot/steampipe-plugin-grafana/releases                     
 https://github.com/turbot/steampipe-plugin-slack/releases                       
 https://github.com/turbot/steampipe-plugin-docker/releases                      
 https://github.com/turbot/steampipe-plugin-fastly/releases                      
 https://github.com/turbot/steampipe-plugin-urlscan/releases                     
 https://github.com/turbot/steampipe-plugin-hackernews/releases                  
 https://github.com/turbot/steampipe-plugin-splunk/releases                      
 https://github.com/turbot/steampipe-plugin-kubernetes/releases                  
 https://github.com/turbot/steampipe-plugin-virustotal/releases                  
 https://github.com/turbot/steampipe-plugin-finance/releases                     
 https://github.com/turbot/steampipe-plugin-zendesk/releases

**Comment by e-gineer** [comment]
We don't currently formally release the plugins or mods on GitHub. Any releases that exist for them should be deleted IMO as mistakes.

CC @cbruno10
