### ISSUE TITLE
Queries in the interactive client are failing

### ISSUE THREAD

**Issue by jackdelab** [turbot/steampipe#970]
**Describe the bug**
Queries which work from the shell and return results within seconds hang for several minutes then produce an enourmous error message when run from the interactive client

**Steampipe version (`steampipe -v`)**
steampipe version 0.8.3

**Plugin versions**
+--------------------------------------------------+---------+-------------+
| Name                                             | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.32.1  | aws         |
| hub.steampipe.io/plugins/turbot/azure@latest     | 0.18.0  | azure       |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.1.3   | steampipe   |
+--------------------------------------------------+---------+-------------+

**To reproduce**
`$ steampipe query "select arn from aws.aws_kms_key limit 10"`
results are returned within 2 seconds
`$ steampipe query`
`> select arn from aws.aws_kms_key limit 10`
"Loading results..." is displayed for several minutes, followed by the error message in the attached file [steampipe_error.txt](https://github.com/turbot/steampipe/files/7253105/steampipe_error.txt). Presumably the error message is even longer and I am only getting the last 1000 lines of it.

**Expected behavior**
Queries perform the same in the interactive client as they do from the shell.

**Additional context**
This problem is also affecting queries run through the Postgres connection to the Steampipe process.

**Comment by kaidaguerre** [comment]
@jackdelab thanks for reporting this, I'll look into it

**Comment by kaidaguerre** [comment]
@jackdelab I have pushed a fix which I hope resolves this issue - I could not reproduce your exact failure but I believe this addresses the underlying issue. Please try updating Steampipe to 0.8.4 see if it behaves better
