### ISSUE TITLE
[Bug]: [UI]: the copy to clipboard icon should not move along with the query output

### ISSUE THREAD

**Issue by vkumbha** [turbot/steampipe#98]
- Navigate to https://steampipe.io/docs and click on `Learn Steampipe` (I dont know, there isn't a direct link to that page?).
- Scroll down to the `Query` section and look for the output of the query 
- Scroll towards the right end of the output to find the icon moving to the left.
```
select
  instance_id,
  security_groups,
  tags
from
  aws_ec2_instance;
```
![image](https://user-images.githubusercontent.com/40973863/106260194-21d87a00-6246-11eb-9a68-2fe45deab2ee.png)

**Comment by MichaelBurgess** [comment]
Wrong repo
