### ISSUE TITLE
mod csv export should omit control characters

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#981]
I ran this command.

```
steampipe check all --output csv  > output.csv
```

The output is like this.

![image](https://user-images.githubusercontent.com/46509/135679422-00ded5d8-8aba-4c75-8230-f2b76172aaa5.png)

I had to delete the preamble in order to be able to work with the data in Excel.

This is not a problem for JSON export, which also gives a nice summary.

```
  "summary": {
    "status": {
      "alarm": 66,
      "ok": 38,
      "info": 81,
      "skip": 0,
      "error": 0
    }
```

But most people who want to work with the data will expect to export to CSV, then import to a spreadsheet or database.

**Comment by kaidaguerre** [comment]
this is expected behaviour and can be avoided using the `--progress=false` or `--export csv` flags
