### ISSUE TITLE
FR: Open link in new tab for Blog Posts

### ISSUE THREAD

**Issue by vkumbha** [turbot/steampipe#99]
- I wish the blog posts at https://steampipe.io/blog had the "Open Link in New Tab" options.
- Tried Chrome Version 87.0.4280.141 (Official Build) (x86_64) and Safari Version 14.0 (15610.1.28.1.9, 15610)
![image](https://user-images.githubusercontent.com/40973863/106260556-885d9800-6246-11eb-87f5-33ec14a2cc3f.png)

**Comment by MichaelBurgess** [comment]
Wrong repo
